### DISCUSSION TITLE
Expand environment variables when loading config file from disk

### DISCUSSION THREAD

**Discussion by pbarnum** [Lissy93/dashy#1060] [Ideas]
Hello!

I have an API endpoint that I want to pull information from, but it requires basic authentication to work. Since this is configured with the `conf.yml` file, I don't feel comfortable adding the user/pass to it as plain text (or base64 encoded). Could Dashy instead expand environment variables found within the `config.yml` file?

For example:
```yaml
# I *think* this is why my PiHole stats are not working, since they previously did when I didn't have a password set up
  - name: PiHole
    icon: fas fa-raspberry-pi
    widgets:
      - type: pi-hole-stats
        useProxy: true
        options:
          hostname: http://$PIHOLE_USERNAME:$PIHOLE_PASSWORD@pihole.local
        id: 0_577_piholestats
```

If this isn't why my stats are not showing up, then we can start a new thread in the help channel.

Thank you!
Patrick
