### DISCUSSION TITLE
Pages Example

### DISCUSSION THREAD

**Discussion by quartzeye** [Lissy93/dashy#1153] [Help and Support] [answered]
Can someone provide a working Pages example?  Or at least show the code on WHERE you add it to the config.yml.  I have cut and pasted the sample snippet from the docs all over the place and have yet  to see it work.  Also for future reference, snippets suck and should be shown with proper context in a fully functional yaml file. The descriptive text isn't sufficient to know where the proper formatted section should go.  Maybe I am just too slow to figure it out but it is clear the documentation is written in a way that without inherit knowledge not conveyed in the docs, you likely will be unable to make sense of it.  Sorry for the rant but it is frustrating when only a snippet is provided that cannot work on it's own and no example of its proper use is provided anywhere that I have been able to find.

**Comment by quartzeye** [comment]
So I found the animated GIF but was unable to catch any info from it until I downloaded it and burst it into individual frames.  

So the Pages section goes at the top of the config.yml file.  Did that, see that button.  I placed the sub-page yaml in the /app/public folder and entered it into the path attribute.  No navigation was done.  The sub-page did not display and it is a valid copy of a working config.yml page.  I also enter the explicit path to the file and still no navigation.  I moved the page to another nested directory and still no navigation to it. Permissions on files are wide open.

I don't see how to place an item on the page and have it navigate to the sub-page yaml file either.  Why is there nothing similar to the links pages on Firefox and Chrome with the ability to set an item to a path rather than a URL?  That is all I need.  The ability to set an item to a path that loads a sub-page.  Not a button at the top, which doesn't seem to work either.

It looks like the only way to achieve what I am trying to do is to run multiple instance of Dashy on different ports with item link  so that I can get the equivalent that is native in Firefox and Chrome.  Seems a whole lot of redundant for a basic capability to have an item link to a sub links page for organizing links.  Btw, I tried this same thing with pages and using a URL for path and got no navigation from the button either so I don't think the pages/sub-pages are working or they are not documented correctly to make them work.

**Reply by cmro** [reply]
I had the same problem and after some try and error, I finally got it working. Here is my (simplified) configuration:

conf.yml:
```
appConfig:
  theme: callisto
  layout: auto
  iconSize: large
  language: en
pages:
- name: Main Dashboard
  path: 'main.yml'
- name: Secondary dashboard
  path: 'secondary.yml'
sections: [] 
```

main.yml:
```
pageInfo:
  title: Dashy
  description: Welcome to your new dashboard!
  navLinks:
    - title: GitHub
      path: https://github.com/Lissy93/dashy
    - title: Documentation
      path: https://dashy.to/docs
sections:
  - name: Getting Started
    icon: fas fa-rocket
    items:
      - title: Dashy Live
        description: Development a project management links for Dashy
        icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: https://live.dashy.to/
        target: newtab
        id: 0_1481_dashylive
```

The `secondary.yml` is built the same way as main.yml, but with different pageInfo and sections. **Important:**  After changing the page structure, you have to rebuild the page using the "Update config/Rebuild application"-Button. This is mentioned in the "Restrictions"-Chapter of the documentation. This took a few minutes and after the next page reload, everything works as expected.
