### DISCUSSION TITLE
Hide settings menu for guestUsers

### DISCUSSION THREAD

**Discussion by bahattinseyhan** [Lissy93/dashy#1173] [Help and Support]
I want to hide the UI for settings menu, which includes Layout, Item Size, and Config options for Guest Users.

Disable all UI Config for non admin users is checked. But not working.

![Screenshot 2023-05-04 100825](https://user-images.githubusercontent.com/116269668/236146655-b214fe94-8dfb-47a9-a957-14cc306c54d1.png)

If anyone has any experience with this or can point me in the right direction, I would greatly appreciate it.

Thanks in advance!

**Comment by soloctl** [comment]
1, you may want to identify the right permission scope and user experience of you underlying requirement. for instance, appConfig.disableConfigurationForNonAdmin allows you to disable the pencil(grey out) and once open the wrench, the view config and edit config options are disabled(greyed out).

2, if you feel the build in experience is still not sufficient, you can config by adding component v-if under a certain permission. disableConfigurationForNonAdmin=true will set allowViewConfig to false for none admin users, one example you can custom SettingsContainer.vue file, add     `allowViewConfig() { return this.$store.getters.permissions.allowViewConfig; },` in the `computed: ` values, add `v-if="allowViewConfig"` for the `class="options-outer"` div, this will make the "options-outer" disappear once allowViewConfig is false. 

Hope the above example helps.

**Reply by Maxiksan** [reply]
do you know how to hide the settings icon because when i tried your code, it was not working.
Thanks in advance

**Reply by gdelfavero** [reply]
I'm missing where to change the setting appConfig.disableConfigurationForNonAdmin. I tried in the conf.yml file and set it to true, but it doesn't seem to restrict admin to edit pages (not write to disk).

```
pageInfo:
  title: Dashy
  description: My Dashy ltd.
  navLinks:
    - title: GitHub
      path: https://github.com/Lissy93/dashy
    - title: Documentation
      path: https://dashy.to/docs
appConfig:
  theme: nord-frost
  layout: horizontal
  iconSize: large
  auth:
    disableConfigurationForNonAdmin: true
    enableGuestAccess: false
    users:
      - user: Admin
        hash: somethingsomething
        type: admin
      - user: Prox
        hash: somethingsomething
        type: normal
sections:
  - name: Getting Started
    icon: fas fa-rocket
    items:
....
```
