### DISCUSSION TITLE
Unable to get Proxmox list widget to work

### DISCUSSION THREAD

**Discussion by developingchet** [Lissy93/dashy#1315] [Help and Support]
Error:
```
An error occurred, see the logs for more info.

Unable to fetch data
```
Here is the code block for my proxmox-list:

```
sections:
  - name: Server Management
    icon: ''
    items:
      - title: xxxxxxxxxx
        description: ''
        icon: hl-proxmox
        url: xxxxxxxxxx
        target: newtab
        id: xxxxxxxx
      - title: xxxxxxxxx
        icon: hl-proxmox
        url: xxxxxxxxxxx
        target: newtab
        id: xxxxxxxx
      - title: xxxxxxxx
        icon: hl-truenas
        url: xxxxxxxxxx
        target: newtab
        id: xxxxxxx
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: true
    widgets:
    - type: proxmox-lists
      useProxy: true
      options:
        cluster_url: https://x.x.x.x:xxxx
        user_name: root@pam
        token_name: dashy
        token_uuid: xxxxxxxxxxxxxxxxxxxxxxxx
```
