### DISCUSSION TITLE
Pages not working for me.

### DISCUSSION THREAD

**Discussion by Lockie85** [Lissy93/dashy#1421] [Q&A] [answered]
Hi,

I'm trying and failing to create a dashboard which has different pages. I'd like one page for home use and one page for work use.

Within my conf.yml I have:
```
pages:
  - name: Home
    path: home.yml
  - name: Work
    path: work.yml
```

And within the same place I have my conf.yml I have files home.yml and work.yml. Which look like so:
```
pageInfo:
  title: Home
  description: My personal dashboard
  navLinks:
    - title: Work
      path: '/work'

sections:
  - name: Social Media
    items:
      - title: YouTube
        url: 'https://www.youtube.com'
        icon: fab fa-youtube
      - title: Facebook
        url: 'https://www.facebook.com'
        icon: fab fa-facebook
      - title: Twitter
        url: 'https://www.twitter.com'
        icon: fab fa-twitter

```

```
pageInfo:
  title: Work
  description: Work-related links
  navLinks:
    - title: Home
      path: '/'

sections:
  - name: Professional Tools
    items:
      - title: Microsoft
        url: 'https://www.microsoft.com'
        icon: fab fa-microsoft
      - title: Adobe
        url: 'https://www.adobe.com'
        icon: fab fa-adobe
      - title: Slack
        url: 'https://www.slack.com'
        icon: fab fa-slack

```

Before I go further, is there any obvious mistakes I've already made?

Many thanks for any help.

**Comment by Lockie85** [comment]
Starting to wonder if anyone knows how pages work. From every thread I can read, there seems to be confusion.

**Comment by Lockie85** [comment]
Really, no one knows about this? :(

**Comment by gdeans** [comment]
I haven't gotten to pages yet, but I believe you should try adding the pageInfo section ahead of the pages section.

imho, I'm thinking to design each page I want as just the conf.yml then save it to the page conf.  Then I should just need to adjust the conf.yml when I have everything worked out.  The docs are a little light on actual yml file structure and combinations.

**Comment by CrazyWolf13** [comment]
Can't spot any issue while overlooking quickly, is there any error in the log? 
Any output in the dev tools console of the browser?
Can you visitg the pages?
@Lockie85

**Comment by Niskeletor** [comment]
I completely agree. Often, the documentation can be confusing, and many threads in the forums end up going in circles without providing a clear solution. It's frustrating to reach dead ends frequently. I think it would be much easier if someone could share a base template for creating a main page (index) and two additional pages. This would provide a clearer starting point and help avoid the common pitfalls.

**Reply by CrazyWolf13** [reply]
I can look into this and update the docs.

If there is any specific part that is unclear let me know.

**Reply by Niskeletor** [reply]
Thank you for responding so quickly and taking the time to address this. I hope my previous comment didn't come across as rude; I truly value the effort you all put into this project, and I believe it's an ideal solution for many needs.

The case is that I am using Docker. According to the documentation:

"To get started, create a new .yml config file for your sub-page, placing it within /app/public. Then within your primary conf.yml, choose a name, and specify the path to the new file."

I understand that I need to enter the path inside the container at /app/public/ and create the .yml files for my pages there.

Then, in conf.yml (which is actually located at /app/user-data/conf.yml), I need to indicate their existence by adding:

```yaml
pages:
- name: Main Dashboard
  path: 'page-1.yml'
- name: Secondary Dashboard
  path: 'page-2.yml'
```

I also understand that the project needs to be rebuilt, but I have tried both through the UI and by executing the command 'yarn build start'. In both cases, it fails, and everything breaks.

I have restarted the project in many possible ways, including adding pages through the UI (which also advises that if the sub-page .yml files are in public, they should just be referenced as 'page-1.yml').

I always get errors. I've tried entering developer mode to modify the project, but it seems that the versions and libraries are quite sensitive to manage.

Here are some examples of my files:

Once again, thank you for your time and effort on this project. If anyone has managed to get this working, it would be great if you could share how you have configured the files, where you placed them, and how you 'rebuilt' the Dashy instance. Sometimes, it's difficult to explain the steps without accompanying examples.

![imagen](https://github.com/Lissy93/dashy/assets/97298802/a5d1b3dd-e91c-4ac6-badc-9d9c12f7da40)

/app/user-data/conf.yml

```yml
pageInfo:
  title: Niscode
  description: Landsraad Network
  navLinks:
    - title: GitHub
      path: https://github.com/Niskeletor
      target: newtab
    - title: Documentation
      path: https://dashy.to/docs
      target: newtab
pages:
- name: Main Dashboard
  path: 'page-1.yml'
- name: Secondary dashboard
  path: 'page-2.yml'
appConfig:
  theme: glass
  iconSize: small
  layout: auto
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: false
  statusCheckInterval: 0
  faviconApi: allesedv
  routingMode: history
  enableMultiTasking: false
  widgetsAlwaysUseProxy: false
  webSearch:
    disableWebSearch: false
    searchEngine: duckduckgo
    openingMethod: newtab
    searchBangs: {}
  enableFontAwesome: true
  enableMaterialDesignIcons: false
  hideComponents:
    hideHeading: false
    hideNav: false
    hideSearch: false
    hideSettings: false
    hideFooter: false
  auth:
    enableGuestAccess: false
    users: []
    enableOidc: false
    oidc: {}
    enableHeaderAuth: false
    headerAuth:
      userHeader: REMOTE_USER
      proxyWhitelist: []
    enableKeycloak: false
  showSplashScreen: true
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false
  disableConfigurationForNonAdmin: false
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
  enableErrorReporting: false
sections: []
```
/app/public/page-1.yml

```yml
pageInfo:
  title: Niscode 1
  description: Landsraad Network
sections:
  - name: TErminus
    widgets:
      - type: clock
        options:
          timeZone: Europe/London
          format: en-GB
          hideDate: false
  - name: Coding
    widgets:
      - type: code-stats
        options:
          username: Niscode
  - name: Github
    widgets:
      - type: github-profile-stats
        options:
          username: Niskeletor
```

**Reply by Niskeletor** [reply]
OK, I come to bring more information. In fact the experiment has been curious, as I suspected. I decided to make a fork of the repository. For this I configured the conf.yml file and included in /public/ two pages 'main.yml' and 'secondary.yml'. And the magic happened, there was no problem at all. I understand that this system works for deployment solutions through Netlify and other cloud platforms, but for those who decided to have an onpremise solution with docker this does not work, it is not possible in that way. I am investigating how to do it with docker self-hosting, if I find the way I will share it.

**Reply by CrazyWolf13** [reply, marked as answer]
@Niskeletor 
I noticed, the file should be in /app/user-data as this is the new place for config files.

And yes it is definitely possible locally, the same way as is is wich cloud providers.

----

Okay I just looked into this and it's pretty straightforward, altough I agree, the docs are a bit vague.

1. Create a additional file in the mounted user-data folder -> test-yml

2. Paste the a dashy config file, but only sections and pageInfo:
```
pageInfo:
  title: Dashboard
  description: Welcome 
  navLinks:
    - title: Documentation
      path: https://dashy.to/docs
      target: newtab
  footerText: ''
  logo: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/raspberrypi.png
sections:
  - name: RaspberryPI
    icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/raspberrypi.png
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Jellyfin
        description: ''
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/jellyfin.png
        url: http://192.168.1.111:8096
        target: newtab
        statusCheck: true
```
3. Add the following to the top of the conf.yml file:
```
pages:
- name: Test
  path: 'test.yml'
```
4. Rebuild Dashy through the GUI
5. reload the page on the browser
6. Click the Icon test: 
![image](https://github.com/Lissy93/dashy/assets/96661824/ab0de086-cc02-46ab-b7be-82c6c8203c57)
7. See a working secondary page:
![image](https://github.com/Lissy93/dashy/assets/96661824/6f9688b2-2747-4c0d-83d3-4c2989375ffe)


I'll add these steps to the docs, but I'm kinda busy lately, so I can't guarantee them to be available immediately.
