### DISCUSSION TITLE
3.0.0

### DISCUSSION THREAD

**Discussion by lissy93** [Lissy93/dashy#1537] [Releases]
Dashy 3.0 has been released!

This version includes some major changes, including:
- No more rebuilding 🎉
- Mounting a directory, not a file 😌
- Switch to Non-Root of Port 🔒
- Environmental Variables for Widget API Keys 🔒
- Other performance, stability and security updates ⚡

For a full break-down, see [#1529](https://github.com/Lissy93/dashy/discussions/1529)

> [!IMPORTANT]
> This release includes breaking changes.
> The port within the container has changed from `80` to `8080`, and the location of your config and other assets has changed from `/app/public` to `app/user-data`. You will need to update your Docker compose/run command after upgrading to this version.

<hr /><em>This discussion was created from the release <a href='https://github.com/Lissy93/dashy/releases/tag/3.0.0'>3.0.0</a>.</em>

**Comment by RafaelSchridi** [comment]
I see a 3.0.0 tag but could we also get a lissy93/dashy:3 docker tag?

**Reply by lissy93** [reply]
I can look into that, as it would be best practice to have this in place.
It would need to be implemented in this workflow file: [`docker-build-publish.yml`](https://github.com/Lissy93/dashy/blob/HEAD/.github/workflows/docker-build-publish.yml)

So just to clarify, `:3` will be updated with whatever the current `3.x.x` version is, and `:3.1` would be updated with the latest `3.1.x`. That's what you'd want, right?

**Reply by RafaelSchridi** [reply]
Yes that way your can update carefree without hitting breaking changes until you manually change it to `:4`.

I've seen massive projects also do `:3.1` like you said, but I think just `:3` would suffice honestly.

**Comment by mjlehrke** [comment]
I can't seem to get widgets working after the upgrade. So far every widget has a proxy error. For example,  HealthChecks:

> An error occurred, see the logs for more info.
>
>Proxy returned error from target server

>Stack Trace
>Request failed with status code 401

1. I have triple checked the API keys, they remain the same and are valid.
2. curl receives a correct response from HealthChecks, for instance
3. curl within the container with `docker exec` also receives a correct response from HealthChecks

None of my widgets work anymore.

Here is an example config that has the error
```yaml
---
# Page meta info, like heading, footer text and nav links
pageInfo:
  title: Dashy
  description: Welcome to your new dashboard!
  navLinks:
  - title: GitHub
    path: https://github.com/Lissy93/dashy
  - title: Documentation
    path: https://dashy.to/docs

# Optional app settings and configuration
appConfig:
  theme: colorful

# Main content - An array of sections, each containing an array of items
sections:
- name: Status
  widgets:
    - type: HealthChecks
      options:
        host: http://192.168.0.150:3002
        apiKey: 
          - 8KFsc32YOhIthCEwxESIDNU1WHhMFJ0S
```

The cors-proxy has a bad request error:
```
"code":"ERR_BAD_REQUEST","status":401
```
