### DISCUSSION TITLE
Trouble adding UptimeKuma widget

### DISCUSSION THREAD

**Discussion by MAMedici** [Lissy93/dashy#1584] [Help and Support]
This is the first time I've tried adding a widget, so pardon me for this basic question.

I've added the following to my conf.yml under `sections`:

```
  - name: Uptime Kuma
    displayData:
      sortBy: default
      rows: 2
      cols: 2
      collapsed: false
      hideForGuests: false
    widgets:
      - type: uptime-kuma
        # useproxy: true
        options: null
        apiKey: <api key generated in uptimekuma>
        url: http://docker1.<mydomain.com>:3011/metrics
```

When I refresh my dashy homepage, I get the section for Uptime Kuma but it's blank.  There's a refresh button in the page, and when I click that I get an animated "snake" in that section but no data  from Uptime Kuma is displayed.  I verified that UptimeKuma is listening on that URL and the API key is correct by doing curl -u":<api key>" docker1.<mydomain.com>:3011/metrics and data is returned.

When I do yarn validate-config I get the following errors:

```
1. /appConfig/auth/oidc must have required property 'clientId' 
2. /appConfig/auth/oidc must have required property 'endpoint' 
3. /sections/1/widgets/0/options must be object 
```

I'm not sure  what I'm doing wrong.  I'm going to try a different widget and hope I can figure out from there, but any advice would be welcome.
