### DISCUSSION TITLE
Can't get Widgets that depend on Glances to communicate, with or without CORS proxy.

### DISCUSSION THREAD

**Discussion by JohnHind** [Lissy93/dashy#1597] [Q&A]
Finally figured out status checks, then tried some Widgets: down another rabbit hole!

Basically, with this in my conf.yml:
```
    widgets:
    - type: gl-system-load
      options:
        hostname: http://localhost:61208
```
I get:
`
     GET http://localhost:61208/api/3/load net::ERR_CONNECTION_REFUSED
`
In the browser log.

With this:
```
    widgets:
    - type: gl-system-load
      useProxy: true
      options:
        hostname: http://localhost:61208
```
I get:
`
       GET http://octosnap.local/cors-proxy 500 (Internal Server Error)
`

'octosnap.local' is the external URL of the Raspberry Pi on which Dashy is running (in a Docker container). The Glances server is running on the Raspberry Pi, not in a Docker container (although I have also tried it in a Docker container with the same result). The Dashy client is running in Vivaldi browser on a Windows machine on the same local network. http://octosnap.local:61208 works fine, bringing up the Glances Web Page in the same browser.

I believe I have read all the relevant documentation for both Dashy and for Glances. I am really puzzled, because this should be a well trodden path: I do not think I am doing anything unusual! Is there something I need to do to configure the CORS proxy that I have missed?

**Comment by CrazyWolf13** [comment]
Hi yeah that nothing on you end, glances recently updated to api v4, hence why it throws an error.

I already submitted a PR which got merged yesterday, just re-pull the latest dashy image from dockerhub and it should all work.

**Reply by JohnHind** [reply]
Thanks for that, but I just updated to Dashy 3.1.0 and the only difference is the error message is now:

`
GET http://localhost:61208/api/4/load net::ERR_CONNECTION_REFUSED
`

Without 'useProxy' and exactly the same as above with 'useProxy: true'.

I'm still thinking it needs the proxy, but for some reason the proxy is not working.

**Reply by CrazyWolf13** [reply]
Could you try directly with the IP of the system instead of the domain name?

For me I needed the proxy, but try with nd without, that depends on your setup.

**Reply by JohnHind** [reply]
Thanks again. FINALLY, This worked:
```
    widgets:
    - type: gl-system-load
      useProxy: true
      options:
        hostname: http://192.168.1.233:61208
```
Where 192.168.1.233 is the translation of 'octosnap.local', the external IP of the Raspberry Pi server machine that is running both the Dashy server (in a Docker container) and the Glances server on the bare OS. It is worrying that it only works with the numeric IP as that is changeable. Could the code do a DNS lookup at some point to avoid this?

One problem I have commonly had understanding the documentation is knowing when a URL is being used from the client side and when from the server side. This tripped me up with status check URLs being different from service URLs when referencing the same server. I'm not sure I have understood it yet, because I'd expect this Glances API URL to be used by the Dashy back-end server like the status check URLs.
