### DISCUSSION TITLE
Pihole widget not retrieving data when using reverse proxied domain name

### DISCUSSION THREAD

**Discussion by bullfrog-au** [Lissy93/dashy#1624] [Help and Support]
Dashy V-3.1.1
PiHole v5.18.2
Traefik 3.0.2

So this seems to be a permissions/ authentication transmission issue.

I have Dashy, Pihole and Traefik running in containers.
The 'pi-hole-stats' widget works if I pass the IP address in the hostname
```
 - type: pi-hole-stats
      useProxy: true
      options:
        #hostname: https://pihole.domain.com/api.php
        hostname: http://192.168.1.2/admin/api.php
        apiKey: xxxxxxxxxxxxxxxxxxxxx
```
![image](https://github.com/Lissy93/dashy/assets/69968720/5f9a59e1-4712-43f9-8995-0818f6182d61)

But fails if I pass the proxied address including the API path, but without any clear error
```
    - type: pi-hole-stats
      useProxy: true
      options:
        hostname: https://pihole.domain.com/api.php
        # hostname: http://192.168.1.2/admin/api.php
        apiKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
![image](https://github.com/Lissy93/dashy/assets/69968720/eee879b3-fd09-4cb1-8148-9c40320d6dfb)
![image](https://github.com/Lissy93/dashy/assets/69968720/860c3057-7d87-4e28-b7b6-8c29e561fbc2)

If there are any networking gurus out there who know where the block is happening it would be appreciated!
Thanks
