### DISCUSSION TITLE
500 Error in production mode w/ ProxMox widget after copying CA Cert

### DISCUSSION THREAD

**Discussion by fuzzball03** [Lissy93/dashy#1734] [Help and Support]
Like the title states I've copied over the CA certificate and exported the appropriate variables but I'm getting an error 500 with the ProxMox lists widget. I've tried enabling the `UseProxy` with no change.

Have I missed something obvious based on what can be seen below? I appreciate any help in advanced.

See below for snippets of the `conf.yml` file, the result of the `env` command within docker, and the resulting json error from chrome.
note: Pi-hole stats are polling without issue

Thank you

### Relevant Snippets
**conf.yml**
```
    widgets:
      - type: pi-hole-stats
        options:
          hostname: http://pi-hole/
          apiKey: VUE_APP_PIEAPI
          useProxy: true
      - type: proxmox-lists
        useProxy: true
        options:
          cluster_url: https://10.0.0.8:8006
          user_name: VUE_API_PVEUSER
          token_name: dashy
          token_uuid: VUE_API_PVEUUID
 ```
**docker exec Dashy env**
```
NODE_EXTRA_CA_CERTS=/app/user-data/pve-ssl.pem
NODE_VERSION=20.11.1
HOSTNAME=****
VUE_API_PVEUSER=root@pam
YARN_VERSION=1.22.19
SHLVL=1
PORT=8080
HOME=/root
OLDPWD=/app
VUE_APP_PIEAPI=****
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DIRECTORY=/app
IS_DOCKER=true
PWD=/app/user-data
VUE_API_PVEUUID=****
NODE_ENV=production
```
**error 500 JSON object**
```
{
    "message": "Request failed with status code 500",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 500\n    at J (http://10.0.0.21:10/js/chunk-vendors.2a3fe5ac.js:68:18328)\n    at XMLHttpRequest.u (http://10.0.0.21:10/js/chunk-vendors.2a3fe5ac.js:68:23215)\n    at Bt.request (http://10.0.0.21:10/js/chunk-vendors.2a3fe5ac.js:68:31178)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http",
            "fetch"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 50000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Target-URL": "https://10.0.0.8:8006/api2/json/nodes",
            "CustomHeaders": "{\"Authorization\":\"PVEAPIToken=VUE_API_PVEUSER!dashy=VUE_API_PVEUUID\"}"
        },
        "method": "get",
        "url": "http://10.0.0.21:10/cors-proxy",
        "data": "{}"
    },
    "code": "ERR_BAD_RESPONSE",
    "status": 500
}
```
