### DISCUSSION TITLE
Some setup issues

### DISCUSSION THREAD

**Discussion by ZzenlD** [Lissy93/dashy#1736] [Help and Support]
Hello everyone,
I got Dashy running with the following docker-compose.yml conf.yml:
```yaml
# docker-compose.yml
version: "3.9"
services:
  dashy:
    image: docker.io/lissy93/dashy:3.0.1
    hostname: dashy
    read_only: true
    tmpfs:
      - /app
    security_opt:
      - no-new-privileges
    volumes:
      - ./dashy/config:/app/user-data:z,ro
    labels:
      - io.containers.autoupdate=registry
    networks:
      - proxy
    environment:
      - VUE_APP_STARTING_VIEW=minimal
    restart: always

networks:
  proxy:
    external:
      name: proxy
```

```yaml
# conf.yml
pageInfo:
  title: My Dashboard

appConfig:
  defaultOpeningMethod: modal
  auth:
    enableOidc: true
    oidc:
      clientId: dashy
      endpoint: "https://authelia.my.domain/.well-known/openid-configuration"
  hideComponents:
    hideHeading: true
    hideNav: true
    hideSettings: true
    hideFooter: true
  enableMultiTasking: true
  disableConfiguration: true

sections:
  - [...]
```

A few things don't quite work yet, and I'm not sure if I'm doing it wrong or if the functions are (so far) not given at all.

1. I have configured Authelia as specified in the configuration file, but the redirect does not work, no matter what i try
2. Although I have deactivated the footer, a border is still displayed at the bottom of the Workplace view, how do I get rid of it?
3. Every time I restart the container, the application is rebuilt, can this be avoided/can the application only be built inital?
4. Is it possible to show a search in the Workplace view to quickly find configured services and open them in Workplace mode?
5. Is it possible to dynamically display all open pages “at the top” in the Workplace view? This would make it much easier to work with multiple pages from different sections.
6. Can the link to the default view be deactivated in the Workplace view? I would like to use only the Minimal and Workplace views

Thanks for your help :)
