### DISCUSSION TITLE
Unable to get keycloak authentification

### DISCUSSION THREAD

**Discussion by sbrutin** [Lissy93/dashy#1842] [Help and Support]
Sorry to bother you with my problems but I cannot configure dashy with keycloak.

I get this error message in the page :
"It looks like something's gone wrong..."
and this one on console log :
"Failed to authenticate with Keycloak 

This is likely not an issue with Dashy, but rather your configuration.
If you think it is a bug, please open a ticket on GitHub: https://git.io/JukXk"

On network traces, It seems fine, I get a token from keycloak :

![image](https://github.com/user-attachments/assets/e7fe219e-47dc-4aef-8512-76e77fad598e)

here my dashy config file : 
```
  auth:
    enableGuestAccess: false
    users: []
    enableOidc: false
    oidc: {}
    enableHeaderAuth: false
    headerAuth:
      userHeader: REMOTE_USER
      proxyWhitelist: []
    enableKeycloak: true
    keycloak:
      serverUrl: https://secure.xxx.xx
      realm: xxxxxxxx
      clientId: dashy-client
      legacySupport: false
```

and my keycloak configuration :  
![image](https://github.com/user-attachments/assets/ceee3cd7-264f-4d9e-8ff3-0baac92b3d2c)
![image](https://github.com/user-attachments/assets/657cf4b4-1053-42e4-ac70-bdf3ef61f04f)

What did I do wrong?
Thanks
