### DISCUSSION TITLE
image-icons with BASE_URL set don't seem to work.

### DISCUSSION THREAD

**Discussion by dkowis** [Lissy93/dashy#274] [Help and Support] [answered]
I've set the Environment Variable BASE_URL in my docker-compose, and all the compiled assets are working fine, however image-icons are not.

```yaml
     - title: Grafana
       url: https://example.com/grafana/
       icon: grafana.png
```

That icon is in the volume specified here:

```yaml
services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: dashy_dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - ./config.yml:/app/public/conf.yml
      - ./icons:/app/public/item-icons
    # Set any environmental variables
    environment:
      - NODE_ENV=production
      - BASE_URL=/dashy
```

But unfortunately:
![image](https://user-images.githubusercontent.com/28048/136728918-d23c67ee-9419-4d14-8c1e-5aec604ad116.png)

All the image-icons specified are not honoring that BASE_URL. Did I find a bug? Did I configure something wrong?
