### DISCUSSION TITLE
Dashy with docker compose - unable to do "clean" recreate

### DISCUSSION THREAD

**Discussion by Wri84** [Lissy93/dashy#368] [Help and Support] [answered]
Hi,

while searching for a dashboard for my selfhosted setup I came across dashy and immediately replaced my previous organizr deployment with it.

I use docker compose for my stack and run everything on a RPi4. The first install went fine and I was able to customize dashy a bit. However, I since chose to start from scratch but I somehow can't do so. Normally, if I remove the docker volume with persistent data, everything is back to square one when recreating the container. But dashy somehow doesn't work that way. 

When I first deployed dashy with docker compose, it came up with an example config containing a getting started section. I'm unable to return to this state. Additionally, the "adventure" theme is now broken as the correct fonts are no longer loaded. When switching to other themes, everything looks fine, but "adventure" now has Times New Roman as its font.

I just want to restart from scratch. Where else can I look to reset my installation?

Following is my compose extract

```
# dashy - Unified Frontend
  dashy:
    container_name: dashy
    image: lissy93/dashy:arm64v8
    restart: unless-stopped
    networks:
      - t2_proxy
    dns:
      - 127.0.0.1
      - 1.1.1.1
    security_opt:
      - no-new-privileges:true
    ports:
      - "$DASHY_PORT:80"
    volumes:
      - $DOCKERDIR/dashy:/app/public
      - $DOCKERDIR/dashy/item-icons:/app/public/item-icons
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - UID=$PUID
      - GID=$PGID
      - TZ=$TZ
      - NODE_ENV=production
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
```
