### DISCUSSION TITLE
widgets in docker

### DISCUSSION THREAD

**Discussion by henkiewie** [Lissy93/dashy#400] [Help and Support] [answered]
Hi,
I'm using dashy with the docker compose example.
It's working nicely, but widgets like system-info an weather-forecast are giving me errors.
Should they work in docker?
There is no info in the log.
System-info has no options.
Weather-forecast options;
![Screenshot 2022-01-02 at 13 02 41](https://user-images.githubusercontent.com/74558874/147875218-43fe6ae9-a608-46ff-a2fc-2ce48fb8600b.png)
[Untitled.txt](https://github.com/Lissy93/dashy/files/7799037/Untitled.txt)

          city: Amsterdam,NL
          numDays: 6
          apiKey: myapaikey
Time seems to be working OK

**Comment by KierenConnell** [comment, marked as answer]
For the weather-forecast, if you open Inspect Element on your dashboard page, you should see an error reported in the console.

**Reply by henkiewie** [reply]
If you mean the browser option to inspect an element. It states div.widget.error.  can get to to console in docker, but don't know where to look for the log file it is referring to.

**Reply by KierenConnell** [reply]
Is there a reference to the api call for the weather-forecast widget in the inspect console?

**Reply by henkiewie** [reply]
I tried the simpeler weather api that is working OK. Must be something with the parameters.

**Reply by KierenConnell** [reply]
Weather-forecast requires a paid subscription for OpenWeather. But the simple daily widget works fine on the free api key

**Reply by henkiewie** [reply]
Ahh I thought it would be something like that. I tried to lower the number of days to three. But that did not help. Maybe they should use that free one call API for the forecast. Thanks for the help.
![Screenshot 2022-01-02 at 15 33 15](https://user-images.githubusercontent.com/74558874/147879119-01c90871-fc1b-401e-b629-309ee274558a.png)

**Reply by lissy93** [reply]
If you're a student or graduate, you can get a free API key for the premium weather forecast widget, here: https://home.openweathermap.org/students There isn't any verification, but you can only use for personal use.

**Reply by lissy93** [reply]
Alternatively, you could use the [Open Weather Map Widgets](https://openweathermap.org/widgets-constructor) with Dashy's [Embed Widget](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#html-embedded-widget), something like this:

![Widget](https://i.ibb.co/2ccpHHk/embed-widget-3.png)

```yaml
  widgets:
  - type: embed
    options:
      html: <div id="openweathermap-widget-11"></div>
      scriptSrc: https://openweathermap.org/themes/openweathermap/assets/vendor/owm/js/d3.min.js
      script: |
        window.myWidgetParam ? window.myWidgetParam : window.myWidgetParam = [];
        window.myWidgetParam.push({id: 11,cityid: '2643743',appid: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
        ,units: 'metric',containerid: 'openweathermap-widget-11',  });
        (function() {var script = document.createElement('script');script.async = true; script.charset = "utf-8";
        script.src = "https://openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js";
        var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(script, s);  })();
```

Although it's not the neatest solution, and OWM's widgets are slow and don't seem to work on all screen sizes. Maybe there's another weather service with a better widget plugin.

---

Update, if you want to embed a weather card, looks like [weatherwidget.io](https://weatherwidget.io/) has much nicer widgets than OWM.

![Example](https://i.ibb.co/kSjY5Dc/embed-widget-4.png)

```yaml
- type: embed
    options:
      html: |
        <a class="weatherwidget-io" href="https://forecast7.com/en/51d51n0d13/london/"
        data-label_1="LONDON" data-label_2="WEATHER" data-theme="original" ></a>
      script: |
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id))
        {js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';
        fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
```
