### DISCUSSION TITLE
Widgets and Items?

### DISCUSSION THREAD

**Discussion by yidhoe** [Lissy93/dashy#434] [Q&A] [answered]
Hey all,

Probably something simple I am missing, but I can only get either Widgets to work or the normal Icon Items I cannot get both to work together, however I can see there is examples of this working so not quite sure what I am missing.

Could someone please provide a sample config with any random item and say just a clock widget so I can see what I am missing.

Thanks

**Comment by lissy93** [comment, marked as answer]
Heya @yidhoe 

Not sure I fully understand the question, do you mean how to display both items and widgets in the same section?

If so, you can just put them together, like this:

```yaml
sections:
- name: BitCoin Node
  icon: fab fa-bitcoin
  items:
  - title: Local BitCoin Node
    icon: ':lock:'
    url: https://bitcoin-node.local/ui
  ...
  widgets:
  - type: crypto-price-chart
    options:
      asset: bitcoin
      currency: GBP
      numDays: 7
- name: Another Section
  ...
```

**Reply by yidhoe** [reply]
Hi Lissy,

Oh I really need to change my username lol just seen it, anyway thanks for the prompt response, don't be surprised if my name randomly changes shortly either lol.

Anyway, I have used the built in editor to add various buttons etc. but if I add any kind of widet to the page it fails to load and usually crashes the container, I just tried adding the 'dots' you showed above wondering if they were closing statements lol but no luck.

I have tried putting the widgets before and after the existing items too but no luck.

Either load fine on their own but the whole thing falls down as soon as I try to add both types of items.

So for example this is the last setion of my code with your code appended on the bottom, previously I was trying to add a basic clock as a starting point.

```
  - name: Statistics
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: NetData
        description: Network Data for Domain.xyz
        icon: NetData.png
        url: https://Domain.xyz
        target: modal
        statusCheck: true
        id: 0_1067_netdata
      - title: NetDataCloud
        description: Network Data for VPN Server
        icon: NetData.png
        url: https://Domain.xyx
        target: modal
        statusCheck: true
        id: 1_1067_netdatacloud

  widgets:
  - type: crypto-price-chart
    options:
      asset: bitcoin
      currency: GBP
      numDays: 7
```

Thanks

**Reply by yidhoe** [reply]
In fact I just stripped out most of the items so I can share the whole code, now if I remove either the widget or the shortcuts it works but otherwise this fails is the whole page...

```
appConfig:
  theme: vaporware
  layout: vertical
  iconSize: large
  language: en
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: true
  statusCheckInterval: 30
  faviconApi: local
  routingMode: history
  enableMultiTasking: false
  webSearch:
    disableWebSearch: false
    searchEngine: google
    openingMethod: newtab
    searchBangs: {}
  enableFontAwesome: true
  cssThemes: []
  customColors: {}
  externalStyleSheet: []
  hideComponents:
    hideHeading: false
    hideNav: false
    hideSearch: false
    hideSettings: false
    hideFooter: true
  auth:
    enableGuestAccess: false
    users: []
    enableKeycloak: false
    keycloak: {}
  showSplashScreen: false
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
  enableErrorReporting: false
pageInfo:
  title: Domain.xyz
  description: Welcome to your world...
  navLinks:
    - title: GitHub
      path: https://github.com/Lissy93/dashy
    - title: Documentation
      path: https://dashy.to/docs
  footerText: ''
sections:
  - name: Statistics
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: NetData
        description: Network Data for Domain.xyz
        icon: NetData.png
        url: https://NetData.Domain.xyz
        target: modal
        statusCheck: true
        id: 0_1067_netdata
      - title: NetDataCloud
        description: Network Data for VPN Server
        icon: NetData.png
        url: https://NetDataCloud.Domain.xyz
        target: modal
        statusCheck: true
        id: 1_1067_netdatacloud

  widgets:
  - type: crypto-price-chart
    options:
      asset: bitcoin
      currency: GBP
      numDays: 7
```

**Reply by lissy93** [reply]
Oops sorry, the dots were just meant to symbolize _more stuff_. If the container crashes, than that means there's a YAML syntax error in your config. Try pasting your config into [YAMLchecker.com](https://yamlchecker.com/), and it should show you exactly where the error is.

In your snippet, it's just an indentation mistake, the `widgets` part needs to be inside the current section. Here's the fixed working version:

```yaml
sections:
  - name: Statistics
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
    - title: NetData
      description: Network Data for Domain.xyz
      icon: NetData.png
      url: https://Domain.xyz
      target: modal
      statusCheck: true
      id: 0_1067_netdata
    - title: NetDataCloud
      description: Network Data for VPN Server
      icon: NetData.png
      url: https://Domain.xyx
      target: modal
      statusCheck: true
      id: 1_1067_netdatacloud
    widgets:
    - type: crypto-price-chart
      options:
        asset: bitcoin
        currency: GBP
        numDays: 7
```

Easy mistake to make, YAML is awesome compared to JSON, because you don't have to deal with hundreds of opening and closing braces, but it can take a while to get used to, since indentation must be 100% correct.

Hope that helps :)
