### DISCUSSION TITLE
Better docker folder mapping...

### DISCUSSION THREAD

**Discussion by stuu3k** [Lissy93/dashy#441] [Ideas]
Biggest problem I have had with Dashy was getting it started on Docker as I did not realise I had to create the .conf file with contents to get it to boot.

I feel this could be imrpoved by deploying  a default file, personally I would go a few better and remove the file mapping and replace it with 1x folder please "/path/Dashy : /config" or something like that and on first run auto deploy a blank conf file so said folder as well as creating 2 more subfolders (Images + Logs),

This way it's easy for people to work out where to add images locally for a start and also easier to get up and running.

Finally as an added bonus we would have easy access and management of logs.

Oh also and I am not sure if this is just me but in Portainer you can't seem to map a file, only folders, you try to map a file and it creates a folder of that name dot included instead so it would by-pass that little problem too.

Either way thanks for the great work so far!!!

**Comment by MattW42** [comment]
Totally agree with this comment. 
The app needs to create a default .conf file if it doesn't exist.

I used the following steps to get this working in Portainer.

1. Create the '`dashy_data`' volume in Portainer

2. Create conf.yml and populate with default config
```
#  SSH to Pi - logon to host (in this case it was a RaspberryPi running docker)
      cd /var/lib/
#  Create conf.yml
      sudo touch docker/volumes/dashy_data/_data/conf.yml
#  Edit conf.yml - requires some basic config to start with
      sudo nano docker/volumes/dashy_data/_data/conf.yml

#  Full path to docker data - requires sudo otherwise access denied.
#    /var/lib/docker/volumes/dashy_data/_data/conf.yml

#  get full path name for stack info with 
      pwd

#  get uid and gid for stack info with
       id
```

3. Create a new stack (in Portainer) with the following yml config:

```
---
version: "3.8"
volumes:
  dashy_data:

services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
      - dashy_data:/app/public
      
      # previous method for mapping to a file
      #- /var/lib/docker/volumes/dashy_data/_data/conf.yml:/app/public/conf.yml
    
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
```
4. Deploy stack in Portainer  ( Note: Portainer now shows the volume in use - under the 'Volumes' menu )


All of step 2 could be removed if the app created its own default config.


This config uses a named volume (dashy_data - which is already created/existing in Portainer)
Once Dashy container is running, Portainer then shows the volume as being in use.

Docker documentation:
https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
