### DISCUSSION TITLE
Run your Docker Container with Network type HOST.

### DISCUSSION THREAD

**Discussion by stuu3k** [Lissy93/dashy#445] [Hot Tips]
Hi all,

I have done lots of testing with this over the last few days and the only way I can get Dashy to ping all destinations is when I have it running using HOST network instead of Bridge.

*You DO NOT need to run in Privilaged mode when doing it this way!*

In my case I have it installed on a Synology NAS which has several other containers running on it, including Critically a Pi-Hole container running in HOST mode with Elevated privliges, initially I could ping only devices on my LAN everything else would fail, after adjusting my NAS firewall rules and switching the ping check to use the docker container IP's (172.17.0.0/16 range) I could get it to check everything except for the Pi-Hole running in HOST mode.

Chaning my container to run in HOST mode resolved this problem and now I can successfully check 10.0.0.0/24, 172.17.0.0/16 and Critically the Pi-Hole container running in host mode.

P.S. I also highly recommend setting up Portainer which assist massively in discovering things like container IPs which you can see all in one view! :)

Another great thing about Portainer is it will let you recreate your containers whilst changing things like the Network Type which is something the Synology GUI will not let you do!

Hope this helps!

**Comment by stuu3k** [comment]
Further to this I have since notice that sometimes the Docker IP's change after reboot which can cause a probem if you use 172.17.0.10 for example and it switches with another container after a reboot.

However if you instead actually use 172.17.0.1 for querying all containers using their External Port instead of Internal it will route the traffic for you, so any container monitoring I suggests always using 0.1 and External Port numbers.

Tested on Windows Docker Desktop and Docker on Synology works on both! :)

Thanks

**Comment by JohnHind** [comment]
Thanks for this. You gave me the clues to get me going, but my eventual results were a little different. I had set all of my services except (of course) Portainer itself up using Portainer Stacks with Docker Compose scripts. This had resulted in most of them being in their own separate virtual networks (different second digits in the IP). I created a new Bridge network and moved them all, including Portainer itself, and Dashy, into that network so they all have the same first two digits in their IP. Now as you suggest, I use the gateway for that network with the port number of the service as the Status Check URL.

So if the Service URL is: http://host.local:2180 the Status check URL would be http://172.18.0.1:2180 (my new network was on 172.18.x.x rather than your 172.17.x.x). This worked in all cases except one which required a routing. Service URL was http://host.local:3000/wetty and the Status check URL needed to be http://172.18.0.1:3000/wetty.

I did not find that the network needed to be type Host, Bridge, the default, was fine. I also found it was sometimes necessary to restart the Dashy container (have a coffee while it restarts!) for changes to take effect, sometimes not.

This is the Docker Compose script I use for Dashy:

```
version: "3.8"
services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
      - /home/pi/dashy/conf.yml:/app/public/conf.yml
      - /home/pi/dashy/icons:/app/public/item-icons/icons
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    networks:
      network1:
        aliases:
          - dashy
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
  network1:
    name: octobridge
    external: true
```
Note the two 'networks:' sections: the name (in this case 'octobridge') needs to be the same for all the services.

**Comment by TornaxO7** [comment]
I've got the same problem here and setting `--network=HOST` also solved my status check issue. However: Dashy is now listening on port `8080` but I'd like to give it another port. Does anyone know how to fix this?

**Comment by LokeYourC3PH** [comment]
Just adding my two cents to this conversation:
As I found it somewhat annoying having either to transition things from `host` to my `docker_one` bridge on which most things run (some few like Portainer, HomeAssistant, etc. do not), or having to transition Dashy from my `bridge` to `host` instead, I ended up going with a solution that I find the best personally, which can leave Dashy inside of the `bridge` environment, **_AND_** also let Dashy access things that are outside of the `bridge`, such as things on `host` or even entirely different machines/networks.

My solution? A miniature, low resource NGINX container acting as a proxy.

I solved it with this docker compose:
```
services:
  host-proxy:
    image: nginx:alpine
    container_name: NGINX-Alpine
    restart: unless-stopped
    mem_limit: 128m
    cpu_shares: 128
    volumes:
      - /volume1/docker/nginx-alpine/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - docker_one
#    ports:
#      - "9080:80"

networks:
  docker_one:
    external: true
```
, where the `nginx.conf` file looks like this:
```
server {
    listen 80;

    location /portainer/ {
        proxy_pass http://192.168.2.113:32007/;
        proxy_set_header Host $host;
    }

    location /ha/ {
        proxy_pass http://192.168.2.113:8123/;
        proxy_set_header Host $host;
    }

    location /luci/ {
        proxy_pass https://192.168.2.1/luci-static/argon/img/argon.svg;
        proxy_ssl_verify off;
        proxy_ssl_verify_depth 1;
        proxy_set_header Host $host;
    }
}
```
This allows me to forward Portainer on port 32007, HomeAssistant on 8123, and OpenWRT without it being blocked by CSRF protections (accessing a static resource) directly to Dashy. All you have to do is to then set in Dashy the "`Status Check URL`" field to the name of the container, looking like this (for example, for Portainer) according to the `location` field in the `nginx.conf`: `http://NGINX-Alpine/portainer/`, disable HTTPS (I do at least as it is all internally hosted and I don't use HTTPS internally), and that's it. Status checks now return successfully even from outside of the Docker bridge.
