### DISCUSSION TITLE
Is the docker image published?

### DISCUSSION THREAD

**Discussion by turnrye** [Lissy93/dashy#45] [Help and Support] [answered]
Hey @Lissy93 ! Just curious if this image has been published to any registry? I’d be interested to use Dashy, but in my use case I’ll need to be pulling the image. While I can certainly publish it, I’d hate to build the automation around that (or plant a flag in a registry) if this is already done or on your radar.

Thanks for the awesome project!

**Comment by lissy93** [comment, marked as answer]
Hi @turnrye - thanks for raising this, and sorry for the delay in replying. 

I don't have much experience in publishing to Docker Hub, so it's taken longer to figure things out. But I will update this issue when it's up and running :)

In the meantime, here is the current published Docker image: https://hub.docker.com/r/lissy93/dashy

**Comment by shad-lp** [comment]
Nice, I can give it a try easily now.

**Comment by JonasAlfredsson** [comment]
Hi Lissy93,

I just happened to stumble upon this repo and read this issue, so I thought I could mention that I experimented with using GitHub Action to build and publish my image to DockerHub just very recently. The process, and result, can be read in here if you fee like it: https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/28#issuecomment-810954953 Hope it can help you in some way :)

**Comment by turnrye** [comment]
Thanks @Lissy93 ! Quick snippet in case someone in the future wants a cut-and-paste of running this in K8S now that the docker image is published:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  namespace: default
  labels:
    app.kubernetes.io/name: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dashy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dashy
    spec:
      containers:
      - name: dashy
        image: lissy93/dashy:latest
        volumeMounts:
        - name: config
          mountPath: "/app/public/conf.yml"
          subPath: "conf.yml"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: dashy-config
---
apiVersion: v1
kind: Service
metadata:
  name: dashy
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: dashy
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashy
  namespace: default
spec:
  rules:
  - host: dashy.k8s.leb.memhamwan.net
    http:
      paths:
      - backend:
          service:
            name: dashy
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
data:
  # file-like keys
  conf.yml: |
    ---
    pageInfo:
      title: K8S Dashy
      navLinks:
      - title: Home
        path: /
      - title: About
        path: /about
      - title: Source Code
        path: https://github.com/Lissy93/dashy
    appConfig:
      theme: colorful
      fontAwesomeKey: 0821c65656
    sections:
    - name: Getting Started
      items:
      - title: Source
        description: Source code and documentation on GitHub
        icon: fab fa-github
        url: https://github.com/Lissy93/dashy
      - title: Issues
        description: View currently open issues, or raise a new one
        icon: fas fa-bug
        url: https://github.com/Lissy93/dashy/issues
      - title: Demo 1
        description: 'Live Demo #1'
        icon: far fa-rocket
        url: https://dashy-demo-1.netlify.app 
      - title: Demo 2
        description: 'Live Demo #2'
        icon: fad fa-planet-ringed
        url: https://dashy-demo-2.netlify.app 
      
```

I'll probably separately make an actual helm chart for this and contribute it to https://github.com/k8s-at-home/charts. Thanks again @Lissy93 !
