### DISCUSSION TITLE
Having trouble with latetst docker-build

### DISCUSSION THREAD

**Discussion by kimpenhaus** [Lissy93/dashy#498] [Help and Support]
Hi @Lissy93,

I am running Dashy with the latest docker build and havong trouble as it is not starting due to permission denied while starting node server and listening on port 80. Strange thing is - it was running smoothly until the latest update - without any changes on my side. I am using watchtowrrr for auto-updates on docker:latest

![grafik](https://user-images.githubusercontent.com/575109/154834718-7ecb14d8-2118-4dfe-8503-1bd4d6abaed4.png)

Not sure if there were user changes inside the docker itself which are causing the probems now?

![grafik](https://user-images.githubusercontent.com/575109/154834759-aad8da34-886f-4c18-9955-74e1a0cb59b6.png)

Any help is appreciated - thanks!

**Comment by kimpenhaus** [comment]
Ah - just saw it's related to commit https://github.com/Lissy93/dashy/commit/5aff97a09ee4ac7d5232f304604caa413dec412c and issue #340

Think I need to set the appropriate user and group.

Sorry for opening this discussion without searching first!

**Reply by lennvilardi** [reply]
not working for me UID and GID are correctly set but still got permission problem
[https://github.com/Lissy93/dashy/issues/499]

**Reply by kimpenhaus** [reply]
ya - I was havin UID and GID setup before as well - double checked all file permissions also...

![grafik](https://user-images.githubusercontent.com/575109/154839642-006e953a-76be-48a4-81cc-57908aed305f.png)

**Comment by lissy93** [comment]
So there was a recent change in #495 where @Singebob fixed #340 to allow the container to be run by an unprivileged user.

For now I've reverted this in #501, so it should be working again, while I look for the solution to apply to #502.

Sorry about that, my fault

**Reply by kimpenhaus** [reply]
I am not a Node.js pro but I think the issue is with listening to port 80 (at least from what I've [read](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/security/non-root-user.md#one-paragraph-explainer)) as that is a privileged port. Have it to run as non-root requires a different port (eg 3000 as in the example)

**Reply by kimpenhaus** [reply]
If you could push a docker version (maybe different tag) from #501 I could give it a try with a different port from env

**Reply by lissy93** [reply]
I thought this sounded right, as port 80 does indeed require sudo. But after changing it to 8080 I'm still getting `EACCES: permission denied, rmdir '/app/dist'`. Maybe I just need to chmod the directories correctly or something
Have pushed a temporary Docker image to the tag `:singebob-test-1`, if anyone has any other ideas

**Reply by Singebob** [reply]
With this docker-compose: 
```yaml
version: "3.8"
services:
  dashy:
    container_name: Dashy
    image: lissy93/dashy:singebob-test-1
    volumes:
      - /tmp/dashy/conf.yml:/app/public/conf.yml
      # - /path/to/item-icons:/app/public/item-icons
    ports:
      - 4000:8080

    # Set any environmental variables
    environment:
      - NODE_ENV=production

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
```
I don't have any problems, but if I use `node` as user ( with this docker-compose ):

```yaml
version: "3.8"
services:
  dashy:
    container_name: Dashy
    image: lissy93/dashy:singebob-test-1
    user: "node"  # or "1000:1000"
    volumes:
      - /tmp/dashy/conf.yml:/app/public/conf.yml
      # - /path/to/item-icons:/app/public/item-icons
    ports:
      - 4000:8080

    # Set any environmental variables
    environment:
      - NODE_ENV=production

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
```
I have the same error as you @Lissy93.
If you want to use a `node` user in docker, we can change a dockerfile to use the `node` user instead of a user i have created. 
So you have to delete a command who create the `docker` user and change the env USER with `node` like this:

```dockerfile
FROM node:16.13.2-alpine AS BUILD_IMAGE

# Set the platform to build image for
ARG TARGETPLATFORM
ENV TARGETPLATFORM=${TARGETPLATFORM:-linux/amd64}

# Install additional tools needed if on arm64 / armv7
RUN \
  case "${TARGETPLATFORM}" in \
  'linux/arm64') apk add --no-cache python3 make g++ ;; \
  'linux/arm/v7') apk add --no-cache python3 make g++ ;; \
  esac

# Create and set the working directory
WORKDIR /app

# Install app dependencies
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --network-timeout 1000000

# Copy over all project files and folders to the working directory
COPY . ./

# Build initial app for production
RUN yarn build

# Production stage
FROM node:16.13.2-alpine

# Define some ENV Vars
ENV PORT=8080 \
  DIRECTORY=/app \
  IS_DOCKER=true \
  USER=node

# Install tini for initialization and tzdata for setting timezone
RUN apk add --no-cache tzdata tini 

USER ${USER}

# Create and set the working directory
WORKDIR ${DIRECTORY}

# Copy built application from build phase
COPY --from=BUILD_IMAGE --chown=${USER}:${USER} /app ./

# Finally, run start command to serve up the built application
ENTRYPOINT [ "/sbin/tini", "--" ]
CMD [ "yarn", "build-and-start" ]

# Expose the port
EXPOSE ${PORT}

# Run simple healthchecks every 5 mins, to check that everythings still great
HEALTHCHECK --interval=5m --timeout=2s --start-period=30s CMD yarn health-check
```
