### DISCUSSION TITLE
Hiding settings based on authentication

### DISCUSSION THREAD

**Discussion by lgwapnitsky** [Lissy93/dashy#519] [Help and Support] [answered]
All right plan on using a keycloak to provide authentication to dashy. Is it possible to hide the configuration options based on your login permissions?

**Comment by lissy93** [comment]
Yes, it is. 
AFK at the moment, but see the docs, under authentication

**Comment by lissy93** [comment, marked as answer]
Yes, groups and roles are supported. This is outlined here, in the [Authentication Docs](https://github.com/Lissy93/dashy/blob/master/docs/authentication.md#4-add-groups-and-roles-optional). This feature was contributed by leocov-dev in #397

**Reply by schmug** [reply]
Is this only for Sections, or is it possible to hide config/save options behind keycloak roles/groups as well?

**Reply by lissy93** [reply]
Yes, see [Authentication Docs --> Permissions](https://github.com/Lissy93/dashy/blob/master/docs/authentication.md#permissions)
It's `appConfig.disableConfiguration: true`

**Reply by schmug** [reply]
I think I'm being dense, I can't figure out how to `appconfig.disableConfiguration: true` and use keycloak for auth.

How do I set `type: admin` in keycloak for dashy to recognize it?

in this example config I have `role1` in keycloak attached to my user. I've tried being keycloak group and role `admin`, and keycloak attribute `type: admin`.

``` 
appConfig:
---
  auth:
    enableGuestAccess: true
    users: []
    enableKeycloak: true
    keycloak:
      serverUrl: keycloak.url
      realm: Dashy
      clientId: clientid
  showSplashScreen: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: true
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
  enableErrorReporting: false
pageInfo:
---
sections:
  - name: section1
    displayData:
      showForKeycloakUsers:
        roles:
          - role1
---
    items:
```

**Reply by schmug** [reply]
the docs show the example when using built-in auth only from what I could find
```
appConfig:
  auth:
    users:
    - user: alicia
      hash: 4D1E58C90B3B94BCAD9848ECCACD6D2A8C9FBC5CA913304BBA5CDEAB36FEEFA3
      type: admin
    - user: bob
      hash: 5E884898DA28047151D0E56F8DC6292773603D0D6AABBDD62A11EF721D1542D8
```      
I don't pretend to know what I'm doing, but it seems like only `preventWriteToDisk` checks for admin.
https://github.com/Lissy93/dashy/blob/05f5d71801a765ab29816b5734342b9c9cd78e9d/src/store.js#L83-L96

and I can't find where keycloak users/groups/roles can have a type:
https://github.com/Lissy93/dashy/blob/c2559bc7310d42550f49115a8adc7b103af8fd19/src/utils/KeycloakAuth.js#L63-L69
