### DISCUSSION TITLE
For the life of me, I can't get this custom CSS to work.

### DISCUSSION THREAD

**Discussion by shimizurei** [Lissy93/dashy#588] [Help and Support]
I created issue #560 after playing around and noticing that my CSS activated when I added `text/css`. I thought the issue would be resolved. I STILL cannot get my CSS file working. It is loading, it is linked to, but it is not used. I have no idea what else to do. I'm just gonna throw my code here and hopefully someone will know what's happening. I've also tested with PWD to no avail.

### docker-compose.yml
```yml
version: '3.8'
services:
  dashy:
    image: ghcr.io/lissy93/dashy:latest
    container_name: Dashy
    volumes:
      - /dashy/dashyconfig.yml:/app/public/conf.yml
      - /dashy/assets/dashytweaks.css:/app/public/assets/dashytweaks.css
    ports:
      - 4949:80
    environment:
      - UID=1000
      - GID=1000
      - TZ=America/New_York
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
```

### assets/dashytweaks.css
```css
div#dashy div.home {
  background-attachment: fixed !important;
}

.collapsable label.lbl-toggle {
  color: #dad7d2 !important;
}

footer {
  margin: 0 !important;
  padding: 0.8em 0 !important;
  width: 100% !important
}
```

### dashyconfig.yml
```yml
appConfig:
  layout: 'auto'
  iconSize: 'medium'
  theme: 'thebe'
  defaultOpeningMethod: 'newtab'
  backgroundImg: 'https://i.imgur.com/tfgh9Sv.png'
  externalStyleSheet: ['/assets/dashytweaks.css']
  statusCheck: true
  enableErrorReporting: true
  disableContextMenu: true
  webSearch:
    searchEngine: "qwant"
    searchBangs:
      "/r": "reddit"
      "/wk": "wikipedia"
      "/so": "stackoverflow"
      "/git": "github"
      "/s": "google"
      "/az": "https://www.amazon.com/s?k="
      "/j": "https://jisho.org/search/"
      "/ud": "http://www.urbandictionary.com/define.php?term="
pageInfo:
  title: DASH!!
  navLinks:
    - title: Home
      path: /
    - title: Dashy Docs
      path: https://dashy.to/docs/
  footerText: "🔥 Set your heart ablaze / 心を燃やせ 🔥"
sections:
  - name: Image
    displayData:
      collapsed: true
      cutToHeight: true
    widgets:
    - type: image
      options:
        imagePath: https://64.media.tumblr.com/54a945edd2641e20859d6f6537cd7423/tumblr_pwa4bogz4N1qze3hdo2_r1_500.gifv
  - name: Media Streaming
    displayData:
      collapsed: true
      cutToHeight: true
    items:
      - title: YouTube
        url: https://youtube.com
      - title: Netflix
        url: https://netflix.com/
      - title: Spotify
        url: https://open.spotify.com/
      - title: Soundcloud
        url: https://soundcloud.com
  - name: Anime/Manga
    displayData:
      collapsed: true
      cutToHeight: true
    items:
      - title: Livechart
        statusCheck: false
        url: https://livechart.me/
      - title: AnimeSchedule
        url: https://animeschedule.net/
  - name: Social
    displayData:
      collapsed: true
      cutToHeight: true
    items:
      - title: Twitter
        url: https://twitter.com
  - name: News
    displayData:
      collapsed: true
      cutToHeight: true
    items:
      - title: AnimeNewsNetwork
        url: https://www.animenewsnetwork.com/
  - name: Utilities
    displayData:
      collapsed: true
      cutToHeight: true
      sortBy: alphabetical
    items:
      - title: CyberChef
        description: 'All in one encryption, encoding, hashes etc.'
        url: https://gchq.github.io/CyberChef/
      - title: Healthchecks
        description: 'Off-site cron job and service monitoring'
        url: https://healthchecks.io/
      - title: Prettify YAML
        url: https://onlineyamltools.com/prettify-yaml
      - title: SortMyList
        target: "modal"
        url: https://sortmylist.com/
      - title: Omni Calculator
        url: https://www.omnicalculator.com/
      - title: Composerize
        target: "modal"
        url: https://www.composerize.com/
  - name: Games
    displayData:
      collapsed: true
      cutToHeight: true
    items:
      - title: Steam
        url: https://store.steampowered.com/
      - title: Hextris
        url: https://hextris.io/
      - title: NYT Wordle
        url: https://www.nytimes.com/games/wordle/index.html
```
