### DISCUSSION TITLE
Multi-Page Support!

### DISCUSSION THREAD

**Discussion by lissy93** [Lissy93/dashy#626] [Hot Tips]
You requested it.... Multi-page support is here!

Released in [2.0.8](https://github.com/Lissy93/dashy/releases/tag/2.0.8).

As well as your main page, you can now have as many sub-pages as you like. The config file for which, can either be managed locally within Dashy, or anywhere you like!

To get started, either create additional config files (also within `/public`), and link them to your main config under the `pages` section, like:

```yaml
pages:
- name: Networking Services
  path: 'networking.yml'
- name: Work Stuff
  path: 'work.yml'
```

Or, just link to any YAML config, anywhere on the internet, for example (using [snippet.host](https://snippet.host/))

```yaml
pages:
- name: Getting Started
  path: 'https://snippet.host/tvcw/raw'
- name: Homelab
  path: 'https://snippet.host/tetp/raw'
- name: Browser Startpage
  path: 'https://snippet.host/zcom/raw'
```

Local configs can be edited through the UI, just like your main config. Note that `appConfig` is always read from the primary config file.

For more info, and setup instructions, see, the docs: [Multi-Page Support](https://github.com/Lissy93/dashy/blob/master/docs/pages-and-sections.md)
