### DISCUSSION TITLE
How would I add a favicon to my config?

### DISCUSSION THREAD

**Discussion by PigeonFX** [Lissy93/dashy#750] [Help and Support]
Could someone talk a noob through adding a favicon, Here is my config:

```
 appConfig:
  theme: nord-frost
  layout: auto
  iconSize: large
  language: en
pageInfo:
  title: Raspberry Pi Server
  description: PIGEON
  navLinks:
    - title: GitHub
      path: https://github.com/Lissy93/dashy
      target: newtab
    - title: Documentation
      path: https://dashy.to/docs
      target: newtab
  footerText: ''
sections:
  - name: APPs
    icon: fas fa-rocket-launch
    items:
      - title: Shell In A Box
        description: Web SSH
        icon: icons/bash.png
        url: https://192.168.1.103:4200/
        target: newtab
        id: 0_340_shellinabox
      - title: Grafana
        description: analytics
        icon: icons/grafana.png
        url: http://192.168.1.103:3000/
        target: newtab
        id: 1_340_grafana
      - title: Transmission VPN
        description: Torrent
        icon: icons/transmission.png
        url: http://192.168.1.103:9091/
        target: newtab
        id: 2_340_transmissionvpn
      - title: File Browser
        description: Web File Browser
        icon: icons/filebrowser.png
        url: http://192.168.1.103:8082/files/
        target: newtab
        id: 3_340_filebrowser
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
  - name: Server
    icon: fas fa-server
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Portainer
        description: Docker
        icon: icons/portainer.png
        url: http://192.168.1.103:9000/
        target: newtab
        id: 0_631_portainer
      - title: RPI Docker Monitoring
        description: pi stats
        icon: icons/raspberrypi.png
        url: >-
          http://192.168.1.103:3000/d/Ss3q6hSZk/docker-metrics-for-raspberry-pi?orgId=1&refresh=30s
        target: newtab
        id: 1_631_rpidockermonitoring
      - title: PiHole
        description: DNS Sinkhole
        icon: icons/pihole.png
        url: http://192.168.1.103:1010/admin/index.php
        target: newtab
        id: 2_631_pihole
  - name: Cloud
    icon: fas fa-cloud
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: NextCloudPi
        description: Admin
        icon: icons/nextcloudpi.png
        url: https://192.168.1.103:4444/
        target: newtab
        id: 0_503_nextcloudpi
      - title: NextCloud
        description: Cloud Service
        icon: icons/nextcloud.png
        url: https://192.168.1.103:8443/
        target: newtab
        id: 1_503_nextcloud
```
