### DISCUSSION TITLE
Multi Page Support

### DISCUSSION THREAD

**Discussion by APT256** [Lissy93/dashy#824] [Help and Support]
I am having problems getting multi page support working in Dashy on UnRAID. Dashy itself is running fine and I was able to add pointers to sub-pages from the main page. The problem is that when I select one of the tabs for a sub-page, it never loads. I created two sub-pages named "computers" and "network". I have seperate yaml files for each named computers.yml and network. yml. These files are stored at: /mnt/user/appdata/ dashy. I then changed my docker composer config to have two additional "Path" settings (one for each sub-page).  Here is my complete Dashy config for Un RAID:

root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='dashy' --net='bridge' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e HOST_HOSTNAME="Unraid-1" -e HOST_CONTAINERNAME="dashy" -e 'UID'='99' -e 'GID'='100' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:80]/' -l net.unraid.docker.icon='https://raw.githubusercontent.com/A75G/docker-templates/master/templates/icons/dashy.png' -p '4000:80/tcp' -v '/mnt/user/appdata/dashy/conf.yml':'/app/public/conf.yml':'rw' -v '/mnt/user/appdata/dashy/icons/':'/app/public/item-icons/':'rw' -v '/mnt/user/appdata/dashy/computers.yml':'/app/public/computers.yml':'rw' -v '/mnt/user/appdata/dashy/network.yml':'/app/public/network.yml':'rw' 'lissy93/dashy:latest'
d254a901be80a2ce5d78bb76f394f5768a425652babb92e3bbcea90b7598196c

The command finished successfully!

I then went into the dahy console and verified that I now have a computers.yml and network.yml in the /apps/public folder. When I click on the "Computers" tab from the main page, the link shows as: http://192.168.100.69:4000/home/computers and nothing loads. 

Can someone please tell me what I'm doing wrong?

**Comment by Thomas-Arildtoft** [comment]
Did you ever found a solution to this problem ? As I have similar issues....

**Reply by shrippen** [reply]
I suspect the problem at how the file is referenced in the conf.yml. I recently implemented my first multi-page as well and struggled a bit with this.
It worked when I add the second yml as mentioned in my docker config and changed the conf.yml to just read

pages:
- name: Page2
  path: 'page2.yml'

**Reply by kiesekae** [reply]
I'm an extreme noob so there's a fair chance I am doing something wrong but following this thread I'm still unable to get a second page to work. 

I created a new path in my Unraid Dashy Docker settings making sure to copy the `Config File` pathnames from the original repo and changing the .yml names to match the yml file I created by running  `wget -O /mnt/user/appdata/dashy/[subpage].yml https://raw.githubusercontent.com/Lissy93/dashy/master/public/conf.yml` for my new subpage.

I see the new button in the Navbar of my main dashboard but when I click it, it does not do anything. When I refresh it, I get the following error: `Cannot GET /home/[subpage]`

Digging further I saw some resolved issues talking about changing the routingmode to hash instead of the default "history" but that also did not work for me. 

If there are any details I can include for someone to kindly assist me just let me know.  

Much thanks in advance.

**Reply by APT256** [reply]
@shrippen Would you mind sharing your config? I have been playing with this on and off now for awhile.

**Reply by kiesekae** [reply]
I think I was able to get this working. Seemed like I was the only one in any of the Issue or Discussion sections running my Dashy from an Unraid docker so I was a little confused on how to 'rebuild' as mentioned in other threads but I opened the console to the Dashy docker in Unraid and ran 'yarn build'. After rebuilding, I was able to get other pages to work successfully. 

Hope this helps some other noob like me.

**Reply by APT256** [reply]
Where did you read about running 'yarn build'? I have not seen a mention of that anywhere.

**Reply by kiesekae** [reply]
Between [THIS COMMENT](https://github.com/Lissy93/dashy/issues/929#issuecomment-1270736774) in issue #929 and the following section from [THIS PART OF THE DOCS](https://gist.github.com/Lissy93/000f712a5ce98f212817d20bc16bab10#about-the-config-file):
> • After making changes to the configuration, the application need to be rebuilt. This should happen automatically once running, but a rebuild can also be manually triggered with yarn build (or docker exec -it [container-id] yarn build in Docker)

I eventually got it to work. 

Each change I make on any page other than the main conf.yml requires me to run the 'yarn build' command in order to get those changes to show up. Kinda annoying but I guess less annoying than it not working at all. 

Edit: I did lots of things before getting it to work so I'm not sure if this contributed to it but;
In my docker config I added a 'Subpages' path and wrote it as shown below:
 
![image](https://user-images.githubusercontent.com/92613973/214375265-7aa440ce-6d25-45e7-9e2b-b880ae87761e.png)

**Reply by APT256** [reply]
Hmm, that is too much trouble for me ;-)

**Reply by kiesekae** [reply]
Its very likely I am overcomplicating things. Try only the following:

After adding your additional yml files to the same directory that your main conf.yml is in, simply open your settings menu on Dashy and click on the little wrench icon. About half way down, click on "Rebuild Application" and see if that gets your additional pages to work from your main page.

**Reply by APT256** [reply]
I'll give it a shot and let you know what happens.

**Reply by APT256** [reply]
Any chance I can get a sanitized copy of your main yml file? I am sure that I am doing something wrong there.

**Reply by kiesekae** [reply]
Sure! See below.

What issue are you running into?

```
pageInfo:
  title: Server
  description: Everything in one place!
  navLinks:
    - title: Server
      path: http://[000.000.0.0]/Main
      target: newtab
  footerText: ''
pages:
  - name: Crypto
    path: crypto.yml
  - name: Bookmarks
    path: bookmarks.yml
appConfig:
  theme: lissy
  backgroundImg: /bg.jpg
  layout: auto
  iconSize: large
  language: en
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: false
  statusCheckInterval: 0
  faviconApi: allesedv
  routingMode: hash
  enableMultiTasking: false
  widgetsAlwaysUseProxy: false
  webSearch:
    disableWebSearch: false
    searchEngine: google
    openingMethod: newtab
    searchBangs: {}
  enableFontAwesome: true
  enableMaterialDesignIcons: false
  hideComponents:
    hideHeading: false
    hideNav: false
    hideSearch: false
    hideSettings: true
    hideFooter: true
  auth:
    enableGuestAccess: false
    users: []
    enableKeycloak: false
  showSplashScreen: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false
  disableConfigurationForNonAdmin: false
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
  enableErrorReporting: false
  customColors:
    lissy:
      primary: hsla(0,0%,100%,0.8)
      background: '#060913'
      background-darker: '#191c20'
sections:
  - name: Today
    icon: fas fa-calendar-day
    displayData:
      collapsed: false
      rows: 4
      cols: 1
      sortBy: default
      hideForGuests: false
    widgets:
      - type: weather
        useProxy: true
        options:
          apiKey: [API KEY]
          city: [LOCATION]
          units: imperial
          hideDetails: false
        id: 
      - type: crypto-watch-list
        options:
          sortBy: default
          assets:
            - bitcoin
            - ethereum
            - litecoin
            - chainlink
            - polkadot
        id: 
      - type: rss-feed
        options:
          rssUrl: [URL]
          apiKey: [API KEY]
        id: 
  - name: Media
    icon: fas fa-play
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      cutToHeight: false
      collapsed: false
      hideForGuests: false
    items:
      - title: Plex
        description: Plex Media Server
        icon: favicon
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: Overseerr
        description: Media Request for Users
        icon: overseerr_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: Tautulli
        description: Plex Analytics
        icon: tautulli_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: AudioBooks
        description: Plex for Audiobooks
        icon: audiobook_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: Wiki
        description: My Selfhost Wiki
        icon: dokuwiki_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: EmulatorJS
        description: In Browser Retro Emulator
        icon: emulatorjs_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
  - name: '*Arrrrr'
    icon: fas fa-skull-crossbones
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Radarr
        description: Movie Download Automator
        icon: radarr_logo.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: Sonarr
        description: TV-Show Download Automator
        icon: sonarr_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: Lidarr
        description: Music Download Automator
        icon: lidarr_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: Bazarr
        description: Subtitle Download Automator
        icon: bazarr_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: Prowlarr
        description: Indexer Organization Tool
        icon: prowlarr_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: RuTorrent
        description: P2P Download Manager
        icon: rutorrent_icon.png
        url: >-
          [000.000.0.0]
        target: newtab
        id: 
  - name: Networking
    icon: fas fa-network-wired
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Router
        description: Router Management Portal
        icon: netgear_icon.png
        url: [000.000.0.0]
        target: newtab
        statusCheck: false
        id: 
      - title: Pi-Hole
        description: Network Level Ad-Blocker
        icon: pi-hole_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: Nginx
        description: Reverse Proxy Manager
        icon: nginx_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: WOL
        description: WOL Manager
        icon: wol_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: CloudFlare
        description: Domain Management
        icon: cloudflare_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: Pushover
        description: Notification Service
        icon: pushover_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
  - name: File Management
    icon: fas fa-folder-open
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Unraid Syncthing
        description: Unraid
        icon: syncthing_blue_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: Ferral Syncthing
        description: Feral
        icon: syncthing_green_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: Kiese-PC Syncthing
        description: Kiese-PC
        icon: syncthing_red_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
      - title: EmulatorJS Backend
        description: EmulatorJS Backend Management
        icon: emulatorjs-backend_icon.png
        url: [000.000.0.0]
        target: newtab
        id: 
  - name: Server Stats
    icon: fas fa-server
    displayData:
      collapsed: false
      rows: 1
      cols: 2
      useProxy: true
      sortBy: default
      hideForGuests: false
    widgets:
      - type: gl-cpu-history
        updateInterval: 60
        options:
          hostname: [000.000.0.0]
          chartColors:
            - '#9b5de5'
            - '#f15bb5'
            - '#00bbf9'
            - '#00f5d4'
          limit: 150
          chartHeight: 235
        id: 
      - type: gl-mem-history
        updateInterval: 60
        options:
          hostname: [000.000.0.0]
          chartColors:
            - '#00f5d4'
          limit: 150
          chartHeight: 235
        id: 
      - type: gl-network-traffic
        updateInterval: 60
        options:
          hostname: [000.000.0.0]
          chartColors:
            - '#9b5de5'
            - '#f15bb5'
            - '#00bbf9'
            - '#00f5d4'
          limit: 150
          chartHeight: 235
        id: 
  # - name: Kiese-PC Stats
    # icon: fas fa-desktop
    # displayData:
      # collapsed: true
      # rows: 1
      # cols: 1
      # useProxy: true
      # sortBy: default
      # hideForGuests: false
    # widgets:
      # - type: gl-cpu-history
        # updateInterval: 60
        # options:
          # hostname: [000.000.0.0]
          # chartColors:
            # - '#9b5de5'
            # - '#f15bb5'
            # - '#00bbf9'
            # - '#00f5d4'
          # limit: 150
          # chartHeight: 235
        # id: 
      # - type: gl-mem-history
        # updateInterval: 60
        # options:
          # hostname: [000.000.0.0]
          # chartColors:
            # - '#00f5d4'
          # limit: 150
          # chartHeight: 235
        # id: 
      # - type: gl-network-traffic
        # updateInterval: 60
        # options:
          # hostname: [000.000.0.0]
          # chartColors:
            # - '#9b5de5'
            # - '#f15bb5'
            # - '#00bbf9'
            # - '#00f5d4'
          # limit: 150
          # chartHeight: 235
        # id: 
```
