### DISCUSSION TITLE
AnonAddy Configuration?

### DISCUSSION THREAD

**Discussion by Tharic99** [Lissy93/dashy#888] [Help and Support]
Hi there!

I'm trying to get the AnonAddy widget configured and I'm unsure what you mean in the config under the apiKey section.

```
  - type: anonaddy
    options:
      apiKey: "xxxxxxxxxxxxxxxxxxxxxxxx\
        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\
        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      limit: 5
      sortBy: created_at
      disableControls: true
```

The API Key provided by AnonAddy is one single string of characters, not three broken out by a \ character.  It's similar to this (no, this is not my actual API key)

`uYxSW6yad45cfGn7B4Eiq93iX8xafw7NLBmugJXox`

I can't get the widget to "work" on the Dashy screen. Any suggestions?
