### ISSUE TITLE
[BUG] Overflow Issue on Tooltip and Description

### ISSUE THREAD

**Issue by changbowen** [Lissy93/dashy#1004]
### Environment

Self-Hosted (Docker)

### System

Chrome 108

### Version

2.1.1

### Describe the problem

There are some overflow issues with the global theme when there might be long random text in the item description. Did some tests and perhaps consider incorporate below styles to the global theme?

```css
.tile-title {
    overflow: hidden;
}

.item-wrapper.wrap-size-large {
    overflow: hidden;
}

.tile-title p.description {
    overflow: hidden;
}

.tooltip-inner {
    overflow-wrap: break-word;
}
```

### Additional info

Before
![image](https://user-images.githubusercontent.com/15975872/206367679-70997f99-bafa-4dc4-82dd-d7b98a14b48d.png)

After
![image](https://user-images.githubusercontent.com/15975872/206367913-6dbcfb6b-06eb-4009-be23-82b2858b4968.png)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
