### ISSUE TITLE
[BUG] Multi-Page Support , can´t get it to work.

### ISSUE THREAD

**Issue by ostgardh** [Lissy93/dashy#1005]
### Environment

Self-Hosted (Docker)

### System

Docker

### Version

Version:           20.10.21

### Describe the problem

I have add 
```
pages:
- name: Work Stuff
  path: 'work.yml'
  ```
  And make work.yml file 
  
  I can see Pages link in Dashy, but If I click on "Work Stuff" I coming to url: "http:mypage/home/work-stuff"
  But is not working. I see same page as conf.yml...
  And If I reload I get "Cannot GET /work-stuff"
  
  work.yml file is mounded in docker and have r&w.
  I don´t understad if I have make something  wrong or if this is bug???
  

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by ostgardh** [comment]
> which dir is `work.yml` mounted in? for the filename only syntax to work it needs to reside in `public`:
> 
> > The path (local or remote) to the config file to use.
> > For files located within `/public`, you only need to specify filename, for externally hosted files you must include the full URL
> 
> https://dashy.to/docs/configuring#pages-optional
> 
> > **                          [Configuring | Dashy](https://dashy.to/docs/configuring)                      **                            All app configuration is specified in /public/conf.yml which is in YAML Format format. If you're using Docker, this file can be passed in as a volume. Changes can either be made directly to this file, or done through the UI. From the UI you can also export, backup, reset, validate and download your configuration file.

Same as conf.yaml
/app/public/work.yml

**Comment by kozoke** [comment]
Same experience. Have the additional page in the same folder as the config.yml  Not working.

**Comment by pcl11** [comment]
Same experience. Not working.

**Comment by 4lexKidd** [comment]
same issue here.

I had a look into the routing code and found that the logic builds routes based on page "type" (home =default; workspace; dev) but i have not found any way for users to specify the page type in the configs.
Might be the issue there.

Also @Lissy93 may i suggest some fix to clearify and easy up multi-page Support:
Basicly i see two paths that would solve these multipage problems.
A) If page types should be kept, you might extend the needed configs for a sub-page to [name, path, type] and force a type folder (home, dev, etc) within the public forder with the config declared in the path.
B) You might drop the page types and let the routing be created on the domains  root (for example https://hostna.me/sub-page-name-with-replaced-whitespaces).
I see a lot of confusion (especially in the docker community) where to place (and in extend, create volumes to) the sub-page configs.

To serve a common use case:
I want to create a sub-page to seperate admin related sections from family used, none admin sections.

**Comment by schniggie** [comment]
For me it is also not working.

docker-compose.yml:
```
version: "3.8"
services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
    - /share/CACHEDEV1_DATA/docker/dashy/conf.yml:/app/public/conf.yml
    - /share/CACHEDEV1_DATA/docker/dashy/nas.yml:/app/public/nas.yml
    ...
```

conf.yml:
```
...
pages:
  - name: NAS
    path: nas.yml
```

Clicking the NAS button does nothing, opening in new tab gives 'Cannot GET /home/nas'

**Comment by semhoun** [comment]
Same bug in 2.1.1. I try the same configs with 2.1.0 and in this version pages work.
I use docker version.

**Comment by bodrick** [comment]
So I had the same issue , I fixed it by setting routingMode to hash.
I am using docker.

**Comment by Dylan-Bs** [comment]
I got the same problems, it's very frustrating because there is no error message and no logs ... (or I didn't find them). 

For me, the problem was in my file for the new page, some syntax problems (in widgets, the "limit: 60" in "type" instead of 'options'. 

I can suggest you to try with some [examples](https://gist.github.com/Lissy93/000f712a5ce98f212817d20bc16bab10) and when you have a page who work, do changes carrefully!

(using Docker version 20.10.3, build 55f0773)

**Comment by papampi** [comment]
Don't know if this is related to sme issue or not
I can't open dashy/home either, getting "**Cannot GET /home**"
Adding pages also gives "**Cannot GET /home/test**"

dashy only opens at `http://ip:port` and not` http://ip:port/home` or `http://ip:port/home/test` or `http://ip:port/test`

**Comment by schniggie** [comment]
For me the problem still exists. Tried all suggestions from above. Nothing solves it for me.

**Comment by phmassa** [comment]
same issue. I am running dashy in Docker.

**Comment by yglory** [comment]
> 
@Fiala06 is right! 
Here are the steps I have taken:
1. Make sure all .yml files for each page are correct and there are no yellow triangles in config.
2. Mount the folder which contains .yml files to /app/public/
3. Mount my.config to /app/public/conf.yml.
4. Set PUID and GUID.
5. Set NODE_ENV=production.
6. Following Fiala06's screenshot, override command with 'yarn' 'build-and-start' in portainer.
7. Go to the dashy page:
    7.1 Log in as an administrator
    7.2 Press ctrl+r to refresh
    7.3 At this point, dashy should start reporting errors
    7.4 Open the log of Dashy in Portainer, and you can see that Dashy is reporting an error and starting to compile.
    7.5 Wait a moment, when the compilation is complete, just return to the Dashy page, everything is great~~~~~~

**Comment by jiakme** [comment]
Same experience. Not working.

**Comment by symphoniccow** [comment]
I had similar issues finding a method to get pages working. This is what worked for me:

1. Ensure you have mapped the newly created .conf file that has been created - this is done within the docker run command or docker-compose file
eg docker run
  -v  ./dashy/conf.yml:/app/public/conf.yml \
  -v  ./dashy/newconf.yml:/app/public/newconf.yml \
eg docker-compose
  volumes:
    - ./dashy/conf.yml:/app/public/conf.yml
    - ./dashy/newconf.yml:/app/public/newconf.yml

2. You will obviously need to bring the container down and up again
eg
  docker compose down
  docker compose up

3. Once this is done, I created the additional page entry through the UI - Edit Mode ->Edit Pages ( I did this as editing the conf.yml file directly didn't seem to work)

4. Finally you then need to run the 'Rebuild Application' under the configuration options within the UI or use 'yarn' 'build-and-start'

After following this process I now have multiple working pages. If you make changes to the sub pages I've found that a rebuild is necessary to reflect the changes in the UI.

**Comment by DPCools** [comment]
I have tried every thing here  remote pages and local pages I just a 404 error or it loads the yml code. I'm at a loss with this.

**Comment by CrazyWolf13** [comment]
can confirm, the issue persists

**Comment by mian-muhammad** [comment]
can confirm, the issue still persists.

**Comment by PuckeyP** [comment]
Is Dashy unsupported ?

**Comment by ykelvis** [comment]
If the files are mounted correctly, doing a "rebuild application" through UI should fix this. (do this manually everytime the config files are edited)

**Comment by PuckeyP** [comment]
Nope does not work

**Comment by ykelvis** [comment]
> > files are mounted correctly, doing a "rebuild application" through UI should fix this. (do this manually everytim
> 
> When you say mounted correctly I have done very tutorial i can find and there's a lot and trayed every possible config, trust me I have wasted hours on this. show how about you wright your how to guide to help people insted of being not so helpful.

I just did a test, and it seemed to me "rebuild" is really the one thing fixed it. I'll post configs below so you could give it a test. Upon bring the container up, the "frontpage" button doestn't do anything. After "rebuild" through the web UI, and check the logs to make sure it is rebuilt, the "frontpage" button will work.

docker-compose.yml
```
  test:
    image: lissy93/dashy
    ports:
      - 8000:80
    volumes:
      - ./test/conf.yml:/app/public/conf.yml
      - ./test/www.yml:/app/public/www.yml
    restart: unless-stopped
```
conf.yml
```
appConfig:
  layout: vertical
  defaultOpeningMethod: sametab
  enableMultiTasking: true
  disableContextMenu: true
  iconSize: large
  theme: cherry-blossom
  language: en
  hideComponents:
    hideSearch: false
    hideSettings: false
    hideSplashScreen: true
    hideFooter: true
    hideHeading: false
    hideNav: false
  startingView: default
  statusCheck: true
  statusCheckInterval: 30
  faviconApi: allesedv
  colCount: 4
  routingMode: history
  widgetsAlwaysUseProxy: true
  webSearch:
    disableWebSearch: true
    searchEngine: duckduckgo
    openingMethod: newtab
    searchBangs: {}
  enableFontAwesome: true
  enableMaterialDesignIcons: false
  auth:
    enableGuestAccess: false
    users: []
    enableKeycloak: false
  showSplashScreen: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false
  disableConfigurationForNonAdmin: false
  allowConfigEdit: true
  enableServiceWorker: false
  disableUpdateChecks: true
  disableSmartSort: false
  enableErrorReporting: false
pageInfo:
  title: homelab
  description: ''
  navLinks: null
  footerText: ''
pages:
  - name: frontpage
    path: 'www.yml'
```
www.yml
```
---
# Page meta info, like heading, footer text and nav links
pageInfo:
  title: Hello, Alicia
  description: General browser startpage
  logo: https://i.ibb.co/71WyyzM/little-bot-3.png

# Optional app settings and configuration
appConfig:
  statusCheck: false
  theme: charry-blossom
  fontAwesomeKey: c94dc2b452
  customCss: '.clock p.time { font-size: 3rem !important; }'
  layout: vertical
  iconSize: small

# Main content - An array of sections, each containing an array of items
sections:
- name: Dev & Cloud
  icon: far fa-code
  items:
  - title: GitHub
    icon: favicon
    url: https://github.com/
```

**Comment by DPCools** [comment]
thanks for the information, i will give it a try but that is just a faf.

**Comment by DPCools** [comment]
may look at this https://homarr.dev/  as its more active and replace dashy.

**Comment by Photo64** [comment]
The rebuild didn't work for me, I assume there is still no fix for this?

**Comment by rflemen** [comment]
> > > files are mounted correctly, doing a "rebuild application" through UI should fix this. (do this manually everytim
> > 
> > 
> > When you say mounted correctly I have done very tutorial i can find and there's a lot and trayed every possible config, trust me I have wasted hours on this. show how about you wright your how to guide to help people insted of being not so helpful.
> 
> I just did a test, and it seemed to me "rebuild" is really the one thing fixed it. I'll post configs below so you could give it a test. Upon bring the container up, the "frontpage" button doestn't do anything. After "rebuild" through the web UI, and check the logs to make sure it is rebuilt, the "frontpage" button will work.
> 
> docker-compose.yml
> 
> ```
>   test:
>     image: lissy93/dashy
>     ports:
>       - 8000:80
>     volumes:
>       - ./test/conf.yml:/app/public/conf.yml
>       - ./test/www.yml:/app/public/www.yml
>     restart: unless-stopped
> ```
> 
> conf.yml
> 
> ```
> appConfig:
>   layout: vertical
>   defaultOpeningMethod: sametab
>   enableMultiTasking: true
>   disableContextMenu: true
>   iconSize: large
>   theme: cherry-blossom
>   language: en
>   hideComponents:
>     hideSearch: false
>     hideSettings: false
>     hideSplashScreen: true
>     hideFooter: true
>     hideHeading: false
>     hideNav: false
>   startingView: default
>   statusCheck: true
>   statusCheckInterval: 30
>   faviconApi: allesedv
>   colCount: 4
>   routingMode: history
>   widgetsAlwaysUseProxy: true
>   webSearch:
>     disableWebSearch: true
>     searchEngine: duckduckgo
>     openingMethod: newtab
>     searchBangs: {}
>   enableFontAwesome: true
>   enableMaterialDesignIcons: false
>   auth:
>     enableGuestAccess: false
>     users: []
>     enableKeycloak: false
>   showSplashScreen: false
>   preventWriteToDisk: false
>   preventLocalSave: false
>   disableConfiguration: false
>   disableConfigurationForNonAdmin: false
>   allowConfigEdit: true
>   enableServiceWorker: false
>   disableUpdateChecks: true
>   disableSmartSort: false
>   enableErrorReporting: false
> pageInfo:
>   title: homelab
>   description: ''
>   navLinks: null
>   footerText: ''
> pages:
>   - name: frontpage
>     path: 'www.yml'
> ```
> 
> [www.yml](http://www.yml)
> 
> ```
> ---
> # Page meta info, like heading, footer text and nav links
> pageInfo:
>   title: Hello, Alicia
>   description: General browser startpage
>   logo: https://i.ibb.co/71WyyzM/little-bot-3.png
> 
> # Optional app settings and configuration
> appConfig:
>   statusCheck: false
>   theme: charry-blossom
>   fontAwesomeKey: c94dc2b452
>   customCss: '.clock p.time { font-size: 3rem !important; }'
>   layout: vertical
>   iconSize: small
> 
> # Main content - An array of sections, each containing an array of items
> sections:
> - name: Dev & Cloud
>   icon: far fa-code
>   items:
>   - title: GitHub
>     icon: favicon
>     url: https://github.com/
> ```

Making sure each .yml file was mapped and mounted as a volume then rebuilding worked for me.   Thanks for this thread and leading me in right direction!

**Comment by Photo64** [comment]
I've tried this again mimicking the recent post above but still not working for me.  I'll have to come up with another solution as the multi-pages just doesn't appear to work or is too complicated to implement.

**Comment by rflemen** [comment]
> I've tried this again mimicking the recent post above but still not working for me. I'll have to come up with another solution as the multi-pages just doesn't appear to work or is too complicated to implement.

If it helps at all here is how I did it.   You have to make each .yml a volume...here is command I used to run dashy...my .yml files are in the /opt/dashy/config directory before this is run:

docker run -d --name=dashy --restart=always --network=host -v /opt/dashy/config/conf.yml:/app/public/conf.yml  -v 
/opt/dashy/config/test.yml:/app/public/test.yml lissy93/dashy

You see the two -v statements mapping the yml files....then I build the application from command line like so:

docker exec -it dashy yarn build

After that the pages worked for me...

![Screenshot 2023-10-06 at 2 03 15 PM](https://github.com/Lissy93/dashy/assets/124945067/5979e332-f37e-4e32-bd84-78c378f9f32d)

**Comment by Photo64** [comment]
So after messing around a little bit more I actually did get it to work so that it switches to the second page however while I was previously able to make updates to the yml code through via ssh in VSCode I noticed that doesn't seem to work anymore. Will any changes or updates now require a re-build each time?

**Comment by Photo64** [comment]
So unfortunately this app is just becoming too flakey to use. While I did momentarily get the second page to show I am unable to make any edits through the UI and as I mentioned earlier for some reason it no longer recognizes any changes I make directly in the conf.yml or pages.yml. So I thought maybe I need to do a rebuild again however doing that just prevented the second page from showing again. 

I really like a lot of the aspects of this Dashboard but it looks like I might have to move on from it until it becomes more stable to work with.

**Comment by icf20** [comment]
volumes:
      - ./test/conf.yml:/app/public/conf.yml
      - ./test/www.yml:/app/public/www.yml
      
**dont to that because is for folders not files**

**Comment by icf20** [comment]
just to make sure, u need to have
```

volumes:
  - ./test/dashyconfigs:/app/public/
```

inside that u need the default conf.yml the main config file 
inside conf.yml
```
pages:
  - name: www
    path: www.yml

```
should be done

**Comment by pc12346** [comment]
I finally got it work!  Running Dashy 2.1.0 not in Docker. The answer is here: https://dashy.to/docs/troubleshooting/#refused-to-connect-in-modal-or-workspace-view

Under Troubleshooting, I found this little gem.

**404 On Multi-Page Apps**
[T]his can be fixed under `appConfig`, by setting `routingMode `to `hash`. Then rebuilding, and refreshing the page.

From the `config.xml`, my value was `history`. Changed it to `hash`. Rebuild Dashy.

Second thing.
I am only maintaining the pages from `config.xml`.  I had an issue trying to access the landing page as home.  This is what worked for me in `config.xml`.

```
pages:
  - name: Home
    path: ''
  - name: Server Room
    path: serverroom.yml
```

Hope this helps someone else.
