### ISSUE TITLE
Color Changes to Themes are Not Applied in Latest Docker Image

### ISSUE THREAD

**Issue by teamRibcage** [Lissy93/dashy#1012]
### Environment

Self-Hosted (Docker)

### System

Docker 20.10.21

### Version

2.1.1

### Describe the problem

After updating the Docker container to the latest image ( `lissy93/dashy:latest` ) it seems that changes made to Theme colors and fonts in the `conf.yml` file are not applied. In my setup, I have most all of the colors/fonts defined as
```yaml
theme: "basic"
  customColors:    
    basic:
      primary: '#282a40'
      background: '#1c1e2d'
      background-darker: '#212335'
      info: '#04e4f4'
      success: '#00ca8b'
      ...
```
After updating the container, the selected theme shows to be "Basic", however none of the modified colors or fonts are changed. Re-deploying the container using the image `lissy93/dashy:2.1.0` fixes this issue.

I searched through Issues already opened, but didn't see anything similar raised yet. I apologize if I missed something!
Thanks again for all your hard work on this project! 🙂

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
