### ISSUE TITLE
[BUG] IP Blacklist widget times out

### ISSUE THREAD

**Issue by schniggie** [Lissy93/dashy#1014]
### Environment

Netlify

### System

Google Chrome 108.0.5359.111

### Version

2.1.1

### Describe the problem

Running it on Netlify and the part of the config, looks like:

```
- name: I know about you
  icon: far fa-poo
  displayData:
    collapsed: false
    hideForGuests: false
  widgets:
  - type: public-ip
  - type: blacklist-check
    useProxy: true # also tried false, that doesn't fix it
    timeout: 5000
    options:
      apiKey: key_REMOVED
```

And thw following error is thrown:

```
{
    "message": "timeout of 5000ms exceeded",
    "name": "AxiosError",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 5000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "FormData": null
        },
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Target-URL": "https://api.blacklistchecker.com/check/44.213.62.20",
            "CustomHeaders": "{\"Authorization\":\"Basic key_REMOVED\"}"
        },
        "method": "get",
        "url": "https://flauschers.netlify.app/cors-proxy",
        "data": "{}"
    },
    "code": "ECONNABORTED",
    "status": null
}
```

### Additional info

Already tried to set the timeout to 5000 (default 500) without any luck.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
