### ISSUE TITLE
[BUG] Authentication does not work correctly

### ISSUE THREAD

**Issue by malordin** [Lissy93/dashy#1082]
### Environment

Self-Hosted (Docker)

### System

Windows 10 21H2 , Firefox 109.0 x64

### Version

2.1.1

### Describe the problem

I have set up two users, malordin and admin, with hash and type : admin. But if I log in without cookies and then log in, I can't change the configuration under any user with admin rights. In addition, I have 2 sections hidden from Guests, but when I log in as any user with admin privileges, I still can not see them. What is the problem?

![изображение](https://user-images.githubusercontent.com/20083687/214239298-e9a65cf8-9c9c-4612-b0f2-7ada28fe7c64.png)

### Additional info

Here is my beginning of conf.yml

```
appConfig:
  theme: crayola
  layout: auto
  iconSize: medium
  language: en
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: false
  statusCheckInterval: 1
  faviconApi: allesedv
  routingMode: history
  enableMultiTasking: false
  widgetsAlwaysUseProxy: false
  webSearch:
    disableWebSearch: false
    searchEngine: duckduckgo
    openingMethod: newtab
    searchBangs: {}
  enableFontAwesome: true
  enableMaterialDesignIcons: false
  hideComponents:
    hideHeading: false
    hideNav: false
    hideSearch: false
    hideSettings: false
    hideFooter: false
  disableConfigurationForNonAdmin: true
  auth:
    enableGuestAccess: true
    users:
      - user: admin
        hash: 12345
        type: admin
      - user: malordin
        hash: 1245
        type: admin
    enableKeycloak: false
  showSplashScreen: false
```
There is no information in the logs:

```
➜  dashy sudo docker-compose logs -f
Dashy  | yarn run v1.22.15
Dashy  | $ node server
Dashy  | 
Dashy  | Checking config file against schema...
Dashy  | ✔️ Config file is valid, no issues found
Dashy  | 
Dashy  | SSL Not Enabled: Public key not present
Dashy  | 
Dashy  | 
Dashy  |  ██████╗  █████╗ ███████╗██╗  ██╗██╗   ██╗
Dashy  |  ██╔══██╗██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝
Dashy  |  ██║  ██║███████║███████╗███████║ ╚████╔╝
Dashy  |  ██║  ██║██╔══██║╚════██║██╔══██║  ╚██╔╝
Dashy  |  ██████╔╝██║  ██║███████║██║  ██║   ██║
Dashy  |  ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝
Dashy  | 
Dashy  | *******************************************************************************************
Dashy  | Welcome to Dashy! 🚀
Dashy  | Your new dashboard is now up and running with Docker
Dashy  | *******************************************************************************************
Dashy  | 
Dashy  | 
Dashy  | Using Dashy V-2.1.1. Update Check Complete
Dashy  | ✅ Dashy is Up-to-Date
Dashy  | 
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
