### ISSUE TITLE
[BUG] ERROR, unable to validate 'conf.yml'

### ISSUE THREAD

**Issue by 0n1cOn3** [Lissy93/dashy#1127]
### Environment

Self-Hosted (Docker)

### System

Fedora Server 37

### Version

V-2.1.1

### Describe the problem

1) Clone the dashy repos to a directory of my choice (/home/user/Docker-Tests or /docker)
2) Adjustment path of the configuration file
3) Start the container

Instant Error as in the description already mentioned
Does not matter if with root or non-root user account.
When entering the website, the console also spits out an error (It's obvious why ;) )

Error: EACCES: permission denied, stat '/app/public/conf.yml'

### Additional info

Firefox Dev Utilities Output:

Deprecation warning: The `simple-icons` entrypoint will be removed in the next major. Please switch to using `import * as icons from "simple-icons/icons"` if you need an object with all the icons. [index.js:1:8](webpack:///node_modules/simple-icons/index.js)
XHRGEThttp://10.1.200.240/conf.yml
[HTTP/1.1 500 Internal Server Error 5ms]

Uncaught (in promise) 
Object { message: "Request failed with status code 500", name: "AxiosError", code: "ERR_BAD_RESPONSE", config: {…}, request: XMLHttpRequest, response: {…}, stack: "" }
[asyncToGenerator.js:6:4](webpack:///node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js)
XHRGEThttp://10.1.200.240/conf.yml
[HTTP/1.1 500 Internal Server Error 5ms]

Object { message: "Request failed with status code 500", name: "AxiosError", code: "ERR_BAD_RESPONSE", config: {…}, request: XMLHttpRequest, response: {…}, stack: "" }

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by 0n1cOn3** [comment]
Still relevant 🙃

**Comment by jeangjenq** [comment]
Still relevant, pretty much went through the same steps in this issue today and experiencing the exact same thing.

```bash
[dashy] | yarn run v1.22.15
[dashy] | $ node server
[dashy] | 
[dashy] | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[dashy] |  Error, unable to validate 'conf.yml' 
[dashy] | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[dashy] | 
[dashy] | ⚠️ Permission denied 
[dashy] | 
[dashy] | SSL Not Enabled: Public key not present
[dashy] | 
[dashy] | 
[dashy] |  ██████╗  █████╗ ███████╗██╗  ██╗██╗   ██╗
[dashy] |  ██╔══██╗██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝
[dashy] |  ██║  ██║███████║███████╗███████║ ╚████╔╝
[dashy] |  ██║  ██║██╔══██║╚════██║██╔══██║  ╚██╔╝
[dashy] |  ██████╔╝██║  ██║███████║██║  ██║   ██║
[dashy] |  ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝
[dashy] | 
[dashy] | *******************************************************************************************
[dashy] | Welcome to Dashy! 🚀
[dashy] | Your new dashboard is now up and running with Docker
[dashy] | *******************************************************************************************
[dashy] | 
[dashy] | 
[dashy] | Using Dashy V-2.1.1. Update Check Complete
[dashy] | ✅ Dashy is Up-to-Date
[dashy] | 
Error: EACCES: permission denied, stat '/app/public/conf.yml'
Error: EACCES: permission denied, stat '/app/public/conf.yml'
```

**Comment by jeangjenq** [comment]
@0n1cOn3 
I made some progress today. I tested this on both Fedora Workstation and Fedora Silverblue 38.
If I use the `docker` and `docker-compose` from fedora software repository,
`sudo dnf install docker docker-compose` in Workstation.
`rpm-ostree install docker docker-compose` in Silverblue.
This issue occurs.

But if you follow the official docker engine installation instructions [here](https://docs.docker.com/engine/install/fedora/).
Dashy starts up without issue.
Workstation:
```bash
sudo dnf -y install dnf-plugins-core
sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
sudo dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

Silverblue:
```bash
cd /etc/yum.repos.d/
wget https://download.docker.com/linux/fedora/docker-ce.repo
rpm-ostree install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

**Comment by Joker214kk** [comment]
yarn run v1.22.15
$ node server

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 Error, unable to validate 'conf.yml' 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚠️ Config file could not be found at ./public/conf.yml

SSL Not Enabled: Public key not present


 ██████╗  █████╗ ███████╗██╗  ██╗██╗   ██╗
 ██╔══██╗██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝
 ██║  ██║███████║███████╗███████║ ╚████╔╝
 ██║  ██║██╔══██║╚════██║██╔══██║  ╚██╔╝
 ██████╔╝██║  ██║███████║██║  ██║   ██║
 ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝

*******************************************************************************************
Welcome to Dashy! 🚀
Your new dashboard is now up and running with Docker
*******************************************************************************************


Using Dashy V-2.1.1. Update Check Complete
✅ Dashy is Up-to-Date

I have the same identical issue on Debian 11, where I executed it on docker-compose

dashy:
    image: ghcr.io/lissy93/dashy:latest
    container_name: Dashy
    volumes:
     - /opt/dashy/public:/app/public
     - /opt/dashy/item-icons:/app/item-icons
    ports:
      - 4000:80
    environment:
      - UID=1000
      - GID=1000
    restart: always
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

**Comment by Joker214kk** [comment]
It's still relevant

**Comment by elendil7** [comment]
Getting the same issue here, with docker-compose

```
  # Dashy Dashboard
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy:latest
    container_name: dashy
    build:
      context: ./services/dashy
      dockerfile: Dockerfile.yml
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - ./services/dashy/public:/app/public
    # ports:
    #   - 4000:80
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # Specify restart policy
    restart: unless-stopped
    depends_on:
      - nginx
```
