### ISSUE TITLE
[BUG] hideForKeycloakUsers does not hide elements

### ISSUE THREAD

**Issue by jakob1379** [Lissy93/dashy#1166]
### Environment

Self-Hosted (Docker)

### System

firefox 112, docker version 23.0.4

### Version

2.1.1

### Describe the problem

I have setup a selfhosted keycloak instance as described in the docs for dashy and `(hide|show)ForKeycloakUsers` does not seem to work as expected. The login part worked after downgrading from 2.1.1. to 2.1.0 (#678). Now the issue is that my user is part of the group `dashyReadOnly` as seen here on Keycloak

![image](https://user-images.githubusercontent.com/17257805/234851803-46bd3a8b-0b4b-4280-8720-40bfce92da00.png)

And in the dashu config I have this

```yaml
appConfig:
  statusCheckInterval: 0 # service will only be checked on initial page load
  preventWriteToDisk: true
  theme: default
  enableFontAwesome: true
  statusCheck: true
  auth:
    enableGuestAccess: false
    enableKeycloak: true
    keycloak:
      serverUrl: 'https://auth.mypage.com'
      realm: 'test-realm'
      clientId: 'test-client'
      legacySupport: true # remove this if keycloak >= v17

sections: # An array of sections
  - name: Apps
    icon: far fa-rocket
    items:
      - title: test-app
        description: testing the tests to improve other tests
        statusCheckAllowInsecure: true
        icon: si-streamlit
        url: https://tests.com
        displayData:
          hideForKeycloakUsers:
            groups: ['dashyReadOnly']
```

Now when I log in as the user `jga` I can still see the item `test-app`. 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
