### ISSUE TITLE
[FEATURE_REQUEST] Calendar Widget?

### ISSUE THREAD

**Issue by Sonny-Crockett** [lissy93/dashy#1201]
### Is your feature request related to a problem? If so, please describe.

I searched the widget documentation and outside of something custom, I did not see a normal calendar widget. 

Is this something that is planned?

### Describe the solution you'd like

I would love to use Dashy to replace Dakboard and a good calendar would make all the difference. Basically just need to be able to hook up Google Calendars and able to choose which color dots/events are on for what calendars. Anything beyond that would be great, but thats typically what I need with a calendar app. 

A Multi-Week/Month mode, Week Mode, and Agenda mode would be the best options for layouts IMO.

[Some Examples here](https://dakboard.freshdesk.com/support/solutions/articles/35000099436-calendar-layouts-and-settings)

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

None

**Comment by Sonny-Crockett** [comment]
Yes still like it 😄

**Comment by Nepo26** [comment]
You can use the embed widget and use the embed feature of the google calendar if that is what you use @Sonny-Crockett. But I agree that maybe something that reads iCal and use it could be used. Not so sure.

**Comment by Hannes1909** [comment]
+1 - Google Calendar doesnt seem possible to add as a widget to dashy besides from making the calender public (for iframe widget, but I dont want my Google calendar to be any more public than it already is - hi google! ;) ) or exposing it as iCAL url thats currently not supported in dashy.

**Comment by Scot-Survivor** [comment]
How about instead of google calendars, just support iCal?

**Comment by Hannes1909** [comment]
iCal would be the best way, not locking in to vendor specific authentication - for reference, my google calendars in homepage are also just iCal URLs:

```
- type: ical # Show calendar events from another service
  url:  https://calendar.google.com/calendar/ical/[REDACTED]/[REDACTED]/basic.ics # URL with calendar events
  name: Google # required - name for these calendar events
  color: blue # optional - defaults to pre-defined color for the service (zinc for ical)
  params: # optional - additional params for the service
    showName: true # optional - show name before event title in event line - defaults to false
```

**Comment by Mela** [comment]
A calendar widget would be great.

**Comment by kris9854** [comment]
+1 would be nice.
Would make it easy to have it on a tablet or something in the kitchen. To check the daily schedule.

**Comment by pfuller88** [comment]
not a perfect solution but this works on it's own page...

- name: Calendar
  icon:  hl-beef
  displayData:
    cols: 5
  widgets:
  - type: iframe
    options:
      frameHeight: 600	
      useProxy: true
      url: https://grabcalendar.com/wp-content/uploads/2025/11/Blank-2026-Calendar.jpg

**Comment by lissy93** [comment]
This took way too long, sorry 😬

I've got something ready, which I'm just testing atm. 
It does generic ical support, so should work with all providers if you can surface that link.

I'll let you know once merged + released, and will update the docs (https://dashy.to/docs/widgets#calendar). but usage will be like this:

```yaml
- type: calendar
  options:
    calendarUrl: https://nextcloud.example.com/remote.php/dav/public-calendars/AbCdEf123?export
    days: 14
```

and with combining calendars and colour-coding them:

```yaml
- type: calendar
  options:
    limit: 15
    calendarUrl:
      - url: https://calendar.google.com/calendar/ical/xxxx/private-xxxx/basic.ics
        name: Personal
        color: '#5cabca'
      - url: webcal://p12-calendars.icloud.com/published/2/xxxx
        name: Family
        color: '#e8j54a'
```
