### ISSUE TITLE
[FEATURE_REQUEST] Masonry layout

### ISSUE THREAD

**Issue by mfnalex** [Lissy93/dashy#1233]
### Describe the solution you'd like

Right now, the "auto" layout leads to unused space (marked red in the screenshot):

![image](https://github.com/Lissy93/dashy/assets/1122571/10c24dc0-16c7-4ae1-af15-f32f0db6c826)

It'd be nice if an option could be added to use a "masonry"-kinda layout, like from the following screenshot:

![image](https://github.com/Lissy93/dashy/assets/1122571/3be2e8d2-7f2c-4f27-bc59-f8b9a054df63)

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

None

**Comment by itsrllyhim** [comment]
Second! Would love to see this addition.

**Comment by mfnalex** [comment]
> This issue has gone 3 months without an update. To keep the ticket open, please indicate that it is still relevant in a comment below. Otherwise it will be closed in 5 working days.

Still relevant

**Comment by bulletinmybeard** [comment]
For everyone who would like to have a masonry-like layout with pure CSS, add the following to your `conf.yml` (`appConfig > customCss`):

```css
.item-group-container {
  display: block !important;
  columns: 4;
  column-gap: 1rem;
  gap: .85rem !important;
  margin-top: 1.5rem !important;
}
.item-group-container > * {
  break-inside: avoid;
  margin: 0 0 1rem 0 !important;
}
```

## conf.yml
```yaml
appConfig:
  customCss: '.item-group-container { gap: .85rem !important; display: block !important; columns: 4; column-gap: 1rem; margin-top: 1.5rem !important; } .item-group-container > * { break-inside: avoid; margin: 0 0 1rem 0 !important; }'
```

<img width="1800" height="864" alt="Image" src="https://github.com/user-attachments/assets/86023bd4-df85-426b-9e7c-c17b4e000275" />
