### ISSUE TITLE
[BUG] Change Font Clock Widget 

### ISSUE THREAD

**Issue by CrazyWolf13** [Lissy93/dashy#1239]
### Environment

Self-Hosted (Docker)

### System

RaspberryPi OS 32Bit

### Version

2.1.1

### Describe the problem

I wanted to change the font from the Clock widget, so I tried a whole day and finally found some hints: [https://github.com/Lissy93/dashy/blob/master/src/components/Widgets/Clock.vue](url) 
I change the Font and font family to be Podkova which is already in the folder: [https://github.com/Lissy93/dashy/tree/master/public/fonts](url)

But after a container restart nothing happened so I did a rebuild from the UI, and then I got the error: "Error: ENOENT: no such file or directory, stat '/app/dist/index.html" And after I manually sudo docker exec into the container the whole dist folder was gone. A recreate from portainer solved this.

But still how could I change the font of the clock to podkova? What am I doing wrong? Why is there this error?
Many thanks for an answer:)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
No still a request

**Comment by CrazyWolf13** [comment]
This damm Bot When the project is stale but issue request keep getting closed...
@Lissy93

**Comment by Lissy93** [comment]
Hey @CrazyWolf13 

I was able to get this working using the `.clock .time` selector + using `!important`

```yaml
appConfig:
  customCss: '.clock .time { font-family: "Roboto", monospace !important; }'

sections:
- name: CrazyWolf13 Clock Demo
  icon: ⏰
  widgets:
  - type: clock
```

This should work with any font you have installed on your local PC.

If you want to use a font not yet installed, you could import it, also within the CSS.
For example:

```yaml
appConfig:
  customCss: >
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap');
    .clock .time { font-family: "Poppins", monospace !important; }
```
