### ISSUE TITLE
[QUESTION] Problem with custom css

### ISSUE THREAD

**Issue by pw-64** [Lissy93/dashy#1245]
### Question

My styles.css isn't being applied to the page.

I am running from a docker-compose file:
```
dashy:
    image: "lissy93/dashy:latest"
    container_name: Dashy
    ports:
      - 80:80
    volumes:
      - "./dashy/config.yml:/app/public/conf.yml"
      - "./dashy/icons:/app/public/item-icons"
      - "./dashy/styles.css:/app/themes/custom.css"
```

config.yml:
```
appConfig:
  layout: auto
  iconSize: medium
  theme: cyberpunk
  externalStyleSheet: ["/app/themes/custom.css"]
  statusCheckInterval: 60
pageInfo:
  title: Testing
sections:
- name: Docker
  icon: docker.svg
  items:
    [...]
```

Here is the directory structure on the host:
```
server/
├─ dashy/
│  ├─ icons/
│  │  ├─ docker.svg
│  ├─ config.yml
│  ├─ styles.css
├─ docker-compose.yml
```

The config file seems to be read because if i down-up the stack it stays in the cyberpunk theme. The docker icon does appear. However, the styles don't seem to apply.

I assume it is either:
1. I have an incorrect path somewhere
2. This isnt how styles are applied (the documentation is quite confusing to me)

styles.css:
```
.tile-icon {
    --item-icon-transform: none;
    -webkit-filter: none;
}
```

This is just to remove the shadow which is applied if using a locally stored image. If I use `logo: si-docker` there is no shadow. All I did was download that svg from simpleicons.org so it would work without outside internet access. I will also do some padding and margins, just trying to get this working first.

docker.svg is attached so you can see the contents:
![file](https://github.com/Lissy93/dashy/assets/64085841/6597ea3b-1d85-4972-8586-a8185e4a4754)

### Category

Using Icons

### Please tick the boxes

- [x] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
