### ISSUE TITLE
[BUG] Public Holiday Widget "Unable to fetch holiday data"

### ISSUE THREAD

**Issue by Salan54** [Lissy93/dashy#1268]
### Environment

Self-Hosted (Docker)

### System

Docker version 24.0.4, build 3713ee1

### Version

2.1.1

### Describe the problem

Was working till a few weeks ago. But now, the public holiday widget failed with :

An error occurred, see the logs for more info.
Unable to fetch holiday data
Retry

I tried to change the country from FR to US, but to no avail.

I have the Cryptocurrencies widget in my config, and this one works perfectly...

Thanks for your help.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by cauterize** [comment]
Not the author, but pretty much same problem.

Config:
```yaml
pageInfo:
  ...
appConfig:
  ...
sections:
  - name: Today
    icon: far fa-cloud-sun
    displayData:
      collapsed: false
      hideForGuests: false
    widgets:
      - type: clock
        options:
          timeZone: Europe/Berlin
          format: de-DE
        id: 0_513_clock
      - type: weather
        options:
          apiKey: efdbade728b37086877a5e83442004db
          city: Berlin
        id: 1_513_weather
      - type: public-holidays
        options:
          country: DE
          holidayType: all
          monthsToShow: 6
          state: SH
        id: 2_513_publicholidays
```

This results in the following query to the Api:
https://kayaposoft.com/enrico/json/v2.0/?action=getHolidaysForDateRange&fromDate=26-7-2023&toDate=26-1-2024&country=DE&holidayType=all&region=SH

It returns 200 just fine... but the UI still states `An error occurred, see the logs for more info. Unable to fetch holiday data. This is likely not an issue with Dashy, but rather your configuration. If you think it is a bug, please open a ticket on GitHub`

This config worked for months and I can't find whats wrong. [And yes I checked the docs.](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#public-holidays)

**Comment by ViciousWall** [comment]
I am having the same issue, the widget does not work and gives the mentioned error. Below is my config.
---
# Page meta info, like heading, footer text and nav links
pageInfo:
  title: Dashy
  description: Welcome to your new dashboard!
  navLinks:
  - title: GitHub
    path: https://github.com/Lissy93/dashy
  - title: Documentation
    path: https://dashy.to/docs

# Optional app settings and configuration
appConfig:
  theme: colorful

# Main content - An array of sections, each containing an array of items
sections:
- name: Today
  displayData:
    collapsed: false
    hideForGuests: false
  widgets:
  - type: clock
  - type: public-holidays
    options:
      country: NZ
      state: CAN
      holidayType: all
      monthsToShow: 12

**Comment by Salan54** [comment]
Sorry for the delay.
Thanks guys for your answers so far.
Yes, the problem persists.
My config is very straightforward : 
```
- type:  public-holidays
  label: "Jours fériés"
  options:
  country: "US"
  holidayType: "all"
  monthsToShow: 3
```
Initially, country was FR, I switched to US to see if that changes something but to no avail.
I'm using Dashy V-2.1.1 in a docker container.
Thanks for your help.
