### ISSUE TITLE
[BUG] Custom CSS cannot be applied.

### ISSUE THREAD

**Issue by 94tiger** [Lissy93/dashy#1296]
### Environment

Self-Hosted (Docker)

### System

Docker

### Version

2.1.1

### Describe the problem

style.css
```style.css
@font-face {
  font-family: "NanumBarunpenB";
  src: url("/fonts/NanumBarunpenB.ttf");
}
```
conf.yaml

```conf.yaml
appConfig:
  externalStyleSheet: ['/assets/style.css']
```
I saved the above to a file. And applied like. `--font-body: "NanumBarunpenB", serif;`
However, css was not applied, and when the same content written in style.css was applied in the UI, it was applied.
This is not permanently applied, but only applied temporarily when the 'Save Changes' button is pressed, and restored when refreshing.

<img width="947" alt="image" src="https://github.com/Lissy93/dashy/assets/29029527/5d2918c2-f3cb-4ebc-87be-853204698a44">

css applied after pressing 'Save Changes' button

<img width="959" alt="image" src="https://github.com/Lissy93/dashy/assets/29029527/c87977dd-c75a-40ab-85c0-6746772a224d">

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
can confirm, something there is either broken or the documentation outdated, to less detailed.

**Comment by Lissy93** [comment]
@lopiv2 CC'ing your ticket, #1242 into here.

**Comment by codevski** [comment]
seem to have this issue as well I think its done correctly so this is my docker:

```   
  - /var/local/dashy/gruvbox.scss:/app/src/styles/user-defined-themes.scss
```

My scss file:
```
html[data-theme='gruvbox'] {
  --primary: #d79921;
  --background: #282828;
  --background-darker: #3c3836;
  --item-group-background: #504945;
  --item-background: var(--background);
  --item-background-hover: var(--background-darker);
  --item-hover-shadow: 0 1px 3px #d79921b3, 0 1px 2px #d79921bf;
  --font-body: 'Cascadia Code', 'Fira Code', monospace;
  --font-headings: 'Source Han Serif VF', 'Georgia', serif;
  --text-color: #ebdbb2;
  --text-color-subtle: #bdae93;
  --border-color: #7c6f64;
  --notification-bg: #cc241d;
  --modal-bg: #3c3836;
  --button-bg: #98971a;
  --button-text: #282828;
}
```

and finally the appConfig
```
appConfig:
  theme: gruvbox
  cssThemes:
    - gruvbox
  customCss: >-
    @media (min-width: 1780px) { .home
    .item-group-container:not(.item-size-large) { grid-template-columns:
    repeat(3, 1fr); } } .home .item-group-container.item-size-large
    .item-group-grid, .home .item-group-container.orientation-vertical
    .item-group-grid { display: flex !important; }
  auth:
    enableGuestAccess: true
```

**Comment by CrazyWolf13** [comment]
Hi
This problems seems to be related to dashy not automatically rebuilding on changes, see #1479 and https://github.com/Lissy93/dashy/issues/1290#issuecomment-1884249018 
A new release has just been published, which should fix this issue, so please upgrade to the latest version.
If this is not the case just respond back to this ticket and I'll reopen this issue.
Thanks and have a nice day.

**Comment by EliasGagnef** [comment]
I'm having a similar issue, when I change to my custom theme and reload the page the colors are still blue, here's screenshots:

First one:
![1](https://github.com/Lissy93/dashy/assets/46574798/91e19c2c-8cba-4a5e-8420-45020b1c24c7)
after changing from default to custom 
![2](https://github.com/Lissy93/dashy/assets/46574798/c7ac831f-748b-48b7-b81a-7cb4fe16027b)
and second one is after reloading my tab, I could be doing something wrong though, I have tried rebuilding with the theme on but it just goes blue

**Comment by Lissy93** [comment]
Oh interesting, @EliasGagnef - how did you make your theme, was it a custom stylesheet, or just setting custom colors?

I'm guessing that it could be  `appConfig.customColors` isn't being saved correctly. Do you mind sharing that part of your `conf.yml` with me?

Also, that is a sick dashboard, I love it! 😍

**Comment by EliasGagnef** [comment]
> Oh interesting, @EliasGagnef - how did you make your theme, was it a custom stylesheet, or just setting custom colors?
> 
> I'm guessing that it could be `appConfig.customColors` isn't being saved correctly. Do you mind sharing that part of your `conf.yml` with me?
> 
> Also, that is a sick dashboard, I love it! 😍

Thank you so much :D

I set the custom colors in the UI, but I have also edited the dashy_conf.yml, I probably did something wrong :p

I'm not sure what part so I'll just send the whole file here it is:

```
appConfig:
  backgroundImg: https://i.imgur.com/oErxY4Z.jpg
  theme: custom
  layout: auto
  iconSize: large
  language: sv
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: false
  statusCheckInterval: 0
  faviconApi: allesedv
  routingMode: history
  enableMultiTasking: false
  widgetsAlwaysUseProxy: false
  webSearch:
    disableWebSearch: false
    searchEngine: duckduckgo
    openingMethod: newtab
    searchBangs: {}
  enableFontAwesome: true
  enableMaterialDesignIcons: false
  hideComponents:
    hideHeading: false
    hideNav: false
    hideSearch: false
    hideSettings: false
    hideFooter: false
  auth:
    enableGuestAccess: false
    users: []
    enableKeycloak: false
  showSplashScreen: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false
  disableConfigurationForNonAdmin: false
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
  enableErrorReporting: false
  customColors:
    custom:
      primary: '#ebb75c'
      background: '#2d2200'
      background-darker: '#130d00'
pageInfo:
  title: Cayuga
  description: ''
  navLinks: []
  footerText: ''
sections:
  - name: Media
    icon: hl-duckdns
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Jellyfin
        icon: hl-jellyfin
        url: http://localhost:8096/web/index.html#!/home.html
        id: 0_480_jellyfin
      - title: Qbittorrent
        icon: hl-qbittorrent
        url: http://192.168.1.21:8080/
        target: null
        id: 1_480_qbittorrent
      - title: Sonarr
        icon: hl-sonarr
        url: http://192.168.1.21:8989/
        target: null
        id: 2_480_sonarr
      - title: Radarr
        icon: hl-radarr
        url: http://192.168.1.21:7878/
        target: null
        id: 3_480_radarr
      - title: Bazarr
        icon: hl-bazarr
        url: http://192.168.1.21:6767/series
        target: null
        id: 4_480_bazarr
      - title: Prowlarr
        icon: hl-prowlarr
        url: http://192.168.1.21:9696/
        target: null
        id: 5_480_prowlarr
  - name: Admin
    icon: hl-jellystat
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Cockpit
        icon: hl-cockpit
        url: https://192.168.1.21:9090/
        target: null
        id: 0_489_cockpit
      - title: Portainer
        icon: hl-portainer
        url: https://192.168.1.21:9443/#!/2/docker/dashboard
        target: null
        id: 1_489_portainer
  - name: wiidget
    widgets:
      - type: gluetun-status
        useProxy: true
        options:
          hostname: http://localhost:8000
          visibleFields: >-
            public_ip,region,country,city,location,organisation,postal_code,timezone
        id: 0_749_gluetunstatus
      - type: image
        options:
          imagePath: https://i.imgur.com/VoVqUld.gif
        id: 1_749_image

```

**Comment by Lissy93** [comment]
Thanks :)

This is indeed a bug, so I'll re-open.

As a workaround, your config works fine if you set the theme to `default` and then also put your colors under `default` (instead of custom). This will also work using any other theme as the base theme (except `custom`).

<img align="right" width="300" src="https://github.com/Lissy93/dashy/assets/1862727/602f316b-9e36-45f5-9230-70a402b1de52" />


```yaml
appConfig:
  # .....
  customCss: '.settings-outer { background: transparent !important; }'
  customColors:
    default:
      primary: '#ebb75c'
      background: '#2d2200'
      background-darker: '#130d00'
      settings-background: 'transparent'

```

**Comment by EliasGagnef** [comment]
> Thanks :)
> 
> This is indeed a bug, so I'll re-open.
> 
> As a workaround, your config works fine if you set the theme to `default` and then also put your colors under `default` (instead of custom). This will also work using any other theme as the base theme (except `custom`).
> <img alt="" width="300" src="https://private-user-images.githubusercontent.com/1862727/311539957-602f316b-9e36-45f5-9230-70a402b1de52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMTYxMDEsIm5iZiI6MTcxMDExNTgwMSwicGF0aCI6Ii8xODYyNzI3LzMxMTUzOTk1Ny02MDJmMzE2Yi05ZTM2LTQ1ZjUtOTIzMC03MGE0MDJiMWRlNTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMDAxMDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTE3NTFmMWVjZjJjM2M4ZjU5ZmMxZWFiMjEwZGU1MjZjMTJhODE4NjJmNTQzMDIxYzYwMzMwOWZjOGUxNDJkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0Ml0-Up-jNB9To3RPy0PqrPUiFM3iy3wQXUT51aGH0k">
> 
> ```yaml
> appConfig:
>   # .....
>   customCss: '.settings-outer { background: transparent !important; }'
>   customColors:
>     default:
>       primary: '#ebb75c'
>       background: '#2d2200'
>       background-darker: '#130d00'
>       settings-background: 'transparent'
> ```

Thank you, I put the colors under "bee" since that one has the fonts I like :D (also fits perfectly with Adventure Time), works perfectly!!

Also thank you so much for making Dashy, it really makes using my computer/server much more fun :)

Btw if you want to add the theme to the user showcase section I am 1000% okay with that (even though it's a little basic compared to the other ones lol)

**Comment by CrazyWolf13** [comment]
@the1ts 
Could you test this again with re-pulling the :latest tag? That should actually be resolved.

**Comment by the1ts** [comment]
Confirmed it builds by:

1. blanking my `user-defined-themes.scss` restarting and theme not present
2. putting theme file back in place, restarting, I see checking, then building and the theme appears.

Thanks again.

**Comment by CrazyWolf13** [comment]
@the1ts  Is this issue still persistent with the :latest tag?

I cannot reproduce this here.

**Comment by the1ts** [comment]
@CrazyWolf13 like you, I believe this problem is fixed, my custom CSS is working fine now.
I was able to remove the file, restart. Then put the file back in and restart and no manual intervention was required and I can confirm I'm still at :latest.

**Comment by ribas89** [comment]
I’m replying here because this was the first result I found that closely matches my problem.

To make your theme or theme tuning work using SCSS:

If you're only tuning an existing theme, ignore step 1.

1 - If you're creating a new theme, define its name in the config so it appears in the theme list.

```yml
appConfig:
  cssThemes: ['my-custom-theme']
```

2 - Create an empty file named **user-defined-themes.scss** and mount it in the container. Example:

```yml
    volumes:
      - ./dashy/conf.yml:/app/user-data/conf.yml
      - ./dashy/item-icons:/app/user-data/item-icons:ro
      - ./dashy/user-defined-themes.scss:/app/src/styles/user-defined-themes.scss:ro
```

3 - Change the properties you want.

```scss
html[data-theme="my-custom-theme"] body,
html[data-theme="my-custom-theme"] div.login-page {
  background-image: url(/item-icons/the-ball-of-fire-dips.jpg);
  background-repeat: repeat;
  background-size: cover;
  background-attachment: fixed;
}

// or

html[data-theme="vaporware"] body,
html[data-theme="vaporware"] div.login-page {
  background-image: url(/item-icons/the-ball-of-fire-dips.jpg);
  background-repeat: repeat;
  background-size: cover;
  background-attachment: fixed;
}
```

4 - Recreate the container to rebuild the CSS.

```
docker compose down dashy
docker compose up -d dashy
```

**Comment by TafkaMax** [comment]
Was this broken in 4.X.X releases? I used to use the same logic, but its not working anymore for me.

EDIT: I migrated to how it is said to do in the docs officially, but to no avail.

**Comment by ribas89** [comment]
> I’m replying here because this was the first result I found that closely matches my problem.
> 
> To make your theme or theme tuning work using SCSS:
> 
> If you're only tuning an existing theme, ignore step 1.
> 
> 1 - If you're creating a new theme, define its name in the config so it appears in the theme list.
> 
> appConfig:
>   cssThemes: ['my-custom-theme']
> 
> 2 - Create an empty file named **user-defined-themes.scss** and mount it in the container. Example:
> 
>     volumes:
>       - ./dashy/conf.yml:/app/user-data/conf.yml
>       - ./dashy/item-icons:/app/user-data/item-icons:ro
>       - ./dashy/user-defined-themes.scss:/app/src/styles/user-defined-themes.scss:ro
> 
> 3 - Change the properties you want.
> 
> html[data-theme="my-custom-theme"] body,
> html[data-theme="my-custom-theme"] div.login-page {
>   background-image: url(/item-icons/the-ball-of-fire-dips.jpg);
>   background-repeat: repeat;
>   background-size: cover;
>   background-attachment: fixed;
> }
> 
> // or
> 
> html[data-theme="vaporware"] body,
> html[data-theme="vaporware"] div.login-page {
>   background-image: url(/item-icons/the-ball-of-fire-dips.jpg);
>   background-repeat: repeat;
>   background-size: cover;
>   background-attachment: fixed;
> }
> 
> 4 - Recreate the container to rebuild the CSS.
> 
> ```
> docker compose down dashy
> docker compose up -d dashy
> ```

This solution does not work anymore. I got it working by putting the custom CSS directly in the config file:

```yml
appConfig:
  theme: vaporware
  ...
  disableUpdateChecks: false
  disableSmartSort: false
  customColors:
    vaporware:
      primary: '#5c90eb'
      background: '#2c418b'
      background-darker: '#210f37'
  customCss: |
    html[data-theme="vaporware"] body,
    html[data-theme="vaporware"] div.login-page {
      background: url("/item-icons/the-ball-of-fire-dips.jpg") repeat fixed center center / cover;
    }
pageInfo:
  ...
```
It's not my most elegant solution, but it works well enough for my setup. If anyone knows a better way to apply custom CSS on top of a default theme, I'd really appreciate the suggestion.

**Comment by lissy93** [comment]
You're right that the user-defined-themes.scss mount method no longer works on recent versions, and that's expected. Older images rebuilt on startup, which is why mounting it + recreating the container used to work; the 4.x images are pre-built and don't rebuild at runtime, so a mounted SCSS file is ignored unless you rebuild the image yourself.


The reliable runtime approach (no rebuild needed) is `externalStyleSheet`.
Dashy serves your user-data directory as static files at the site root, so:

### 1) Put your CSS in the directory user-data directory

This is the same dir as your conf.yml, e.g. `./user-data/mytheme.css`:

```css
html[data-theme='vaporware'] body,
html[data-theme='vaporware'] div.login-page {
  background: url("/item-icons/the-ball-of-fire-dips.jpg") repeat fixed center
center / cover;
}
```

### 2) Reference it in config
```yaml
appConfig:
  theme: vaporware
  cssThemes: [vaporware]        # only needed for a brand-new theme name
  externalStyleSheet: /mytheme.css
```

### 3) Refresh page
Should work now :)
If not, check the browser config for any errors
