### ISSUE TITLE
[QUESTION] caddy setup

### ISSUE THREAD

**Issue by zuble** [Lissy93/dashy#1330]
### Question

docker-compose.yml
```
---
version: "3.8"
services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: Dashy
    # Pass in your config file below, by specifying the path on your host machine
    # volumes:
      # - /root/my-config.yml:/app/public/conf.yml
    ports:
      - "4000:80"
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: $DOCKER_MY_NETWORK
    external: true
```

Caddyfile
```
dash.{$MY_DOMAIN} {
        header {
                X-Frame-Options SAMEORIGIN
                X-Robots-Tag "none"
        }

        encode gzip

        reverse_proxy dashy:4000
}
```
the dashy container is running healthy 
```
yarn run v1.22.15
$ node server
Checking config file against schema...
✔️ Config file is valid, no issues found
SSL Not Enabled: Public key not present

Welcome to Dashy! 🚀
Your new dashboard is now up and running with Docker
Using Dashy V-2.1.1. Update Check Complete
✅ Dashy is Up-to-Date
```
and  here are the logs from caddy container
`ERR ts=1695506363.1284177 logger=http.log.error msg=dial tcp 172.18.0.6:4000: connect: connection refused request={"remote_ip":"  ","remote_port":"   ","client_ip":"   ","proto":"HTTP/2.0","method":"GET","host":"dash.******","uri":"/","headers":{"Upgrade-Insecure-Requests":["1"],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Site":["none"],"Sec-Fetch-User":["?1"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"],"Accept-Language":["en-US,en;q=0.5"],"Dnt":["1"],"Sec-Fetch-Mode":["navigate"],"Te":["trailers"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; rv:112.0) Gecko/20100101 Firefox/112.0"],"Accept-Encoding":["gzip, deflate, br"]},"tls":{"resumed":false,"version":772,"cipher_suite":4867,"proto":"h2","server_name":"dash.******"}} duration=0.003785185 status=502 err_id=2sem9u7vc err_trace=reverseproxy.statusError (reverseproxy.go:1246)`

anyone has experience setting things up using caddy ? 
thanks in advance

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
