### ISSUE TITLE
[QUESTION] Dashy 1.5.6 consumes more RAM

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#136]
Hello, 
Since Dashy 1.5.6 it does not start anymore. Indeed, I allocate 756MB of RAM to it. With Dashy 1.5.6 this is no longer sufficient, I have to give it 1024MB.

With my container limited to 1024MB, Dashy 1.5.6 works.

I already find that allocating 756 MB of RAM is already significant. 1024MB, that starts to do a lot, my machine only has 8GB, more now that Dashy is available on ARM, a lot of ARM machine has little RAM.

Where did this high demand for RAM come from when Dashy was launched? Because we can see that once launched, Dashy consumes much less RAM (around 250MB).

Logs with the container limited to 756MB:

```
yarn run v1.22.5,
$ npm-run-all --parallel build-watch start,
$ vue-cli-service build --watch --mode production,
$ node server,
,
Checking config file against schema...,
No issues found, your configuration is valid :),
,
,
,
 ██████╗  █████╗ ███████╗██╗  ██╗██╗   ██╗,
 ██╔══██╗██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝,
 ██║  ██║███████║███████╗███████║ ╚████╔╝,
 ██║  ██║██╔══██║╚════██║██╔══██║  ╚██╔╝,
 ██████╔╝██║  ██║███████║██║  ██║   ██║,
 ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝,
,
*******************************************************************************************,
Welcome to Dashy! 🚀,
Your new dashboard is now up and running in container ID dc91db3e1af1,
After updating your config file, run  'docker exec -it dc91db3e1af1 yarn build' to rebuild,
*******************************************************************************************,
,
,
Using Dashy V-1.5.6. Update Check Complete,
Unable to check for updates,
,
-  Building for production...,
 WARN  A new version of sass-loader is available. Please upgrade for best experience.,
,
<--- Last few GCs --->,
,
[61:0x5627bf910340]    86833 ms: Scavenge (reduce) 373.1 (378.4) -> 372.8 (379.4) MB, 23.6 / 0.0 ms  (average mu = 0.291, current mu = 0.351) allocation failure ,
[61:0x5627bf910340]    86909 ms: Scavenge (reduce) 373.4 (381.4) -> 373.1 (381.4) MB, 25.1 / 0.0 ms  (average mu = 0.291, current mu = 0.351) allocation failure ,
[61:0x5627bf910340]    87005 ms: Scavenge (reduce) 373.8 (378.4) -> 373.4 (379.9) MB, 25.2 / 0.0 ms  (average mu = 0.291, current mu = 0.351) allocation failure ,
,
,
<--- JS stacktrace --->,
,
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory,
error Command failed with signal "SIGABRT".,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.,
ERROR: "build-watch" exited with 1.,
error Command failed with exit code 1.,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.,
```

**Comment by Lissy93** [comment]
Oh, that doesn't look good.
It's weird, because this PR mostly just included docs updates, some UI stuff and a slight refactor.

This seems to be a Node.js error, and possibly caused my a memory leak in the version used, I've seen something similar in a previous project a while back. I will take a proper look this evening, and try and get it sorted asap. Thanks for raising it :)

Which tag are you using, is it the normal amd `:latest` image?

**Comment by EVOTk** [comment]
Hello, 

> Which tag are you using, is it the normal amd `:latest` image?

Yes. 

My composition which no longer works:
```
version: "3.8"
services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
      - /home/evo-dashy/docker/dashy/conf.yml:/app/public/conf.yml
      - /home/evo-dashy/docker/dashy/item-icons:/app/public/item-icons
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    mem_limit: 756M
    mem_reservation: 256M
```

If I increase mem_limit, Dashy works:
```
version: "3.8"
services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
      - /home/evo-dashy/docker/dashy/conf.yml:/app/public/conf.yml
      - /home/evo-dashy/docker/dashy/item-icons:/app/public/item-icons
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    mem_limit: 1024M
    mem_reservation: 256M
```
