### ISSUE TITLE
[BUG] Items are always placed above widget within a section despite the order in the config

### ISSUE THREAD

**Issue by Antiz96** [Lissy93/dashy#1362]
### Environment

Self-Hosted (Docker)

### System

Firefox 119.0, Arch Linux, Docker 24.0.6

### Version

2.1.1

### Describe the problem

*Not sure if it is a bug or the intended behavior... If it's the latter, I can open a feature request if you prefer*

If there are both items and widgets within a single section, it looks like items are always placed above/before the widgets despite the order in the config:

```
[...]
- name: Section Name
  icon: icon

  widgets:
  - type: widget1
    options:
      option1: some option
  - type: widget2
    options:
      option1: some option
   
  items:
  - title: item1
    description: item1
    icon: icon
    url: some url
```

With the above config, the `item1` is placed above `widget1` and `widget2` despite being declared after them in the config file.
I tried using some `displayData` parameters within the config file but it did not work as it seems to only affect items placement (and not widgets').

The expected behavior could be to preserve the order of the config placement (so widgets before items with the above config) or alternatively having an additional parameter to set the order.
Could be something like:
```
[...]
displayData:
  sortBy:
    - widgets
    - items
    - [...]
[...]
```

### Additional info

I'm looking for a way to put Glances items below the Glances widgets in the below screenshot:

![2023-10-25_11-32](https://github.com/Lissy93/dashy/assets/53110319/2839056e-578c-4198-9124-b44d208764cf)

By the way, Dashy's awesome. Thanks for your wonderful work!

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
