### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by MichaelTrip** [Lissy93/dashy#1374]
### Environment

Other (Specify below)

### System

Kubernetes

### Version

latest and 2.1.1

### Describe the problem

I have dashy configured and set the following parameters:

```yaml
    appConfig:
      auth:
        users:
          - user: michael
            hash: <passwordhash>
            type: admin
        enableGuestAccess: false
...
```
After logging in everything seems ok. If i start another browser the dashboard doesn´t require a login and i can see all my tiles. Have also noticed that my name is not in the "config" section:

![Screenshot from 2023-11-07 13-20-21](https://github.com/Lissy93/dashy/assets/1826203/b349bef8-1e29-47b4-ac3a-2f5b105e0c92)

In most cases your username should be there.

But this seems to be a serious bug for me. For now i am reverting back to 2.1.0 for now. 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
