### ISSUE TITLE
[QUESTION] Config not working on docker?

### ISSUE THREAD

**Issue by Inrego** [Lissy93/dashy#142]
Hi there. This looks great, and I'm trying to deploy it with docker. However, I'm having issues with configuration.

I've mapped the volume to conf.yml, and as far as I can tell - it's working. When I modify config in the web UI and save, I can see the changes in my conf.yml file.
After saving, I do a rebuild, which also completes just fine (log output below).

```
Using Dashy V-1.5.7. Update Check Complete
Unable to check for updates

-  Building for production...
 WARN  A new version of sass-loader is available. Please upgrade for best experience.
 DONE  Compiled successfully in 14894ms9:06:55 AM

  File                                      Size             Gzipped

  dist/js/chunk-vendors.18a6705c.js         1919.94 KiB      559.08 KiB
  dist/js/dashy.b20dbb74.js                 212.71 KiB       62.97 KiB
  dist/precache-manifest.50c09b745725981    19.66 KiB        3.47 KiB
  e237f7cae6741b734.js
  dist/js/about.0c77a650.js                 4.48 KiB         1.99 KiB
  dist/service-worker.js                    1.04 KiB         0.61 KiB
  dist/css/dashy.2d652b28.css               110.25 KiB       16.72 KiB
  dist/css/chunk-vendors.c7f81a37.css       6.59 KiB         1.93 KiB
  dist/css/about.a64c098d.css               1.04 KiB         0.34 KiB

  Images and other types of assets omitted.

```

However, after a reload, none of my changes are visible, and when going back to config in the web UI, it's back to default values.
So it's kind of like it can write the conf file, but not read it?

For simplicity, I tried just removing one of the navbar links, so here's how my conf.yml file looks after saving from web UI:

```
appConfig:
  layout: "auto"
  iconSize: "medium"
  language: "en"
  theme: "nord"
pageInfo:
  title: "Dashy"
  description: ""
  navLinks:
    - title: "Home"
      path: "/"
  footerText: ""
sections: []
```
