### ISSUE TITLE
[QUESTION] <Wiki from GitHub is not useful but docs from dash.io worked.>

### ISSUE THREAD

**Issue by sandy9707** [Lissy93/dashy#1436]
### Question

<img width="981" alt="image" src="https://github.com/Lissy93/dashy/assets/93817573/ed867449-6f29-487f-a6c7-1f5b92c3d6a6">

This could be:

```yaml
appConfig:
  auth:
    users:
    - user: alicia
      hash: 4D1E58C90B3B94BCAD9848ECCACD6D2A8C9FBC5CA913304BBA5CDEAB36FEEFA3
      type: admin
    - user: bob
      hash: 5E884898DA28047151D0E56F8DC6292773603D0D6AABBDD62A11EF721D1542D8
```

I try and find [authentication · Lissy93/dashy Wiki · GitHub](https://github.com/Lissy93/dashy/wiki/authentication/b2e548c97559860f3c3938215734be40b503de2d) is wrong. Which could be work is from [Authentication | Dashy](https://dashy.to/docs/authentication%23setting-up-authentication).

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
