### ISSUE TITLE
[BUG] Dashy v2.1.2 consuming all assigned resources after changing config (either via GUI or direct conf.yml change)

### ISSUE THREAD

**Issue by CTHRU** [Lissy93/dashy#1500]
### Environment

Self-Hosted (Docker)

### System

raspberry pi os lite - 6.1.0-rpi8-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64 GNU/Linux

### Version

2.1.2

### Describe the problem

I'm still experiencing a similar issue to #1494 , but now it happens when dashy is active.

I started from the default config:
- I tried to add config to the `conf.yml` file directly (adding 1 section + 1 item).
- I tried to add a section with a single item via the GUI and `Save to Disk` from GUI.

It appears  that in both cases the symptoms are very similar to issue #1494 (due to repeating rebuild? But this time not at startup time but when the changes are applied while the app is running).
Observations:
- the docker container consumes all assigned CPU resources (in my case 50% op cpu)
- physical memory and swap memory are slowly filled until the system falls out of memory / the memory limit of the container is reached ( example below taken before the system would become unresponsive, but it will go up till 256 and filling swap memory too).   
 
      CONTAINER ID   NAME         CPU %     MEM USAGE / LIMIT   MEM %     NET I/O           BLOCK I/O         PIDS
                                  dashy        47.16%    205.7MiB / 256MiB   80.35%    396kB / 14.6MB    173MB / 1.2MB     84

- When the container is started the first time with the default conf.yml file, everything is fine and max memory usage does not exceed 150 MB.
- As soon as any change is applied while running, the above behavior is noticed.
- Keeping the config changes and bringing the docker container down and up as follows, solves the issue. The application seems to be correctly updated upon restart and then idles on cpu with about 150 MB RAM usage.

  ```sh
     sudo docker compose down
     sudo docker compose up -d --build
  ```
  This is also my current workaround to prevent the issue each time I apply a configuration change.

my `compose.yaml` file (fyi, i copied the `/app/public` folder contents of the source code to the mounted dir on the host)

```yaml
services:
  dashy:
    container_name: dashy
    hostname: dashy
    memswap_limit: 384M
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
    restart: unless-stopped
    ports:
      - 80:80
    image: lissy93/dashy:latest
    volumes:
      - ${HOST_APP_DIR}/public:/app/public
    networks:
      - dashy
networks:
  dashy:
    name: dashy
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
