### ISSUE TITLE
Persisted Folder(s)

### ISSUE THREAD

**Issue by WildStar2022** [Lissy93/dashy#1517]
### Environment

MicroK8s Kubernetes

### Version

2.1.2

### Describe the problem

For Dashy to function with MicroK8s Kubernetes, it requires at least one persisted folder for conf.yml, and  other files that need to be preserved before a redeployment or reboot.  With Portainer, it can be installed using a Kubectl shell as well as with Helm.  However, upon a reboot, it reverts back to its original installation, and any changes are lost. 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

Update:  With version 3.0 this still doesn't work!  Once installed using Portainer, it always redeploys from scratch upon a reboot.  Also, if I try to make /app/user-data the persisted folder, the installation fails.

**Comment by CrazyWolf13** [comment]
Are you sure your config is valid and works for other apps?

Could you share some more details?

I don't know that much about kubernetes, but I think other people have manged to install it successfully.

**Comment by Lissy93** [comment]
Yeah, I think this sounds like something with your Kubernetes config, because it should work okay.
Do you need to create a PV and PVC? And if so, have you done that?

**Comment by Lissy93** [comment]
Kuberneties is not my not my area of expertise, so please someone jump in and correct me if I'm wrong here. But I would _think_ that for MicroK8s you'd need something roughly like:


### PersistentVolume

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dashy-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/microk8s-data/dashy"
```
### PersistentVolumeClaim

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashy-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

### Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
      - name: dashy
        image: lissy93/dashy:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/user-data
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: dashy-pvc
```

**Comment by WildStar2022** [comment]
Below is the application form created with Portainer.

For persisted folder in this configuration I used the following values:

	path in container: /config (I tried all sorts of different paths)
	new volume instead of an existing volume
	requested size: 5GB
	storage: microk8s-hostpath
	

No matter what I choose for path in container, and unlike my other apps, nothing ever goes in there and Dashy always goes back to default after a reboot.  I see my changes go in /app/user-data when saving to disk, but it will not deploy if I use that for my persisted folder.

Hope that helps!  :)
``` yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    io.portainer.kubernetes.application.note: ""
  creationTimestamp: 2024-05-11T20:17:16Z
  generation: 1
  labels:
    io.portainer.kubernetes.application.name: dashy
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: dashy
  name: dashy
  namespace: default
  uid: 0b77fa93-6116-44bf-879f-906b25ce9c9a
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dashy
  serviceName: headless-dashy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dashy
        io.portainer.kubernetes.application.name: dashy
    spec:
      containers:
        - env:
            - name: TZ
              value: America/Montreal
            - name: MODE_ENV
              value: production
          image: lissy93/dashy:latest
          imagePullPolicy: Always
          name: dashy
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config
              name: dashy-2a785c16-af22-45ec-8077-40ab81c3e6e6
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: dashy-2a785c16-af22-45ec-8077-40ab81c3e6e6
          persistentVolumeClaim:
            claimName: dashy-2a785c16-af22-45ec-8077-40ab81c3e6e6
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        labels:
          app: dashy
          io.portainer.kubernetes.application.name: dashy
          io.portainer.kubernetes.application.owner: admin
        name: dashy-2a785c16-af22-45ec-8077-40ab81c3e6e6
        namespace: default
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5G
        storageClassName: microk8s-hostpath
        volumeMode: Filesystem
      status:
        phase: Pending
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: dashy-56f4949bdf
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: dashy-56f4949bdf
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2024-05-11T20:17:16Z
  labels:
    io.portainer.kubernetes.application.name: dashy
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: dashy
  name: headless-dashy
  namespace: default
  uid: 79cce4b7-872d-4904-ab85-a2e75890f6c8
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: dashy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2024-05-11T20:17:16Z
  labels:
    io.portainer.kubernetes.application.name: dashy
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: dashy
  name: dashy
  namespace: default
  uid: b31e4430-9b01-44eb-9511-13dc46f6d41b
spec:
  clusterIP: 10.152.183.65
  clusterIPs:
    - 10.152.183.65
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: port-0
      nodePort: 31080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: dashy
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```
