### ISSUE TITLE
[FEATURE_REQUEST] Hide city details for the Public IP widget

### ISSUE THREAD

**Issue by diasdmhub** [Lissy93/dashy#1530]
Can you add an option to hide the city name in the [Public IP widget](https://dashy.to/docs/widgets#public-ip)?

Something like this:
```
widgets:
  - type: public-ip
    options:
      hideDetails: true
```

So we can only display the IP.
![public-ip](https://github.com/Lissy93/dashy/assets/67486897/9d235ae7-cbe8-401e-b1c3-fa9db8a4052a)

<BR>

### Priority

Low (Nice-to-have)
