### ISSUE TITLE
[BUG] Just upgraded and it never brings up the page.

### ISSUE THREAD

**Issue by bonelifer** [Lissy93/dashy#1568]
### Environment

Self-Hosted (Docker)

### System

Firefox 125.0.3

### Version

CURRENT

### Describe the problem

Just upgraded. Was working fine before upgrade. Now it gets to the point shown in the logs below, but never brings up the page. 

### Additional info

```
  dist/js/chunk-2d225b78.f859d3b9.js        2.05 KiB         1.09 KiB
  dist/js/chunk-2ab49ff8.24cc67cd.js        1.91 KiB         0.99 KiB
  dist/js/chunk-c0f28fc6.435a99aa.js        1.91 KiB         0.94 KiB
  dist/js/chunk-d42744f4.a2a43256.js        1.90 KiB         0.98 KiB
  dist/js/chunk-7795c4fe.22642bbe.js        1.04 KiB         0.57 KiB
  dist/service-worker.js                    1.04 KiB         0.61 KiB
  dist/js/chunk-3767f013.cb3f9754.js        0.75 KiB         0.45 KiB
  dist/css/dashy.249a3490.css               272.35 KiB       33.14 KiB
  dist/css/chunk-20775648.d688965a.css      11.54 KiB        1.75 KiB
  dist/css/chunk-03c5a0ba.fdf5ccee.css      9.49 KiB         1.81 KiB
  dist/css/chunk-0248a1e9.2af758e1.css      7.32 KiB         1.32 KiB
  dist/css/chunk-4073bae0.262be67e.css      5.86 KiB         1.00 KiB
  dist/css/chunk-0c7116ec.8d663b8e.css      3.98 KiB         0.96 KiB
  dist/css/chunk-29548417.1e586604.css      3.78 KiB         0.69 KiB
  dist/css/chunk-7795c4fe.8e5b7c8e.css      3.78 KiB         0.92 KiB
  dist/css/chunk-2642eaf9.103376cf.css      3.54 KiB         0.86 KiB
  dist/css/chunk-93c6be8c.b621be85.css      3.53 KiB         0.88 KiB
  dist/css/chunk-2925d418.2f4219ad.css      3.48 KiB         0.77 KiB
  dist/css/chunk-26dbf0a4.3f521e8a.css      3.31 KiB         0.86 KiB
  dist/css/chunk-c8bd4cd0.25b1ca48.css      3.28 KiB         0.83 KiB
  dist/css/chunk-vendors.d8067ad8.css       2.74 KiB         0.83 KiB
  dist/css/chunk-f05c978e.04b75e3f.css      2.67 KiB         0.59 KiB
  dist/css/chunk-7e15df28.208bbeec.css      2.51 KiB         0.64 KiB
  dist/css/chunk-0367deae.0f98d711.css      2.48 KiB         0.67 KiB
  dist/css/chunk-4cfc5864.9357c852.css      2.48 KiB         0.57 KiB
  dist/css/chunk-14192a80.31a5db2c.css      2.38 KiB         0.58 KiB
  dist/css/chunk-49f2d909.26592934.css      2.38 KiB         0.57 KiB
  dist/css/chunk-7ba8e45c.17242d8b.css      2.30 KiB         0.55 KiB
  dist/css/chunk-7bba3126.b97a92c1.css      2.17 KiB         0.56 KiB
  dist/css/chunk-7c4d77dc.8c1925ff.css      2.06 KiB         0.49 KiB
  dist/css/chunk-781da5fb.38b3bad4.css      2.03 KiB         0.56 KiB
  dist/css/chunk-8db027b8.377fb75a.css      2.01 KiB         0.57 KiB
  dist/css/chunk-edbdb67c.0de3bd5e.css      1.94 KiB         0.56 KiB
  dist/css/chunk-e77c83e6.729d6dc8.css      1.93 KiB         0.55 KiB
  dist/loading-screen.css                   1.93 KiB         0.65 KiB
  dist/css/chunk-04659cb4.f809b0eb.css      1.86 KiB         0.50 KiB
  dist/css/chunk-08ca355a.0e2f8538.css      1.85 KiB         0.55 KiB
  dist/css/chunk-460e6092.0bcf49d9.css      1.85 KiB         0.56 KiB
  dist/css/chunk-88331f84.b825db4a.css      1.81 KiB         0.55 KiB
  dist/css/chunk-070d32ac.3ca152a5.css      1.80 KiB         0.51 KiB
  dist/css/chunk-445cc501.d9af4531.css      1.79 KiB         0.53 KiB
  dist/css/chunk-187213fc.851bbb61.css      1.78 KiB         0.52 KiB
  dist/css/chunk-180be55e.2679cb7e.css      1.77 KiB         0.53 KiB
  dist/css/chunk-6ab1f28d.dcd44809.css      1.65 KiB         0.42 KiB
  dist/css/chunk-21680640.f72d1c0d.css      1.64 KiB         0.51 KiB
  dist/css/chunk-32eb6af1.b73f2acc.css      1.59 KiB         0.48 KiB
  dist/css/chunk-4ab61964.950bd772.css      1.57 KiB         0.49 KiB
  dist/css/chunk-92c623f0.7601575f.css      1.55 KiB         0.47 KiB
  dist/css/chunk-b52460ac.d91d8d0b.css      1.49 KiB         0.47 KiB
  dist/css/chunk-4f2c58c5.e91567b0.css      1.38 KiB         0.43 KiB
  dist/css/chunk-aa9cebcc.43dd3768.css      1.36 KiB         0.41 KiB
  dist/css/chunk-7abb8001.d5057fa6.css      1.30 KiB         0.44 KiB
  dist/css/chunk-468d3a74.e7e4907a.css      1.26 KiB         0.42 KiB
  dist/css/chunk-38169201.87f602e2.css      1.16 KiB         0.46 KiB
  dist/css/chunk-15b37c0a.ebae7724.css      1.15 KiB         0.36 KiB
  dist/css/chunk-16e26d5d.97cc876a.css      1.14 KiB         0.41 KiB
  dist/css/chunk-ecec4fc4.7db7f641.css      1.12 KiB         0.36 KiB
  dist/css/chunk-0633ac20.857ad57c.css      1.04 KiB         0.34 KiB
  dist/css/chunk-bd9012c4.bbf2305d.css      1.04 KiB         0.34 KiB
  dist/css/chunk-043d9c91.9438acdb.css      0.93 KiB         0.37 KiB
  dist/css/chunk-1b35c628.f7e5ac71.css      0.90 KiB         0.31 KiB
  dist/css/chunk-4ef6dcf5.f9dd4bd8.css      0.88 KiB         0.30 KiB
  dist/css/chunk-f539423c.4b2b2c2a.css      0.88 KiB         0.33 KiB
  dist/css/chunk-3a3d0cd8.5aaf7cba.css      0.88 KiB         0.33 KiB
  dist/css/chunk-11e20f6f.070a8cfa.css      0.87 KiB         0.35 KiB
  dist/css/chunk-b7e4a5ce.df4ad987.css      0.86 KiB         0.32 KiB
  dist/css/chunk-f38e0ad2.1ea48a31.css      0.84 KiB         0.28 KiB
  dist/css/chunk-0894290e.edb63a9d.css      0.79 KiB         0.32 KiB
  dist/css/chunk-0387fd77.7aa83618.css      0.75 KiB         0.28 KiB
  dist/css/chunk-6b5de1e1.9eb66c9f.css      0.71 KiB         0.31 KiB
  dist/css/chunk-44cb61f1.025edb8a.css      0.69 KiB         0.31 KiB
  dist/css/chunk-736b2ef0.98820bcd.css      0.60 KiB         0.33 KiB
  dist/css/chunk-677c8830.df6a5b00.css      0.59 KiB         0.23 KiB
  dist/css/chunk-284f6914.58ade778.css      0.46 KiB         0.24 KiB
  dist/css/chunk-08fae180.9b2da476.css      0.46 KiB         0.22 KiB
  dist/css/chunk-0c51289a.d6684378.css      0.38 KiB         0.17 KiB
  dist/css/chunk-1e169674.98a4aa99.css      0.36 KiB         0.16 KiB
  dist/css/chunk-75cc9f4d.98a4aa99.css      0.36 KiB         0.16 KiB
  dist/css/chunk-d42744f4.f1c873fc.css      0.36 KiB         0.16 KiB
  dist/css/chunk-674ac328.d604576c.css      0.36 KiB         0.19 KiB
  dist/css/chunk-2ab49ff8.2ca1d591.css      0.36 KiB         0.16 KiB
  dist/css/chunk-6a170920.3839d02e.css      0.31 KiB         0.20 KiB
  dist/css/chunk-c0f28fc6.b67ed63a.css      0.22 KiB         0.16 KiB
  dist/css/chunk-3767f013.c9ab3ab3.css      0.11 KiB         0.10 KiB
  dist/css/chunk-cee89fa8.0918bc41.css      0.08 KiB         0.10 KiB
  dist/css/chunk-b54d81ae.61a081a9.css      0.08 KiB         0.10 KiB
  dist/css/chunk-665a1900.eeb31e13.css      0.07 KiB         0.09 KiB
  dist/css/chunk-b25c821e.f58ec558.css      0.07 KiB         0.09 KiB
  dist/css/chunk-c02e690a.ccf83212.css      0.06 KiB         0.08 KiB
  dist/css/chunk-0f886a7e.2b7bc7a4.css      0.06 KiB         0.07 KiB
  dist/css/chunk-0044633e.0e433876.css      0.00 KiB         0.02 KiB
  dist/css/chunk-7132ce43.0e433876.css      0.00 KiB         0.02 KiB
  dist/css/chunk-72e3b16c.0e433876.css      0.00 KiB         0.02 KiB
  dist/css/chunk-73f090a0.0e433876.css      0.00 KiB         0.02 KiB
  Images and other types of assets omitted.
 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
 ```     
```
---
services:
    dashy:
        ports:
            - '4000:80'
        volumes:
            - ./data/config.yml:/app/user-data/conf.yml
            - ./data/item-icons:/app/public/item-icons
        container_name: dashy

    # Specify restart policy
        restart: unless-stopped

        image: 'lissy93/dashy:latest'
        environment:
            - NODE_ENV=production
            - UID=1000
            - GID=1000

    # Set the deunhealth label
        labels:
            - deunhealth.restart.on.unhealthy=true

    # Configure healthchecks
        healthcheck:
            test: ['CMD', 'node', '/app/services/healthcheck']
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s
```
### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by DeltaTangoLima** [comment]
Very similar issue - just upgraded Docker image and all I get is the default start page (screenshot) - not my configured page.

Docker logs state that config is valid, and I've confirmed my bound volume for `conf.yml` is indeed mapped correctly to `/app/public/conf.yml` inside the running container.

Rolling back to the previous image works fine.

<img width="802" alt="Screenshot 2024-05-04 at 09 44 32" src="https://github.com/Lissy93/dashy/assets/53992354/b0763f47-1ce7-4aef-8eba-f1890029e5b1">

**Comment by bonelifer** [comment]
I dont get that as it literally reports healthy in portainer. But my browser says it can't connect.

**Comment by bonelifer** [comment]
Firefox and Chromium both give the site can not be found message.

**Comment by bonelifer** [comment]
I had to roll back to 2.1.0/2.1.2, to get dashy to load(older one trying to get my current yml to load), but now it wont load my config.yml, have reset local and rebuild from the app. Just end up with defaut config. Would be nice to have local in browser import of the config.yml. I wish I could remember the cloud info for my last backup.

```
---
services:
    dashy:
        ports:
            - '4000:80'
        volumes:
            - ./data/config.yml:/app/user-data/conf.yml
            - ./data/item-icons:/app/public/item-icons
        container_name: dashy

    # Specify restart policy
        restart: unless-stopped

        image: 'lissy93/dashy:2.1.0'
        environment:
            - NODE_ENV=production
            - UID=1000
            - GID=1000

    # Configure healthchecks
        healthcheck:
            test: ['CMD', 'node', '/app/services/healthcheck']
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s
```
