### ISSUE TITLE
[FEATURE_REQUEST] Generalized display control for user/group/roles

### ISSUE THREAD

**Issue by twsouthwick** [Lissy93/dashy#1582]
### Is your feature request related to a problem? If so, please describe.

Currently, group/roles display management has 'keycloak' in the name. However, general OIDC is supported now that has group/role information but is not keycloak.

### Describe the solution you'd like

I think the current `displayData` sections can be replaced with a generalized node (names pending) that would look like this:

```yml
sections:
- name: Getting Started
  icon: fas fa-rocket
  display:
    - type: user
      name: user-name
      display: true|false
    - type: group
      name: group-name
      display: true|false
    - type: role
      name: role-name
      display: true|false
    - type: guest
      display: true|false
```

I have this working locally to explore the idea, but wanted to check on if this was the right direction.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

Yes!
