### ISSUE TITLE
[BUG] Minimal view as starting view not using correct theme

### ISSUE THREAD

**Issue by DBLouis** [Lissy93/dashy#1604]
### Environment

Self-Hosted (Docker)

### System

Firefox 125, Ubuntu 23.10, Docker 26.1.3

### Version

3.1.0

### Describe the problem

I want to have the minimal view as starting view, so I set the environment variable `VUE_APP_STARTING_VIEW` to `minimal`. The starting view is indeed the minimal view but **the theme I set in my config is not set, it uses the default one instead**.

```
services:
  dashy:
    image: ghcr.io/lissy93/dashy:3.1.0@sha256:b9929261cbf9353f8aee2c63b35e53aafc4951aa9923c1244242de7c1251f49f
    container_name: dashy
    networks:
      - traefik
    volumes:
      - ./conf.yml:/app/user-data/conf.yml
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ENV=production
      - VUE_APP_STARTING_VIEW=minimal
    restart: 'unless-stopped'
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges
    labels:
      traefik.enable: 'true'
      traefik.http.routers.dashy.entrypoints: 'http'
      traefik.http.routers.dashy.rule: 'Host(`www.example.com`)'
      traefik.http.middlewares.dashy-https-redirect.redirectscheme.scheme: 'https'
      traefik.http.routers.dashy.middlewares: 'dashy-https-redirect'
      traefik.http.routers.dashy-secure.entrypoints: 'https'
      traefik.http.routers.dashy-secure.rule: 'Host(`www.example.com`)'
      traefik.http.routers.dashy-secure.tls: 'true'

networks:
  traefik:
    external: true
```

```
---
pageInfo:
  title: Title
  description: Description
  navLinks:
  - title: GitHub
    path: https://github.com/Lissy93/dashy
  - title: Documentation
    path: https://dashy.to/docs

appConfig:
  theme: nord
  layout: vertical
  iconSize: large
  language: fr
  disableConfiguration: true
  defaultOpeningMethod: newtab
  statusCheck: true
  hideComponents:
    hideSettings: true
  preventLocalSave: true
  preventWriteToDisk: true

sections:
  <omitted>
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
