### ISSUE TITLE
[BUG] Keycloak authentication breaks Dashy

### ISSUE THREAD

**Issue by edememinov** [Lissy93/dashy#1613]
### Environment

Self-Hosted (Docker)

### System

Docker on Unraid 6.12.10

### Version

3.1.1

### Describe the problem

When enabling Keycloak authentication Dashy stops loading and show the "It looks like something's gone wrong..."-screen.

When enableKeycloak is set to false, Dashy works as expected. (Although without Keycloak)
![Screenshot 2024-06-06 194647](https://github.com/Lissy93/dashy/assets/7499362/08477efa-241e-4987-aacc-6faa19630050)

In Traefik the following docker labels are set:
```yaml
corsheaders:
        headers:
            accesscontrolallowmethods: [GET,OPTIONS,PUT]
            accesscontrolalloworiginlist: ["https://domain.com", "https://auth.domain.com"]
            accesscontrolmaxage: 100
            addvaryheader: true
```

This is the dashy config:

```yaml
  auth:
    enableGuestAccess: false
    users: []
    enableOidc: false
    #oidc: {}
    enableHeaderAuth: false
    headerAuth:
      userHeader: REMOTE_USER
      proxyWhitelist: []
    enableKeycloak: true
    keycloak:
      serverUrl: https://auth.domain.com
      realm: example-realm
      clientId: example-client-id
      legacySupport: false
```

### Additional info

Dashy is being hosted on a domain without a subdomain.

Dashy works with keycloak on one specifc browser instance. I am able to login and after that Dashy works as expected.
On other browsers (and devices) sadly I get the error above. I assume that if I clear my cookies that the single working browser will also show the same error.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by edememinov** [comment]
Found a solution after a lot of trial and error. 

If anyone ever runs into this adding domain and subdomain to the CSP header should work. 

This is what it looks like in Traefik:
```yaml
http:
  middlewares:
    corsheaders:
            headers:
                accesscontrolallowmethods: [GET,OPTIONS,PUT]
                accesscontrolalloworiginlist: ["https://jesdem.top", "https://auth.jesdem.top"]
                accesscontrolmaxage: 100
                addvaryheader: true
                contentSecurityPolicy: "frame-ancestors 'self' *.domain.com domain.top;"
                accesscontrolallowheaders: "*"

```
