### ISSUE TITLE
Dashy 3.1.1 baremetal with keycloak doesn't work[BUG] <title>

### ISSUE THREAD

**Issue by juantxorena** [Lissy93/dashy#1625]
### Environment

Self-Hosted (Bare Metal)

### System

debian 12

### Version

3.1.1

### Describe the problem

This is different than most of the other bugs, since the other ones usually relate to docker.

As the title says, dashy 3.1.1 doesn't work with the latest keycloak version (25.0.1). It redirects to the login page, and after login, I get the black screen of death (with "It looks like something's gone wrong..." etc). When disabling keycloak auth it works as expected. This happened after upgrading dashy from a very old version (2.x).

My setup: dashy behind nginx in a LXC container (in proxmox). Keycloak in another LXC container in the same machine.

Unfortunately the browser console doesn't say anything:
![image](https://github.com/Lissy93/dashy/assets/5948336/40f1a41c-2c4d-48f0-9be9-c824e7569a45)

The strange thing is that I actually get a token, so I assume that the keycloak config is ok:
![image](https://github.com/Lissy93/dashy/assets/5948336/282a8682-b76f-4551-b236-0cc56f329a39)

### Additional info

dashy conf:

```
pageInfo:
  title: Dashy
  description: Willkommen in der Okenstr. 2
  navLinks:
    - title: GitHub
      path: https://github.com/Lissy93/dashy
    - title: Documentation
      path: https://dashy.to/docs
appConfig:
  theme: default
  auth:
    enableKeycloak: true
    keycloak:
      serverUrl: https://auth.lan:8443/
      realm: zuhause
      clientId: dashy
  layout: auto
  iconSize: medium
  statusCheck: true
  disableConfiguration: true
  hideComponents:
    hideNav: true
    hideSearch: true
    hideFooter: true
    hideSettings: true
  language: en
sections:
  - name: Apps
    displayData:
      sortBy: default
      rows: 1
      cols: 5
      collapsed: false
      hideForGuests: true
    items:
      - title: Rezepte
        icon: tandoorrecipes.png
        url: https://rezepte.lan
        target: newtab
        id: 0_404_rezepte
        statusCheckAllowInsecure: true
      - title: Projekte
        icon: vikunja.png
        url: https://projekt.lan?redirectToProvider=true
        target: newtab
        id: 1_404_projekte
        statusCheckAllowInsecure: true
      - title: Smart Home
        icon: openhab.png
        url: https://openhab.lan/oauth2/start?rd=/
        target: newtab
        id: 2_404_smarthome
        statusCheckAllowInsecure: true
      - title: Cloud
        icon: nextcloud.png
        url: https://nextcloud.lan/apps/sociallogin/custom_oidc/keycloak
        target: newtab
        statusCheckAllowInsecure: true
        id: 3_404_cloud

```

nginx conf:

```
server {
    listen                          80;
    listen                          [::]:80;
    server_name                     zuhause.lan;
    return 301                      https://$server_name$request_uri;
}

server {
    #listen 80;
    listen 443 ssl http2;
    #listen 8443 ssl;

    ssl_certificate /etc/ssl/certs/dashy-bundle.crt;
    ssl_certificate_key /etc/ssl/private/dashy.key;
    #access_log /var/log/nginx/access.log;
    #error_log /var/log/nginx/error.log;
    server_name zuhause.lan;

    add_header X-Frame-Options SAMEORIGIN always;

    location / {
        add_header 'Access-Control-Allow-Origin' 'https://zuhause.lan' always;
        proxy_set_header Host $http_host;
        proxy_pass http://localhost:4000/;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by classic-mcfly** [comment]
Hello, same issue here. After downgrading Keycloak to v24 everything is working as expected.

**Comment by veniplex** [comment]
Same issue for me. I use:
- Dashy v3.1.1
- Keycloak v25.0.1

I get the same result. Auth seems to work on Keycloak side, because a session is created and the Keycloak logs show nothing. But Dashy shows this:

![image](https://github.com/Lissy93/dashy/assets/19841573/5b809fd0-d999-4157-b0cd-da69c386d601)

**Comment by juantxorena** [comment]
Since I'm not using docker, I cannot really roll back keycloak to a previous version (I could, but it's too much work). Is there any way I can help testing and fixing this bug?

**Comment by veniplex** [comment]
@juantxorena I assume that Keycloak v25.0.0 introduced some breaking changes, so that the implementation in Dashy needs some adjustments. For reference: https://www.keycloak.org/docs/latest/release_notes/index.html

Maybe it is worth noting this in the installation instructions / troubleshooting section / readme file... until it is updated.

**Comment by veniplex** [comment]
@juantxorena Did you try to use the [OIDC method](https://github.com/Lissy93/dashy/blob/master/docs/authentication.md#oidc) in the meantime? Maybe this works with Keycloak... I haven't tried it and I can't at the moment, because I removed Dashy for now.

**Comment by MioOgbeni** [comment]
Hi, I also encountered with this error. Last week we upgraded to Keycloak 25.X.X and after that login into Dashy stopped working. It definitely looks like some issue with the deprecation of the `keycloak-js` library in the currently used version.

I also tried your @veniplex recommendation, and it seems to work after switching to generic OIDC auth.

Will anyone try to upgrade the `keycloak-js` library, or should I try it in PR?

**Comment by nOw-Ay** [comment]
Hello,

now that general OIDC Authentication is available, what benefit is there to use `keycloak-js` ?

The library is supposed to help developers to implement Keycloak-based Auth in their solution. Now that a general solution is available, don't you think that Keycloak Auth with `keycloak-js` be deprecated ?

**Comment by CrazyWolf13** [comment]
@nOw-Ay 

I think that would a good decision, as keycloak allows oidc, however if we'd really deprecate keycloak( as it requires a lot of maintenance and there are often many problems with keycloak) we'd have to communicate and plan this out well, as I think a lot of people use keycloak, so we can't just remove it.

@Lissy93 What's your opinion on this?

**Comment by veniplex** [comment]
@nOw-Ay As far as I understand, there are Keycloak-specific features available within `keycloak-js`. However, if Dashy is not using these features, a secure OIDC-implementation should be enough for most of the providers.

@CrazyWolf13 Since Dashy doesn't work with the newest version of Keycloak, the most part is already done 😆... I think an update of the documentation would be enough. Just refer to the OIDC implementation for now.

**Comment by viperfan7** [comment]
I'm having trouble with getting the OIDC implementation working, specifically, getting a whole lot of "Invalid scopes" errors, and I can't find any documentation as to what might be causing it

**Comment by HolyMacarony** [comment]
i also cannot figure out how to use the hideForKeycloakUsers  feature with normal OIDC user. does anyone have a working config, which enables the roles- features?

**Comment by lissy93** [comment]
Sorry that I'd been so inactive on this :/

I've re-written the Keycloak functionality since this issue was opened, and tested it as best I can in a range of different systems and configurations, so I am quite confident that it is fixed now (see also https://github.com/lissy93/dashy/issues/1714#issuecomment-4468138810).

I've updated the KC docs for the complete setup too: https://dashy.to/docs/authentication/keycloak

<details>

<summary>keycloak setup summary</summary>

### Step 1: Start Keycloak (if not already done)

Here's a sample [`docker-compose.yml`](https://github.com/user-attachments/files/27861631/docker-compose.yml) - just make sure in same network as Dashy. Or use docker command similar to the one below:

```
docker run -d \
  -p 9100:8080 \
  --name keycloak \
  -e KEYCLOAK_ADMIN=kc-admin \
  -e KEYCLOAK_ADMIN_PASSWORD=KeycloakAdmin2026! \
  quay.io/keycloak/keycloak:25.0 start-dev
```

### Step 2: Configure Keycloak 

By following [these steps](https://dashy.to/docs/authentication/keycloak#2-configure-keycloak), similar to the screen recording below

https://github.com/user-attachments/assets/12b6a596-1ec6-453a-9ff7-d4e2c3aa69f7

### Step 3: Add keycloak to dashy config

Check the [docs](https://dashy.to/docs/authentication/keycloak#3-enabling-keycloak-in-dashy) for all options, but basically should look something like this:

```yaml
appConfig:
  theme: catppuccin
  layout: masonry
  iconSize: medium
  disableConfigurationForNonAdmin: true
  auth:
    enableKeycloak: true
    keycloak:
      serverUrl: http://localhost:9100
      realm: dashy
      clientId: dashy
      adminRole: dashy-admin
```

### Step 4: Test it out

Should all be working now, and to access Dashy, your config, or any endpoints, you'll first be redirected to the Keycloak login page to authenticate. You can then setup [groups and roles](https://dashy.to/docs/authentication/keycloak#4-groups-and-roles) to choose which stuff is visible to which users.

If it doesn't work, there will (hopefully) be error messaging in the console which will tell you why. If not, you can check the [troubleshooting keycloak](https://dashy.to/docs/authentication/keycloak#troubleshooting-common-keycloak-issues) docs, or just give up and cry.

</details>

But I will say (maybe I was just being thick) but Keycloak is a proper pain to get working. It's about 20 minutes of setup through their horrible UI, and then another hour of debugging realms, roles, users, clients, origins, headers, CSPs, redirect URIs, etc 😅
