### ISSUE TITLE
[FEATURE_REQUEST]  Disable configuration for Keycloak user without a certain role

### ISSUE THREAD

**Issue by edememinov** [Lissy93/dashy#1627]
### Is your feature request related to a problem? If so, please describe.

Everyone who visits my dashboard can change the configuration of my Dashy instance and edit the dashboard.

The boolean "disableConfigurationForNonAdmin" prevents this a part of this from hapening, but if keycloak is used then this option doesn't work. Unless I create a built-in auth admin user.

### Describe the solution you'd like

A another setting that contains a list of keycloak (or other OIDC) roles/groups that are allowed to save to disk or edit the configuration.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

Maybe

**Comment by alkaldt** [comment]
I tried the role mapper in keycloak but it didn't work.
😭

**Comment by lissy93** [comment]
This is supported now :)
See: https://dashy.to/docs/authentication/keycloak

```yaml
appConfig:
  disableConfigurationForNonAdmin: true # set this so non-admins cannot do admin things
  auth:
    enableKeycloak: true
    keycloak:
      serverUrl: 'http://localhost:9100'
      realm: 'dashy'
      clientId: 'dashy'
      adminRole: 'dashy-admin'   # only users with this role can edit/save config
```
