### ISSUE TITLE
[QUESTION] Granular Access?

### ISSUE THREAD

**Issue by lue30499** [Lissy93/dashy#165]
Hi, Love Dashy!

I searched through the docs,,, I might be blind though. Is there a way to give granular access to users?
Such as some users see some "bookmarks" but not others?

Regards,
Lue-

**Comment by Lissy93** [comment]
Hey, thanks for your question, at the moment, no is not yet possible. But it's a good idea, so I will add it to the todo list. Just so I understand, you'd like it to be possible have some sections only visible to specific users, right? I think that should be pretty straigtforward :)

**Comment by lue30499** [comment]
Hi,

If possible, individual "bookmarks" and sections?

I am personally used to how [rmountjoy92/DashMachine](https://github.com/rmountjoy92/DashMachine) (unmaintained now) worked.
See below where two users, two roles , two groups and two "bookmarks" are define.
Obviously if you can/want implement it, do it however you see fit!

<img width="661" alt="Screen Shot 2021-08-16 at 8 30 25 pm" src="https://user-images.githubusercontent.com/63104612/129550511-3c4da5e4-cd7f-45d3-82d9-26c3403db769.png">


Regards,
Lue-

**Comment by Lissy93** [comment]
Heya, I've implemented this in PR #171 :)

**Comment by Lissy93** [comment]
You under `displayDaya` for a given section, you can now use the following properties to control the sections visibility on a per-user basis.
- `hideForUsers` - Section will be visible to all users, except for those specified in this list
- `showForUsers` - Section will be hidden from all users, except for those specified in this list
- `hideForGuests` - Section will be visible for logged in users, but not for guests

<details>
	<summary>Examples</summary>
	<p>
	
```yaml
- name: Code Analysis & Monitoring
  icon: fas fa-code
  displayData:
    cols: 2
    hideForUsers: [alicia, bob]
  items:
    ...
```

```yaml
- name: Deployment Pipelines
  icon: fas fa-rocket
  displayData:
    hideForGuests: true
  items:
    ...
```

</p>
</details>

Hope that helps :)
