### ISSUE TITLE
[BUG] Change configuration pannel won't show up

### ISSUE THREAD

**Issue by volrod64** [Lissy93/dashy#1652]
### Environment

Self-Hosted (Docker)

### System

Docker-compose / Debian 12 / Firefox 128.0.3

### Version

3.1.1

### Describe the problem

On your demo https://demo.dashy.to/#
When clicking into " enter edit mode " then " change configuration " you have a pannel coming up
![image](https://github.com/user-attachments/assets/7ab8894b-869b-4b7d-892c-72464e1513f8)
Well, I don't.
![image](https://github.com/user-attachments/assets/25040aa0-5824-41ba-991c-d2c1a1942100)
It's in the bottom of the page and hardstuck. If i click to drag it to the top, i reach a border limit.
I don't have any custom CSS, just use Glass 2 theme.

### Additional info

Docker compose look like 
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
      - /docker/appdata/dashy/config:/app/public
    ports:
      - 4000:8080
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
    

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by volrod64** [comment]
Okay, the bug is coming with Glass 2 theme. I changed to default one and everything look fine ..
But I love glass 2 lol

**Comment by hockwill** [comment]
When swapping the Dashy theme Colorful to Glass2 it is still functioning as expected. I was unable to duplicate this bug with the information provided. Using dashy:latest behind nginx reverse proxy to Firefox 128.0.
The Dev demo link seems to have the glass2 theme. Does the same thing happen there for you? https://dev.dashy.to/

I see in your compose you have the outside container directory for holding your config mounted to `/app/public` for Dashy 3 it is supposed to be `/app/user-data` per https://github.com/Lissy93/dashy/discussions/1529 .

**Comment by volrod64** [comment]
> When swapping the Dashy theme Colorful to Glass2 it is still functioning as expected. I was unable to duplicate this bug with the information provided. Using dashy:latest behind nginx reverse proxy to Firefox 128.0. The Dev demo link seems to have the glass2 theme. Does the same thing happen there for you? https://dev.dashy.to/
> 
> I see in your compose you have the outside container directory for holding your config mounted to `/app/public` for Dashy 3 it is supposed to be `/app/user-data` per #1529 .

Same bug on the dev.dashy.to .. Sound like a " me " problem.

**Comment by CrazyWolf13** [comment]
Try turning off any extensions and opening the page in a private window/ different browser. This really sounds like an issue on your end.

**Comment by volrod64** [comment]
> When swapping the Dashy theme Colorful to Glass2 it is still functioning as expected. I was unable to duplicate this bug with the information provided. Using dashy:latest behind nginx reverse proxy to Firefox 128.0. The Dev demo link seems to have the glass2 theme. Does the same thing happen there for you? https://dev.dashy.to/
> 
> I see in your compose you have the outside container directory for holding your config mounted to `/app/public` for Dashy 3 it is supposed to be `/app/user-data` per #1529 .

Hi, 
I did the change to my docker compose, reload it ... lost everything.
Thanksfully, I had a backup file 
Here my actual docker compose
```
  dashy:
    image: lissy93/dashy:latest
    container_name: Dashy
    volumes:
      - /docker/appdata/dashy/config:/app/user-data
    ports:
      - "4000:8080"
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped

```
![image](https://github.com/user-attachments/assets/7dc6c5e3-9db4-4363-8655-fc0ba700290a)

I do have a conf.yml in  /docker/appdata/dashy/config 
```
/docker/appdata/dashy/config# ls -lhrt
total 8,0K
-rw-r--r-- 1 seb seb 7,4K 31 juil. 16:04 conf.yml
```

With a bunch of links and all my stuff in it.

May I ask for help ? Thanks :)

**Comment by CrazyWolf13** [comment]
Can you make sure the permissions are correct and UID and GUI 1000 has access, otherwise recreate the container without that.

As Dashy changed from running as root to non root.

**Comment by volrod64** [comment]
```
  image: lissy93/dashy:latest
  container_name: Dashy
  volumes:
    - /docker/appdata/dashy/config:/app/user-data
  ports:
    - "4000:8080"
  environment:
    - NODE_ENV=production
  restart: unless-stopped
  
  
  root@netflix:/apps# ls -lhrt /docker/appdata/dashy/config
total 8,0K
-rw-r--r-- 1 seb seb 7,4K 31 juil. 16:04 conf.yml

```
conf got all my stuff.
Still the same error after doing docker-compose up -d
(I also tried to stop the container only, then start it again)

Thanks for taking time to help me, appreciate it !
