### ISSUE TITLE
[QUESTION] I updated from 2.x to 3 and my config is gone, how do I get it back?

### ISSUE THREAD

**Issue by rpgdev** [Lissy93/dashy#1680]
### Question

I just did a pull of the new version, at first I couldn't access it but figured that out from the now recommended docker-compose file. Unfortunately, after dashy started up my old config is gone, how can I get it back? I did not change the .conf mapping so I'm not using a directory I'm still mapped to the single .conf file.

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by rpgdev** [comment]
@HollisTech where did you get that? This is the sample in the docs still pointing at the conf file:
```yaml
---
version: "3.8"
services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: Dashy
    # Pass in your config file below, by specifying the path on your host machine
    # volumes:
      # - /root/my-config.yml:/app/user-data/conf.yml
    ports:
      - 4000:8080
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
```

How can I change the compose file so that it grabs my old config?

**Comment by CrazyWolf13** [comment]
@HollisTech 

That's not fully correct, while it's now _possible_ to use folder to folder mounts, which are most of the time a better experience it's not a must..

@rpgdev  

Create a new folder and move the old config file into the folder and rename to conf.yml
```bash
mkdir /root/dashy
mv /root/my-config.yml /root/dashy/conf.yml
```

```yml
version: "3.8"
services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: Dashy
    # Pass in your config file below, by specifying the path on your host machine
    # volumes:
      # - /root/dashy:/app/user-data
    ports:
      - 4000:8080
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
```

**Comment by CrazyWolf13** [comment]
@HollisTech  
A little bit off topic, but awesome top ps1 you wrote!

Looks amazing for it's size 👏

**Comment by rpgdev** [comment]
@CrazyWolf13 thanks but wouldn't that mean that the conf file I'm mapping in my own compose file should've been recognized?
```yaml
---
services:
  dashy:
    image: lissy93/dashy
    container_name: dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - /mnt/docker/apps/dashy/config.yml:/app/public/conf.yml
      # - /mnt/docker/apps/dashy/icons:/app/user-data/item-icons/
    ports:
      - 4000:8080
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      - UID=${PUID}
      - GID=${PGID}
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - network1
networks:
  network1:
    name: applications
    external: true
volumes:
  dashy_data:
```
