### ISSUE TITLE
[BUG] issues with getting pihole stat widgets to work

### ISSUE THREAD

**Issue by back-lacking** [Lissy93/dashy#1681]
### Environment

Self-Hosted (Docker)

### System

Debian 12, Docker 27.1.1

### Version

3.1.1

### Describe the problem

So I'm currently trying to setup the widgets for Pihole in Dashy. I added the widgets in my conf file, provided my API key for all the Pihole widgets, and added the Traefik CORS headers from the Dashy documentation to my Pihole's compose file. Looking at Firefox's dev tools, I see that I'm getting a weird network error and errors about missing CORS headers, despite me adding it to my Pihole Compose file and seeing the cors headers middleware in my Traefik dashboard. Relevant configs and screenshots in next section. 

### Additional info

![image](https://github.com/user-attachments/assets/04d0fdea-0f46-4bcc-b8d8-807153829e5d) the errors in firefox
![image](https://github.com/user-attachments/assets/a574fab7-cf34-4277-b645-05fc5a26cb37) the network error expanded
```yaml
      - traefik.http.middlewares.pihole-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT
      - traefik.http.middlewares.pihole-cors.headers.accessControlAllowCredentials=true
      - traefik.http.middlewares.pihole-cors.headers.accesscontrolallowheaders=https://home.local.inever.cyou
      - traefik.http.middlewares.pihole-cors.headers.accesscontrolalloworiginlist=https://home.local.inever.cyou
      - traefik.http.middlewares.pihole-cors.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.pihole-cors.headers.addvaryheader=true
```
the cors headers i added to my piholes compose file. `home.local.inever.cyou` is the url for the dashy instance. 

```yaml
    widgets:
      - type: pi-hole-stats
        options:
          hostname: https://pihole.local.inever.cyou
          apiKey: apikey
        id: 0_1168_piholestats
      - type: pi-hole-top-queries
        options:
          hostname: https://pihole.local.inever.cyou
          apiKey: apikey
        id: 1_1168_piholetopqueries
      - type: pi-hole-traffic
        options:
          hostname: https://pihole.local.inever.cyou
          apiKey: apikey
        id: 2_1168_piholetraffic
```
the part of my config file containing the pihole widgets

![image](https://github.com/user-attachments/assets/7786bc55-b12e-4c33-81c8-1e2a4628a008) the traefik dashboard 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
