### ISSUE TITLE
[FEATURE_REQUEST] Expose deployment volume mounts in helm chart values file

### ISSUE THREAD

**Issue by bassplay3r** [Lissy93/dashy#1701]
### Is your feature request related to a problem? If so, please describe.

I would like to consume your chart by wrapping your chart in mine using helm dependencies and configure how the deployment mounts the page configmaps using the helm chart's values file.

### Describe the solution you'd like

Is there some way this code can be abstracted to the helm chart's values file

```
volumeMounts:
            {{ if .Values.static.enabled }}
            - mountPath: /app/user-data/conf.yml
              subPath: conf.yml
              name: {{ include "dashy.fullname" . }}-conf
            - mountPath: /app/user-data/conf2.yml
              subPath: conf2.yml
              name: {{ include "dashy.fullname" . }}-conf
            - mountPath: /app/user-data/conf3.yml
              subPath: conf3.yml
              name: {{ include "dashy.fullname" . }}-conf
            - mountPath: /app/user-data/conf4.yml
              subPath: conf4.yml
              name: {{ include "dashy.fullname" . }}-conf
            {{ end }}
```

```
configMap:
            name: {{ include "dashy.fullname" . }}-conf
            items:
              - key: conf
                path: conf.yml
              - key: conf2
                path: conf2.yml
              - key: conf3
                path: conf3.yml
              - key: conf4
                path: conf4.yml
```

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

Maybe
