### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Fleench** [Lissy93/dashy#1714]
### Environment

Self-Hosted (Docker)

### System

Arch based Chromium version 129.0.6668.101

### Version

3.1.1

### Describe the problem

When attempting to authenticate via Keycloak I get passed the sign in screen and then a 401 error is thrown blocking me from Keycloak

### Additional info

# Dashy Auth Config
```
  auth:
    enableKeycloak: true
    keycloak:
      serverUrl: 'https://account.flench.me'
      realm: 'Nebulee'
      clientId: 'keycloak-d'
```
# Console Logs
```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'private-state-token-redemption'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'private-state-token-issuance'.
Error with Permissions-Policy header: Unrecognized feature: 'browsing-topics'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'private-state-token-redemption'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'private-state-token-issuance'.
Error with Permissions-Policy header: Unrecognized feature: 'browsing-topics'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'private-state-token-redemption'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'private-state-token-issuance'.
Error with Permissions-Policy header: Unrecognized feature: 'browsing-topics'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'private-state-token-redemption'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'private-state-token-issuance'.
Error with Permissions-Policy header: Unrecognized feature: 'browsing-topics'.
KeycloakAuth.js:28 
        
        
       POST https://account.flench.me/realms/Nebulee/protocol/openid-connect/token 401 (Unauthorized)
C @ keycloak.mjs:776
(anonymous) @ keycloak.mjs:255
Promise.then
h @ keycloak.mjs:254
Promise.then
(anonymous) @ keycloak.mjs:319
Promise.then
(anonymous) @ keycloak.mjs:316
(anonymous) @ KeycloakAuth.js:28
value @ KeycloakAuth.js:27
f @ KeycloakAuth.js:87
(anonymous) @ main.js:73
Promise.then
56d7 @ main.js:65
l @ bootstrap:89
0 @ dashy.432463d9.js:1
l @ bootstrap:89
a @ bootstrap:45
(anonymous) @ bootstrap:267
(anonymous) @ dashy.432463d9.js:1
Show 5 more frames
Show less
CoolConsole.js:11 
⚠️ Warning ⚠️ Failed to authenticate with Keycloak This is likely not an issue with Dashy, but rather your configuration.If you think it is a bug, please open a ticket on GitHub: https://git.io/JukXk
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by fussel132** [comment]
Not sure if this is 100% related but I also have issues getting Keycloak to work. Keycloak works fine with other services but it just won't work with Dashy. However in my case there is just one (browser) console entry with "Failed to authenticate with Keycloak", the POST to the token endpoint returns 200 and Keycloak lists an active session.
I can also see IDENTITY/SESSION cookies for the auth domain Keycloak runs behind but no cookies for the domain pointing to Dashy, is this intended?

**Comment by CrazyWolf13** [comment]
https://github.com/Lissy93/dashy/issues/1625

Seems like keycloak has been broken since some longer time.

Honestly I wouln't think this will get fixed in any near future, looking at the state of this project behind the curtains and the owner of this repo.

**Comment by nOw-Ay** [comment]
One solution is to use OIDC auth which (for now) still works, please see take a look at [my answers to this issue](https://github.com/Lissy93/dashy/issues/1747#issuecomment-2481155989).

**Comment by HolyMacarony** [comment]
but the roles features like hideForKeycloakUsers dont work anymore for OIDC. Or du you have a working config?

**Comment by lissy93** [comment]
I was just doing some testing on another ticket which was specific to keycloak, and as part of doing that i had to setup keycloak in front of dashy.

It was a indeed bit of a pain to get running (party because the Keycloak UI is horrible, and partly because I am noob).

I got there in the end, so I'll drop the steps I took, the config I used, and a quick screen recording of the Keycloak part below, in case it's helpful to anyone... (but really, wouldn't reccomend keycloak, it's horrible).

- Sample [docker-compose.yml](https://github.com/user-attachments/files/27861631/docker-compose.yml)
- Sample [conf.yml](https://github.com/user-attachments/files/27861628/conf.yml)
- [Screen recording](https://storage.googleapis.com/as93-screenshots/dashy/keycloak-dashy-setup.mp4) of full walk through of configuring keycloak

---

# Full guide to Setting up Keycloak in front of Dashy

## Step 1: Start Keycloak and Dashy (if not already done)

In this example, i'm using `lissy93/dashy:4.1.0` on `4000`, and `quay.io/keycloak/keycloak:25.0` on `9100`.
I also passed in this .env: `KEYCLOAK_ADMIN=kc-admin` and `KEYCLOAK_ADMIN_PASSWORD=KeycloakAdmin2026!`

So this was the docker-compose:

```yaml
name: dashy-keycloak

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command:
      - start-dev
      - --http-port=9100
      - --hostname-strict=false
      - --health-enabled=true
    restart: unless-stopped
    ports:
      - "9100:9100"
      - "4000:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HEALTH_ENABLED: "true"
    healthcheck:
      test: ["CMD-SHELL", "timeout 2 bash -c '</dev/tcp/127.0.0.1/9100'"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 15

  dashy:
    image: lissy93/dashy:4.1.0
    network_mode: service:keycloak
    restart: unless-stopped
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 8080
    volumes:
      - ./user-data:/app/user-data
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/healthz >/dev/null 2>&1"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 15

volumes:
  keycloak-data:
```

## Step 2: Configure Keycloak

Here's a screen recording of the steps outline below:

https://github.com/user-attachments/assets/12b6a596-1ec6-453a-9ff7-d4e2c3aa69f7

Or, an [example bash script](https://github.com/user-attachments/files/27861666/bootstrap.sh) to do this programatically. Wouldn't reccomend for production, but very handy for dev/testing :)

### Create the Keycloak realm
1. Open `http://localhost:9100`.
2. Click **Administration Console**.
3. Log in as `kc-admin`.
4. Open the realm selector in the top-left.
5. Click **Create realm**.
6. Set **Realm name** to `dashy`.
7. Click **Create**.

### Allow Dashy's local origin
1. In the `dashy` realm, open **Realm settings**.
2. Open **Security defenses**.
3. Open **Headers**.
4. Clear **X-Frame-Options**.
5. Set **Content-Security-Policy** to:

```text
frame-src 'self' http://localhost:4000 http://127.0.0.1:4000; frame-ancestors 'self' http://localhost:4000 http://127.0.0.1:4000; object-src 'none';
```

6. Click **Save**.

### Create the Dashy client
1. In the `dashy` realm, open **Clients**.
2. Click **Create client**.
3. Set **Client type** to `OpenID Connect`.
4. Set **Client ID** to `dashy`.
5. Click **Next**.
6. Turn **Client authentication** off.
7. Leave **Standard flow** on.
8. Leave **Direct access grants** on or off; Dashy does not require it.
9. Click **Next**.
10. Set **Valid redirect URIs** to:
    - `http://localhost:4000/*`
    - `http://127.0.0.1:4000/*`
11. Set **Valid post logout redirect URIs** to:
    - `http://localhost:4000/*`
    - `http://127.0.0.1:4000/*`
12. Set **Web origins** to:
    - `http://localhost:4000`
    - `http://127.0.0.1:4000`
13. Click **Save**.


### Add the realm-role mapper

Dashy uses `adminRole: dashy-admin` in `user-data/conf.yml`. For server-side admin checks to work, Keycloak must include realm roles in the ID token

1. Open **Clients**
2. Click the `dashy` client
3. Open **Client scopes**
4. Click the dedicated scope row, usually named `dashy-dedicated`
5. Click **Add mapper**
6. Click **By configuration**
7. Select **User Realm Role**
8. Set **Name** to `dashy-realm-roles`
9. Set **Token Claim Name** to `realm_access.roles`
10. Turn **Multivalued** on
11. Turn **Add to ID token** on
12. Turn **Add to access token** on
13. Turn **Add to userinfo** on
14. Click **Save**

### Create the Dashy admin role
1. In the `dashy` realm, open **Realm roles**
2. Click **Create role**
3. Set **Role name** to `dashy-admin`
4. Click **Save**

### Create test users

Create an admin user:
1. Open **Users**
2. Click **Add user**
3. Set **Username** to `keycloak-admin`
4. Set **Email verified** to on
5. Set **First name** to `Keycloak`
6. Set **Last name** to `Admin`
7. Click **Create**
8. Open the **Credentials** tab
9. Click **Set password**
10. Set a password, turn **Temporary** off, and save it
11. Open the **Role mapping** tab
12. Click **Assign role**
13. Filter by realm roles, select `dashy-admin`, and assign it

Create a normal user:
1. Open **Users**
2. Click **Add user**
3. Set **Username** to `keycloak-user`
4. Set **Email verified** to on
5. Set **First name** to `Keycloak`
6. Set **Last name** to `User`
7. Click **Create**
8. Open the **Credentials** tab
9. Set a non-temporary password
10. Do not assign `dashy-admin`

### Keycloak now all configured

If you like, you can export a backup of your configured dashy realm, with something like:

```bash
docker compose run --rm --no-deps \
  -v ./backup:/backup \
  keycloak export \
  --realm dashy \
  --dir /backup \
  --users realm_file \
  --optimized
```

Here's [an example backup](https://github.com/user-attachments/files/27861822/dashy-realm.json) of the working realm config for this demo.

## Step 3: Add the Keycloak settings to Dashy config

```yaml
appConfig:
  theme: catppuccin
  layout: masonry
  iconSize: medium
  disableConfigurationForNonAdmin: true
  auth:
    enableKeycloak: true
    keycloak:
      serverUrl: http://localhost:9100
      realm: dashy
      clientId: dashy
      adminRole: dashy-admin
```

## Step 4: All done :)

Now, when you lang on Dashy, you get redirected to Keycloak. After authenticating, your sent back to Dashy.

The auth applies both client + server, so once keycloak is enabled, you'll get a 401 if you try and call anythig before authenticating.

If you authenticated as a user in the admin group, then you'll be able to also view admin settings in Dashy.

You show/hide sections in Dashy based on keycloak user roles, like:

```yaml
  - name: Admin Links
    icon: fas fa-user-shield
    displayData:
      showForKeycloakUsers:
        roles:
          - dashy-admin
```

To disable all editing features for non-admins, then set `appConfig.disableConfigurationForNonAdmin: true`
