### ISSUE TITLE
[BUG] BASE_URL breaks yarn build

### ISSUE THREAD

**Issue by LandStander27** [Lissy93/dashy#1759]
### Environment

Self-Hosted (Docker)

### System

Fedora-Server 6.11.10, Docker 27.3.1

### Version

3.1.1

### Describe the problem

When starting up the container with `BASE_URL` not set, (set to `./`), the yarn build finishes fine and there are no errors. However, when I have `BASE_URL` set (`/dash`) I get a `Failed to compile with 1 error`.

Going to `http://{domain}/dash` returns with `Error: ENOENT: no such file or directory, stat '/app/dist/index.html'`. However, going to the root (`http://{domain}/`) shows the loading screen.

### Additional info

docker-compose.yml
```
services:
  dashy:
    image: lissy93/dashy:latest
    restart: unless-stopped
    environment:
      - VUE_APP_healthcheck_key=secret
      - VUE_APP_passwd=secret
      - NODE_ENV=production
      - VUE_APP_STARTING_VIEW=home
      - IS_DOCKER=true
      - BASE_URL="/dash"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080
    volumes:
      - secret:/app/user-data/conf.yml

  monitoring:
    image: nicolargo/glances:latest
    restart: always
    pid: host
    build:
      network: host
    privileged: true
    ports:
      - 61208:61208
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release:ro
    environment:
      - "GLANCES_OPT=-w"
```

Parts of the error that seem even somewhat useful (everything else looks like the HTML for the crash page):

`This is likely caused by the app source not being found at the current domain`
```  - htmlparser.js:240 new HTMLParser
    [app]/[html-minifier]/src/htmlparser.js:240:13
  
  - htmlminifier.js:966 minify
    [app]/[html-minifier]/src/htmlminifier.js:966:3
  
  - htmlminifier.js:1326 exports.minify
    [app]/[html-minifier]/src/htmlminifier.js:1326:16
  
  - index.js:316 
    [app]/[html-webpack-plugin]/index.js:316:18
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
