### ISSUE TITLE
[QUESTION] Unable to Get Multiple Pages to Work

### ISSUE THREAD

**Issue by qfy1r9** [Lissy93/dashy#1761]
### Question

Hi there,

I’m having some trouble getting multiple pages to work in my Dashy setup. Here’s a breakdown of the issue:

I’ve created the necessary YAML files (`work.yml`, `homelab.yml`, and `bookmarks.yml`) and referenced them in my `conf.yml` file. The `docker-compose.yml` is also configured correctly, but when I deploy the container, the pages do not appear. 

When I go into the settings and manually add the page titles and paths (e.g., `work.yml`, `homelab.yml`), and refresh the page, I encounter the following error message: 

**"work.yml or bookmarks.yml not found."**

I’ve double-checked my file paths, but I’m still facing the issue. Could someone point out what I might be missing or doing wrong? Any guidance would be greatly appreciated!

![Skjermbilde 2024-12-05 133005](https://github.com/user-attachments/assets/a190ed84-01bf-414f-85ee-d1bd3d0507bb)
![Skjermbilde 2024-12-05 132845](https://github.com/user-attachments/assets/c223a479-e90b-4375-a525-24f86259ce02)

### **Docker-Compose Configuration:**

```yaml
version: "3.8"
services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - '/home/docker/dashy/public/conf.yml:/app/public/conf.yml'
      - '/home/docker/dashy/icons:/app/public/item-icons/icons'
    ports:
      - '4000:8080'
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
```

### **conf.yml:**

```yaml
pages:
  - name: Work
    path: 'work.yml'
  - name: Homelab
    path: 'homelab.yml'
  - name: Bookmarks
    path: 'bookmarks.yml'

---
appConfig:
  theme: colorful
  layout: auto
  iconSize: medium
  language: en
pageInfo:
  title: Start Page
  description: Welcome to your Home Lab!
  navLinks:
    - title: GitHub
      path: https://github.com/Lissy93/dashy
    - title: Documentation
      path: https://dashy.to/docs
  footerText: ''
sections:
  - name: Starter Only
    icon: fas fa-server
    items:
      - title: Google
        description: Search
        url: https://google.com
```

### **work.yml:**

```yaml
pageInfo:
  title: Work Resources
  description: Tools and links related to work
sections:
  - name: Tools
    icon: fas fa-briefcase
    items:
      - title: Jira
        url: https://jira.example.com
        icon: fas fa-tasks
      - title: Slack
        url: https://slack.com
        icon: fas fa-comments
      - title: Trello
        url: https://trello.com
        icon: fas fa-columns
```

### **homelab.yml:**

```yaml
pageInfo:
  title: Homelab
  description: Monitor and manage your home servers
sections:
  - name: Monitoring
    icon: fas fa-server
    items:
      - title: Grafana
        url: https://grafana.example.com
        icon: fas fa-chart-line
      - title: Portainer
        url: https://portainer.example.com
        icon: fas fa-docker
  - name: Services
    items:
      - title: Jellyfin
        url: https://jellyfin.example.com
        icon: fas fa-film
      - title: Nextcloud
        url: https://nextcloud.example.com
        icon: fas fa-cloud
```

---

### **Category:**

Configuration

### **Checklist:**

- [X] I am using a [[supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions)](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (checked the first two digits of the version number).
- [X] I’ve ensured that this issue hasn’t already been raised by searching the existing issues [[here](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)](https://github.com/Lissy93/dashy/issues?q=is%3Aissue).
- [X] I’ve reviewed the [[docs](https://github.com/Lissy93/dashy/tree/master/docs#readme)](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [[troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting)](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide.
- [X] I agree to the [[code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct).

---
