### ISSUE TITLE
[FEATURE_REQUEST] Save sections in a separate file

### ISSUE THREAD

**Issue by ZzenlD** [Lissy93/dashy#1785]
### Is your feature request related to a problem? If so, please describe.

It would be good if you could outsource the configuration sections to separate files:
- Configuration file becomes shorter/simpler/clearer
- Entire sections could simply be commented out
- Easier debugging in case of syntax errors

### Describe the solution you'd like

The main configuration file could then look like this:
```yaml
pageInfo:
  title: <title>

appConfig:
  defaultOpeningMethod: modal
  hideComponents:
    hideHeading: true
    hideNav: true
    hideSettings: true
    hideFooter: true
  enableMultiTasking: true
  disableConfiguration: true
  disableUpdateChecks: true

sections:
  - name: Favorites
    icon: star.svg
    items:
      - title: <Service_1>
        url: https://service_1
        target: workspace
      - [...]
 
{{- $file := glob "/config/*.yml" }}
{{- fileContent | toYaml | expandenv | nindent 2 }}
{{- end }}
```

An example file called `example_section.yml` could then have the following content:
```yaml
- name: Example section
  items:
    - title: <Service_X>
      url: https://service_x
    - [...]
```

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

None
