### ISSUE TITLE
[BUG] Issues with Pihole widgets not working

### ISSUE THREAD

**Issue by back-lacking** [lissy93/dashy#1819]
### Environment

Self-Hosted (Docker)

### System

Debian 12.9, Docker 27.5.1

### Version

3.1.1

### Describe the problem

So my widgets for Pihole one day stopped working. Turns out that Pihole had a relatively big update, not sure if that broke how dashy interacts with the Pihole API. 
My normal API key doesn't work, and trying to use an app password I made in Pihole doesn't work. 
not sure if the project has been updated to handle that. 

### Please tick the boxes

- [x] You have explained the issue clearly, and included all relevant info
- [x] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [x] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [x] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [x] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by jsonger** [comment]
They did a massive overhaul of how the API is called with v6.  New endpoint locations and a new auth mechanism.

**Comment by LarryT8959** [comment]
Will this be addresses or we just have to remove the widgets?

**Comment by clockwinder** [comment]
I'm having the same issue since updating Pihole to v6.x+

**Comment by jackald** [comment]
I am also having the same issue since updating Pihole to v6.x+

**Comment by back-lacking** [comment]
ive since went from dashy to homepage

**Comment by Ito-69** [comment]
I have the same problem with new ver6 on PiHole widgets now working any more.
New version is different and there is no API token at least I can not fined it .

**Comment by LarryT8959** [comment]
> I have the same problem with new ver6 on PiHole widgets not working any more.
> New version is different and there is no API token at least I can not fined it .
> 

Token is there but it doesn't work.

**Comment by LarryT8959** [comment]
Has this been addressed yet?

**Comment by SeimusS** [comment]
pihole v6 doesnt use any API key for access. It uses the password or app password. The overhaul of API in pihole v6 made apps made for v5 incompatible.

The widget for pihole in Dashy will need adjustments in order for it to work again.

**Comment by xxdr4gon** [comment]
Is it still prevalent? Running into the same issues described here.

**Comment by LarryT8959** [comment]
Yes, looks like no one is addressing this issue. At least I'm not aware of.

**Comment by TheUriF** [comment]
Would be nice if the widgets could be updated. It looks like the app password would work, it's just fetching from the wrong place

`WARNING API: Bad request (key: bad_request, hint: The API is hosted at pi.hole/api, not pi.hole/admin/api)`

**Comment by EarlyOwl** [comment]
Sadly, it won't work by just changing the endpoint, because the v6 API doesn't just accept the API key in the query like it used to.

Instead, you first have to do a **POST request to authenticate** (using what now is called as **App Password**), and then **use the data in the response** (X-FTL-SID, X-FTL-CSRF) to make subsequent GET requests ([Reference](https://docs.pi-hole.net/api/auth/#use-the-sid-to-access-api-endpoints)).

I wrote a new version of the PiHoleStats widget that works (for me at least) with the v6 API. It needs some work as it's somewhat buggy, but I'm sharing it here in case someone wants to look into it and contribute.

![Image](https://github.com/user-attachments/assets/042e48d2-935f-4e5c-8e68-184dc0f478c2)

**Repo:  [EarlyOwl/dashy](https://github.com/EarlyOwl/dashy)**

**To test it, either:**
### Build from source

```
git clone https://github.com/EarlyOwl/dashy.git
cd dashy/
vi user-data/conf.yml #To add your config, look at the end of the comment
npm install
npm run build
```
Retrieve the build files under the **/dist** folder to serve them (e.g., with NGINX)

### Build directly inside the container (risky - make sure to backup your config)
1. Enter the running container (I use `sudo docker exec -it DASHYCONTAINERNAME sh`)
2. Edit the file _/app/src/components/Widgets/WidgetBase.vue_ to add the line:
`'pi-hole-stats-v6': 'PiHoleStatsV6',`
3. In the same folder create **PiHoleStatsV6.vue** with the content [from the repo](https://github.com/EarlyOwl/dashy/blob/master/src/components/Widgets/PiHoleStatsV6.vue)
4. Finally, build with `cd /app && npm run build`

Remember to either **update your conf.yml** before building or do it with the web editor if you're editing an existing container.

### YML Sample config
```yml
pageInfo:
  title: Pihole widget Test
  description: EarlyOwl
appConfig:
  theme: dashy-docs
  layout: auto
  iconSize: medium
sections:
  - name: Stats
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items: []
    widgets:
      - id: 0_527_piholestatsv
        type: pi-hole-stats-v6
        position: left
        options:
          hostname: https://yourpihole.url
          apiKey: YOURAPPPASSWORD
          hideStatus: 0
          hideChart: 0
          hideInfo: 0
```

I haven't changed the parameter names used in the original PiHoleStat widget, just remember to change the **type** from **pi-hole-stats** to **pi-hole-stats-v6**. And of course to fill the apiKey parameter with your **App Password**.

**Comment by Shirkamdev** [comment]
Has this work been published? I see that @EarlyOwl was able to make it work, but it doesn't seem like it was introduced in Dashy.

**Comment by dziban303** [comment]
Are the v6 widgets broken? No matter what I put in for host or apiKey (as long as they're valid), I get 400 errors. tried both SSL and unencrypted, tried adding /admin to the hostname field, changed my password to verify i'm not crazy, 2fa on and off, used an app password rather than the web password—none of it worked. same result with all of the v6 pihole widgets. none of them are working.

**Comment by lissy93** [comment]
Hiya @dziban303 
Sorry for the delay on this. I've got a small fix coming in #2356, which should get it all working. I'll let you know here once it's merged + released on docker.

---

Below is sounds troubleshooting steps if you've still got issues:
- Ensure you're using the `-v6` versions of the pi-hole widgets (old ones were for old pi-hole)
- For `hostname`, ensure you've got the Pi-hole root, NOT with `/admin`
- For `apiKey` put your web password. Or the app password you made, if you have 2FA on
- If you get a CORS error, check you've got `useProxy: true`
- If you've got a self-signed cert, you might also need `allowInsecure: true`
- If you get a 401, then your password was wrong
- If you get 429, then you didn't upgrade, this should be fixed

---

If you're still having trouble, let me know here, and I;ll try and help. But it would help if you could share relevant parts of logs + config (in the Config menu there's a "Debug info" button).

---

Here's a rough example:

```yaml
sections:
  - name: Pi-hole
    icon: fas fa-shield-alt
    widgets:
      - type: pi-hole-stats-v6
        useProxy: true           # probably needed
        updateInterval: 120      # optional, seconds
        options:
          hostname: http://192.168.1.2   # Pi-hole's root URL, no /admin
          apiKey: your-pihole-password
      - type: pi-hole-top-queries-v6
        useProxy: true
        options:
          hostname: http://192.168.1.2
          apiKey: your-pihole-password
          count: 10             # optional
      - type: pi-hole-traffic-v6
        useProxy: true
        options:
          hostname: http://192.168.1.2
          apiKey: your-pihole-password
```

---

I don't use Pi-Hole anymore (AdGuard ftw), but I spun up a demo instance and tested everything out, and it does all seem good now:

<img width="600" alt="Image" src="https://github.com/user-attachments/assets/2df3be2f-15d9-4ac6-90c0-086a10db49ef" />
