### ISSUE TITLE
[BUG] Authentication Issue v3.1.1

### ISSUE THREAD

**Issue by Sephiro92** [Lissy93/dashy#1831]
### Environment

Self-Hosted (Docker)

### Version

3.1.1

### Describe the problem

Greetings,
I'm trying to use the authentication provided by Dashy but so far I've never managed to authenticate and I always have the message "Password is incorrect"

It's not a configuration issue since I've done everything the documentation says and also tried what I saw on other issue.
I though the update would have fixed this issue I have with authentication for years now but it remain.

Can someone provide me informations and help to finally make it work ?

my auth config section :
```
  auth:
    enableGuestAccess: true
    users:
    - user: alicia
      password: azerty
      type: admin
    - user: bob
      password: azerty
  disableConfigurationForNonAdmin: true
```
I've tested the auth with : Chrome (extention disabled), firefox, edge
Same result.

If you need more informations I'll be active as possible to provide.

Best regards.

### Additional info

Also have those errors on the dev console of my web browser :

```
GET http://127.0.0.1:8080/login 404 (Not Found)Understand this errorAI
CoolConsole.js:6 
Dashy  V3.1.1 🚀
3login:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was receivedUnderstand this errorAI
```
```
Incorrect use of <label for=FORM_ELEMENT>
```

### Please tick the boxes

- [x] You have explained the issue clearly, and included all relevant info
- [x] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [x] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [x] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [x] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Sephiro92** [comment]
Greetings I'm coming back to this topic I've open, I did a lot of tests and manage to make it work through ```hash``` instead of ```password``` (who seems deprecated)

puting my new conf for auth here as an exemple for those who might struggle like I did ;)

```
  auth:
    enableGuestAccess: true
    users:
    - user: alicia
      hash: f2d81a260dea8a100dd517984e53c56a7523d96942a834b9cdc249bd4e8c7aa9
      type: admin
    - user: bob
      hash: f2d81a260dea8a100dd517984e53c56a7523d96942a834b9cdc249bd4e8c7aa9
```

(!!! Don't put your password in a file and hash the file content, it'll result with the hash of the file and the content mixed up !!!) Avoid my mistake :)

Here is the command shell to safely generate your hash password sha256 :
```read -s myvar && echo -n $myvar | shasum -a 256```

> azerty = f2d81a260dea8a100dd517984e53c56a7523d96942a834b9cdc249bd4e8c7aa9

I hope it'll help peoples.

Best regards.
