### ISSUE TITLE
[BUG] Authentik Dashy

### ISSUE THREAD

**Issue by guihub78** [Lissy93/dashy#1860]
### Environment

Self-Hosted (Docker)

### Version

latest

### Describe the problem

I configured Authentik with Dashy with the procedure. I am successfully redirected to the SSO portal and log in, but then here is my error:

![Image](https://github.com/user-attachments/assets/6bc14029-2c30-4db5-b71b-f28500f04b64)

Conf yaml : 

appConfig:
  theme: glass
  layout: auto
  iconSize: medium
  auth:
    enableOidc: true
    oidc:
      clientId: "CLIENT_ID"
      endpoint: https://auth.domain.local/application/o/dashy

And when I remove the conf, everything works properly again.

Thanks you for you help.

### Please tick the boxes

- [x] You have explained the issue clearly, and included all relevant info
- [x] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [x] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [x] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [x] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Mawiguk0** [comment]
please supply the config with indentation.

**Comment by KingEldarion2** [comment]
Hi,

I literally just installed Dashy and tried to setup SSO with Authentik via OIDC.
I have the same Issue, so here is my Config File (literally the default with Authentik OIDC Enabled):

https://pastebin.com/aA7Fv9Lz

When I open Dashy, the Page is going unresponsive and the browser asks to stop the page.
Sometimes the Notification show by the Issue Creator is visible

**Comment by DLBPointon** [comment]
Hi all,

I'm going through trying to set up all my services with Authentik.

Indentation is correct, I can set `enableOidc` to false and Dashy will start working again. With no other changes. KeyCloak has been on and off with no changes effecting it.

Relevant chunk of the config is:

```
  auth:
    enableGuestAccess: false
    users: []
    enableOidc: true
    oidc:
      clientId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      endpoint: https://auth.xxx.com/application/o/dashy/
    enableHeaderAuth: false
    headerAuth:
      userHeader: REMOTE_USER
      proxyWhitelist: []
    enableKeycloak: false
```

**Comment by 0fflineuser** [comment]
Hi,
I had the same problem. (I followed the steps in the doc) 
Just make sure your users have their 'Name' and 'Email' set in authentik (in their settings). In my case they where empty, after adding them it works properly.

**Comment by DLBPointon** [comment]
Hi, apologies for the late reply. 

I'm having another go today and yeah absolutely nothing, the loading screen for dashy enters a forever loading state with enableOidc: true. Eventually, this does error out with a generic `error has occured` as shown in OP. I can't find any better logging to explain.

**Comment by lissy93** [comment]
Sorry I'd not been much help on this, I don't run Authenik myself, and it was another contributor who implemented the OIDC support, so it's not an area I'm very knowledgable about.

But I was recently just working on a feature for something else for OIDC-related on Dashy, and as part of that I needed to spin up an Authentik container and wire it in. So, I can drop a full guide of what I did to get this working below.

---

# How to put Authentik in front of Dashy

The example below uses `https://auth.example.com` for Authentik and `https://dashy.example.com` for Dashy. Replace both with whatever you actually use. The same instructions work for `http://localhost:9000` and `http://localhost:4000`

## 1. Run Authentik

If you not already done so, start Authentik.
I did this with the following:

`docker-compose.yml`:

```yaml
name: authentik

services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 10s
      retries: 5
      timeout: 5s
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik

  redis:
    image: docker.io/library/redis:7-alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 10s
      retries: 5
      timeout: 3s
    volumes:
      - ./data/redis:/data

  server:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG}
    restart: unless-stopped
    command: server
    environment: &authentik-env
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_BOOTSTRAP_PASSWORD: ${AUTHENTIK_BOOTSTRAP_PASSWORD}
      AUTHENTIK_BOOTSTRAP_TOKEN: ${AUTHENTIK_BOOTSTRAP_TOKEN}
      AUTHENTIK_BOOTSTRAP_EMAIL: ${AUTHENTIK_BOOTSTRAP_EMAIL}
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
    ports:
      - "9000:9000"
      - "9443:9443"
    depends_on:
      postgresql: {condition: service_healthy}
      redis: {condition: service_healthy}

  worker:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG}
    restart: unless-stopped
    command: worker
    environment: *authentik-env
    depends_on:
      postgresql: {condition: service_healthy}
      redis: {condition: service_healthy}
```

`.env`, sat next to the compose file:

```env
# Authentik release, pin to whatever whatever version u want
AUTHENTIK_TAG=2024.12

# Database password. Generate fresh: openssl rand -hex 32
PG_PASS=replace-me-with-random-hex

# Encryption key for sessions, tokens, and stored secrets
# If you lose this, you lose access to anything Authentik has encrypted
# Again, generate fresh ones with: openssl rand -hex 32
AUTHENTIK_SECRET_KEY=replace-me-with-random-hex

# First-boot admin (username is akadmin), you can change this in UI after first login
AUTHENTIK_BOOTSTRAP_PASSWORD=change-me-now
AUTHENTIK_BOOTSTRAP_EMAIL=you@example.com

# API token created on first boot
AUTHENTIK_BOOTSTRAP_TOKEN=replace-me-with-random-hex

# Where Authentik will be reachable from a browser, for the issuer URL
AUTHENTIK_URL=https://auth.example.com

# Where Dashy will be reachable, for the redirect URIs
DASHY_URL=https://dashy.example.com
```

Bring it up:

```bash
docker compose up -d
```

Then start the containers with `docker compose up -d`. The first boot runs the migrations which take a min to complete. After that, open `${AUTHENTIK_URL}` in the browser and sign in with `akadmin` with the bootstrap password.

If you're running Authentik behind a reverse proxy (Caddy, Traefik, nginx), point it at `server:9000` (HTTP) and make sure `X-Forwarded-Proto` is set to `https` on the proxied requests. Without that, Authentik's discovery document advertises `http://` issuer URLs, and Dashy's server-side token verification fails because the issuer claim does not match

## 2. Configure Authentik

### Add a groups scope

Go to Customisation > Property Mappings > Create > Scope Mapping
Name and scope name both `groups`, so expression is:

```python
return {"groups": [g.name for g in request.user.ak_groups.all()]}
```

### Create the OIDC provider

Then, go to Applications > Providers > Create > OAuth2/OpenID Provider
And add:
- Name: Dashy
- Authorization flow: default-provider-authorization-implicit-consent
- Invalidation flow: default-provider-invalidation-flow
- Client type: Public
- Client ID: dashy
- Redirect URIs (matching mode strict): your Dashy URL with and without a trailing slash
  - e.g. `https://dashy.example.com` and `https://dashy.example.com/`
- Signing key: any existing self-signed certificate (Authentik creates one on first boot)
- Advanced > Scopes: openid, profile, email, groups (the one you just made)
- Include claims in id_token: on

### Create the application

Then, go to Applications > Applications > Create
Name `Dashy`, slug `dashy`, provider `Dashy`

### Create the admin group

And in Directory > Groups > Create > `dashy-admins`
Add the users you want to give admin rights inside Dashy

### Grab the issuer URL

The OpenID Configuration Issuer URL is shown on the provider's page, that's what Dashy needs

### Alternate approach

<details>

<summary>Script version</summary>

Since i was repeatidly spinning up and killing Authentik, i used a script to configure it instead of the UI. It's terribly written, but this worked for me:

```bash
#!/usr/bin/env bash
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
set -a; source "$HERE/.env"; set +a

API="$AUTHENTIK_URL/api/v3"
TOKEN="$AUTHENTIK_BOOTSTRAP_TOKEN"

# Initial passwords for the two users created below.
ADMIN_PASS="change-me-admin"
USER_PASS="change-me-user"

auth=(-H "Authorization: Bearer $TOKEN")
json=(-H "Content-Type: application/json")
api_get()  { curl -fsS "${auth[@]}" "$API$1"; }
api_post() { curl -fsS -X POST "${auth[@]}" "${json[@]}" -d "$2" "$API$1"; }

echo "Waiting for Authentik API at $API..."
for i in $(seq 1 90); do
  if api_get "/root/config/" >/dev/null 2>&1; then echo "  up"; break; fi
  printf '.'; sleep 5
done

FLOW_ID=$(api_get "/flows/instances/?slug=default-provider-authorization-implicit-consent" | jq -r '.results[0].pk')
INVAL_FLOW_ID=$(api_get "/flows/instances/?slug=default-provider-invalidation-flow" | jq -r '.results[0].pk')
CERT_ID=$(api_get "/crypto/certificatekeypairs/" | jq -r '.results[0].pk')

scope_pk() { api_get "/propertymappings/provider/scope/?scope_name=$1" | jq -r '.results[0].pk // empty'; }
SC_OPENID=$(scope_pk openid)
SC_PROFILE=$(scope_pk profile)
SC_EMAIL=$(scope_pk email)

# Authentik doesn't ship a "groups" scope by default. Create one that puts the
# user's group names into the id_token, which is what Dashy's adminGroup check reads.
SC_GROUPS=$(scope_pk groups)
if [[ -z "$SC_GROUPS" ]]; then
  SC_GROUPS=$(api_post "/propertymappings/provider/scope/" "$(cat <<'JSON'
{
  "name": "Dashy: groups",
  "scope_name": "groups",
  "description": "Expose user group names as a groups claim",
  "expression": "return {\"groups\": [g.name for g in request.user.ak_groups.all()]}"
}
JSON
)" | jq -r '.pk')
fi

PROVIDER_PK=$(api_get "/providers/oauth2/?name=Dashy" | jq -r '.results[0].pk // empty')
if [[ -z "$PROVIDER_PK" ]]; then
  PROVIDER_PK=$(api_post "/providers/oauth2/" "$(cat <<JSON
{
  "name": "Dashy",
  "client_type": "public",
  "client_id": "dashy",
  "authorization_flow": "$FLOW_ID",
  "invalidation_flow": "$INVAL_FLOW_ID",
  "signing_key": "$CERT_ID",
  "property_mappings": ["$SC_OPENID", "$SC_PROFILE", "$SC_EMAIL", "$SC_GROUPS"],
  "redirect_uris": [
    {"matching_mode": "strict", "url": "$DASHY_URL"},
    {"matching_mode": "strict", "url": "$DASHY_URL/"}
  ],
  "sub_mode": "hashed_user_id",
  "include_claims_in_id_token": true,
  "access_token_validity": "hours=1",
  "refresh_token_validity": "days=30"
}
JSON
)" | jq -r '.pk')
fi

if [[ -z "$(api_get "/core/applications/?slug=dashy" | jq -r '.results[0].pk // empty')" ]]; then
  api_post "/core/applications/" "{\"name\":\"Dashy\",\"slug\":\"dashy\",\"provider\":$PROVIDER_PK}" >/dev/null
fi

GROUP_PK=$(api_get "/core/groups/?name=dashy-admins" | jq -r '.results[0].pk // empty')
if [[ -z "$GROUP_PK" ]]; then
  GROUP_PK=$(api_post "/core/groups/" '{"name":"dashy-admins","is_superuser":false}' | jq -r '.pk')
fi

create_user() {
  local username="$1" name="$2" pass="$3" group_pk="$4" body
  local pk=$(api_get "/core/users/?username=$username" | jq -r '.results[0].pk // empty')
  if [[ -z "$pk" ]]; then
    if [[ -n "$group_pk" ]]; then
      body="{\"username\":\"$username\",\"name\":\"$name\",\"email\":\"$username@example.com\",\"path\":\"users\",\"groups\":[\"$group_pk\"]}"
    else
      body="{\"username\":\"$username\",\"name\":\"$name\",\"email\":\"$username@example.com\",\"path\":\"users\"}"
    fi
    pk=$(api_post "/core/users/" "$body" | jq -r '.pk')
  fi
  api_post "/core/users/$pk/set_password/" "{\"password\":\"$pass\"}" >/dev/null
}

create_user "dashy-admin" "Dashy Admin" "$ADMIN_PASS" "$GROUP_PK"
create_user "dashy-user"  "Dashy User"  "$USER_PASS"  ""

echo
echo "Provider client_id : dashy"
echo "OIDC endpoint      : $AUTHENTIK_URL/application/o/dashy/"
echo "Admin group claim  : dashy-admins"
echo "Test admin login   : dashy-admin / $ADMIN_PASS"
echo "Test user login    : dashy-user / $USER_PASS"
```


</details>

## 3. Configure Dashy

In `user-data/conf.yml`, set the `auth` block under `appConfig`:

```yaml
appConfig:
  disableConfigurationForNonAdmin: true
  auth:
    enableOidc: true
    oidc:
      clientId: dashy
      endpoint: https://auth.example.com/application/o/dashy/
      adminGroup: dashy-admins
      scope: openid profile email groups
```

Three things which caught me out the first time:
- `endpoint` is the issuer URL, not the discovery URL. Dashy appends `/.well-known/openid-configuration` itself. Don't paste the full discovery URL, or you get redirect loops
- The `groups` scope is required when you set `adminGroup`. Without it the id_token has no groups claim and Dashy treats every login as non-admin
- `disableConfigurationForNonAdmin: true` is what enforces the admin distinction. Without it any logged-in user can edit the dashboard

Then restart dashy, `docker compose restart dashy` so that it gets the updated env vars.

Dashy's server also verifies tokens server-side, which means the Dashy container has to be able to reach `${AUTHENTIK_URL}` over the network. If both are behind the same reverse proxy on the same host, that's automatic. If not, make sure DNS resolves and any firewall rules allow it.

## 4. Test

Now when you visit Dashy, you'll (hopefully!) be redirected to Authentik's login page, and after logging in you'll then be sent back to your now-authenticated Dashy homepage 😃
To logout from Dashy, use the logoug button.

## Troubleshooting

<details>

### Redirect loop after login
Your `endpoint` probably includes `.well-known/openid-configuration`. Drop everything from `.well-known` onwards

### invalid_redirect_uri
The redirect URI Authentik has registered for the provider doesn't exactly match the URL Dashy is being served from. Register both the bare URL and the trailing-slash version, and make sure the scheme matches (`http` vs `https`).

### Login works in the browser but the dashboard refuses to save anything (403)
Dashy's server is rejecting the id_token. Check Dashy's container logs for `[auth-oidc] token verification failed`. Common causes:
- **Issuer mismatch**. Authentik is behind a reverse proxy that isn't sending `X-Forwarded-Proto: https`, so its discovery document advertises `http://` while you configured `https://` in Dashy. Fix the proxy or set `AUTHENTIK_HOST`/`AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS` on the Authentik containers
- **Audience mismatch**. The `aud` claim in the id_token is not `dashy`. Confirm the provider's Client ID is exactly `dashy` (no leading or trailing whitespace)
- **Dashy server can't reach Authentik**. The Dashy container fails to fetch the discovery document. Exec into the container and try `wget -qO- https://auth.example.com/application/o/dashy/.well-known/openid-configuration`
- **Clock skew**. The middleware allows 30 seconds of drift. If a container's clock is further off than that, `exp`/`iat` checks fail

### Logged in but no admin controls
The id_token doesn't include the groups claim. Open browser devtools after logging in, find the call to `/application/o/dashy/userinfo/`, and check the response. You should see a `groups` array containing `dashy-admins`. If not:
- The `groups` scope mapping doesn't exist, or is not attached to the provider's property mappings
- The user is not in the `dashy-admins` group
- The conf.yml is missing `groups` from `scope:` and Authentik is therefore not sending it

### Login works but Dashy errors on the callback with "OIDC signinCallback returned no user"
The id_token came back without a username claim. Confirm the provider has "profile" and "email" in its scopes and the "Include claims in id_token" is on

### Sign-out leaves you stuck on Authentik
Dashy redirects to Authentik's end-session endpoint on logout. If Authentik's invalidation flow prompts for confirmation (the default), that's expected - click through it. To skip the prompt entirely, change the provider's invalidation flow to one without a consent stage.

### Untrusted certificate from Authentik
Self-signed certs make Dashy's server-side fetch of the discovery document fail. Use a real cert (Let's Encrypt, or your homelab CA installed into the Dashy image) for the Authentik hostname.

### Numeric client_id getting truncated
Don't use numeric-only client IDs. If you must, wrap the value in quotes in conf.yml so YAML treats it as a string

</details>
