### ISSUE TITLE
[QUESTION] Dashy prepending own URL to item URLs

### ISSUE THREAD

**Issue by PacifistPickle** [Lissy93/dashy#1863]
### Question

- OS: Rocky
- Build: Docker
- Version: 3.1.1

My Dashy is prepending it's own address to each item's URL. Example: if my dashy is at `dashy.tailnet-name.ts.net`, my Jellyfin will link to `dashy.tailnet-name.ts.net/jellyfin.tailnet-name.ts.net`. 

I'm opening this as a question because I can't tell if it's a bug or a problem with my conf.yml. The help is much appreciated.

Below is my config excluding a few other items and sections but they experience the same issue.

```
pageInfo:
  title: <server name>
  description: ''
  appConfig:
    theme: glass
    layout: horizontal
    iconSize: large
    startingView: default
    defaultOpeningMethod: sametab
    statusCheck: true
    statusCheckInterval: 0
    faviconApi: allesedv
    routingMode: hash
    enableMultiTasking: false
    widgetsAlwaysUseProxy: false
    webSearch:
      disableWebSearch: true
      searchEngine: duckduckgo
      openingMethod: newtab
      searchBangs: {}
    enableFontAwesome: true
    enableMaterialDesignIcons: false
    hideComponents:
      hideHeading: false
      hideNav: false
      hideSearch: false
      hideSettings: false
      hideFooter: false
    auth:
      enableGuestAccess: false
      users: []
      enableOidc: false
      enableHeaderAuth: false
      headerAuth:
        userHeader: REMOTE_USER
        proxyWhitelist: []
      enableKeycloak: false
    showSplashScreen: false
    preventWriteToDisk: false
    preventLocalSave: false
    disableConfiguration: false
    disableConfigurationForNonAdmin: false
    allowConfigEdit: true
    enableServiceWorker: false
    disableContextMenu: false
    disableUpdateChecks: false
    disableSmartSort: false
    enableErrorReporting: false
    sections:
      - name: Media
        icon: ''
        items:
          - title: Jellyfin
            description: Media Streaming
            icon: >-
            https://www.dockhunt.com/_next/image?url=https%3A%2F%2Fdockhunt-images.nyc3.cdn.digitaloceanspaces.com%2F4b054cbd-4ede-4f5e-8192-b1af71698ea0&w=256&q=75
            url: jellyfin.tailnet-name.ts.net
            target: sametab
            statusCheck: true
            id: 0_480_jellyfin
        displayData:
          sortBy: alphabetical
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
``` 

Here's the dashy section my docker-compose.yml file.
```dockerfile
dashy:
  image: lissy93/dashy:latest
  container_name: dashy
  network_mode: service:dashy-ts
  depends_on:
    - dashy-ts
  volumes:
    - config:/app/user-data
  restart: unless-stopped
``` 

### Category

Configuration

### Please tick the boxes

- [x] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [x] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [x] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [x] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
