### ISSUE TITLE
[BUG] `section.displayData.collapsed: true` not working

### ISSUE THREAD

**Issue by jhelmink** [Lissy93/dashy#252]
### Environment

Self-Hosted (Docker)

### Version

1.8.3

### Describe the problem

```
    - name: Dashy Docs
      icon: fas fa-file-alt
      displayData:
        itemSize: small
        cols: 4
        collapsed: true
      items:
      - title: Source
        description: Source code and documentation on GitHub
        icon: fab fa-github
        url: https://github.com/Lissy93/dashy
      - title: Issues
        description: View currently open issues, or raise a new one
        icon: fas fa-bug
        url: https://github.com/Lissy93/dashy/issues
      - title: Documentation
        description: Full documentation
        icon: fas fa-file-alt
        url: https://github.com/Lissy93/dashy/tree/master/docs
      - title: Docker Compose
        description: Configuring Docker Compose
        icon: si-docker
        url: https://dashy.to/docs/deployment#using-docker-compose
```

The dashboard opens but this section does not start collapsed, despite the `collapsed` boolean being set to true.

(Side note, the title length is necessarily cut off - see screen shot below)

### Additional info

![image](https://user-images.githubusercontent.com/4581673/134850285-dff65028-e6bb-4fba-b658-5995b3e91b8a.png)

No errors are raised in the config;

![image](https://user-images.githubusercontent.com/4581673/134850498-f252bfb4-c0d0-44ae-b2e0-c2f0b842bb1a.png)

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
