### ISSUE TITLE
Make pageInfo.footerText allow html

### ISSUE THREAD

**Issue by turnrye** [Lissy93/dashy#28]
**Is your feature request related to a problem? If so, please describe.**
In my use case, there are multiple users of Dashy who may not be familiar with how it is deployed or run. As such, I'd like to update the footerText to link to Dashy and my deployment configuration repository so that users have an easier time discovering how to update the Dashy config. The issue today is that for me to add those links, the only place I can do that is either in navLinks (too prominent to dedicate that much space) or as a section (which I believe would be violating consistency of sections).

**Describe the solution you'd like**
Add the `v-html` directive to `footer`.

My closest work-around today is to use navLinks and custom CSS to decrease their prominence.

**Priority**:
Low

**Comment by Lissy93** [comment]
Great idea, I'll get onto that tomorrow and update you when it's done :)
Thank you for your PR earlier 🙌- that was the first one!

**Comment by Lissy93** [comment]
Done, merged in #30 :)

The attribute in the config file is exactly the same, it just now accepts HTML and inline styles as well as plain text. You can use it like:
```yaml
pageInfo:
  title: Dashy
  footerText: '<div style="text-align: left;"><h1 style="color: blue;">HTML Footer Example</h1><ul><li>Bullet 1</li><li>Bullet 2</li></ul></div>'
```
