### ISSUE TITLE
[QUESTION] Download Config

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#36]
Hello,
I understand correctly that the modifications made from the browser are not saved in the conf.yml file. and so I thought that this otpions was used to download the current configuration in `Config > Backup Config > Actions > Downloads Config` to save it in the event that we would have made changes from the browser. (Config> Edit Sections for example)

But this is not the case, in any case, this action downloads the original conf.yml file, present in the container.

Is this the normal behavior?

### Exemple :
My conf.yml in contener : ( originaly )
```
appConfig:
  theme: "material-dark"
  fontAwesomeKey: "0821c65656"
pageInfo:
  title: "EVOServ - Dashy"
  navLinks:
    - title: "Accueil"
      path: "/"
    - title: "Code Source"
      path: "https://github.com/Lissy93/dashy"
  description: ""
  footerText: ""
sections:
  - name: "Serveur"
    items:
      - title: "Proxmox"
        description: ""
        url: "https://192.168.2.40:8006"
      - title: "Synology"
        description: ""
        url: "http://192.168.2.42:999"
      - title: "Portainer"
        description: ""
        url: "http://192.168.2.42:9000"
```

In WebBrowser : Config > Edit Sections, add statusCheck for Proxmox, Synology and Portainer :  `statusCheck: true`
In WebBrowser : Backup Config, I can see this:
```
appConfig:
  theme: "material-dark"
  fontAwesomeKey: "0821c65656"
pageInfo:
  title: "EVOServ - Dashy"
  navLinks:
    - title: "Accueil"
      path: "/"
    - title: "Code Source"
      path: "https://github.com/Lissy93/dashy"
  description: ""
  footerText: ""
sections:
  - name: "Serveur"
    items:
      - title: "Proxmox"
        description: ""
        url: "https://192.168.2.40:8006"
        statusCheck: true
      - title: "Synology"
        description: ""
        url: "http://192.168.2.42:999"
        statusCheck: true
      - title: "Portainer"
        description: ""
        url: "http://192.168.2.42:9000"
        statusCheck: true
```

By cons, if clicked `Donwload Config` I download the file conf.yml without the addition of statusCheck, i'm download the originaly conf.yml
