### ISSUE TITLE
[BUG] Unable to start dashy due to OOM on initial build

### ISSUE THREAD

**Issue by simpleauthority** [Lissy93/dashy#379]
### Environment

Self-Hosted (Docker)

### Version

latest

### Describe the problem

I am unable to start dashy when running in docker via docker-compose due to a OOM during build time.

The error:
```
Attaching to dashy
dashy            | 
dashy            | <--- Last few GCs --->
dashy            | 
dashy            | 
dashy            | <--- JS stacktrace --->
dashy            | 
dashy            | 
dashy            | #
dashy            | # Fatal process OOM in insufficient memory to create an Isolate
dashy            | #
dashy            | 
```

I am using this docker-compose setup:
```
  dashy:
    container_name: "dashy"
    image: "lissy93/dashy:arm64v8"
    env_file:
      - "./dashy/.env"
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.http.routers.dashy.rule=Host(`omitted`)"
      - "traefik.http.routers.dashy.entrypoints=https"
      - "traefik.http.routers.dashy.tls=true"
```

I have applied these environment variables, the `NODE_OPTIONS` in an attempt to resolve the OOM:
```
NODE_ENV=production
NODE_OPTIONS=--max-old-space-size=4096
```

This is my system information (`uname -a`): `Linux pine 5.4.17-2102.202.5.el8uek.aarch64 #2 SMP Sat May 22 16:34:31 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux`

`lscpu`:
```
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per cluster: 4
Socket(s):           -
Cluster(s):          1
NUMA node(s):        1
Vendor ID:           ARM
Model:               1
Model name:          Neoverse-N1
Stepping:            r3p1
BogoMIPS:            50.00
NUMA node0 CPU(s):   0-3
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
```

`free -m`:
```
              total        used        free      shared  buff/cache   available
Mem:          23114        5940        2940         642       14234       13063
Swap:          8191         192        7999
```

As far as I know I should have more than enough memory to run dashy, but as I've seen in other issues the initial build process does kick up the memory usage significantly. This does seem expected. But it doesn't explain why I can't seem to resolve the issue with the `NODE_OPTIONS` environment variable.

Any assistance would be much appreciated because this project looks amazing.

### Additional info

I think I included everything necessary but if not please let me know.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
