### ISSUE TITLE
[QUESTION] What am I missing/doing wrong in the Pi Hole Stats widget?

### ISSUE THREAD

**Issue by KierenConnell** [Lissy93/dashy#391]
### Question

Configured the Pi Hole stats widget as per the example, but it returns `Unable to fetch data`

```
name: Pi-Hole Stats
icon: hl-pihole
displayData:
  sortBy: default
  rows: 1
  cols: 1
  collapsed: false
  hideForGuests: false
widgets:
  - type: pi-hole-stats
    options:
      hostname: 'https://pihole-1.kierenconnell.com/admin/api.php'
```

Have tried setting hostname as direct IP to Pi Hole as per example, and also api.php
    

### Category

Widgets

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
