### ISSUE TITLE
[QUESTION] How to link an image for background?

### ISSUE THREAD

**Issue by shimizurei** [Lissy93/dashy#401]
### Question

I'm trying to add my custom background to Dashy, but I can't figure out the best method to do so.

These don't work: 

```
backgroundImg: "/volume1/docker/dashy/assets/bg.jpg" (for Synology)"
backgroundImg: "/dashy/assets/bg.jpg"
backgroundImg: "/assets/bg.jpg"
backgroundImg: "assets/bg.jpg"
backgroundImg: "./assets/bg.jpg"
```

I tried following [this part](https://github.com/Lissy93/dashy/blob/master/docs/theming.md#loading-external-stylesheets) in the Theming doc, to no avail.

Do I need to add something to my config file? I'm afraid of breaking something and I'm not the most savvy with docker/docker-compose.

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
So there's actually an option called `backgroundImg` under [`appConfig`](https://github.com/Lissy93/dashy/blob/master/docs/configuring.md#appconfig-optional), which you can just pass a (local or remote) URL to. You can place any local assets in the public directory, and use `/` to access them.

But if you want to continue with CSS, then put your images anywhere within the public folder, and then you can access them from the root of the domain.  For example, if you image was in `public/assets/bg.png`, you can reference it with `/assets/bg.png`. Don't forget paths are case sensitive ;)

Hope that helps :)

**Comment by shimizurei** [comment]
Still having a bit of trouble.

Here is my appConfig"

```
appConfig:
  layout: "auto"
  iconSize: "medium"
  theme: "thebe"
  defaultOpeningMethod: "newtab"
  backgroundImg: "/assets/bg.jpg"
```

and here is my config.yml

```
version: '3.8'
services:
  dashy:
    image: ghcr.io/lissy93/dashy:latest
    container_name: Dashy
    volumes:
      - /volume1/docker/dashy/dashyconfig.yml:/app/public/conf.yml
      - /volume1/docker/dashy/assets/dashycsstweaks.css:/app/src/styles/user-defined-themes.scss
      - /volume1/docker/dashy/assets/bg.jpg:/app/public/assets/bg.jpg
    ports:
      - xxx:80
    environment:
      - NODE_ENV=production
      - UID=xxx
      - GID=xxx
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
```

I just can't figure it out.
