### ISSUE TITLE
[BUG] Interactive Editor - Empty Edit Item

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#415]
Hello @Lissy93 

### Environment

Self-Hosted (Docker)

### Version

1.9.6

### Describe the problem
In interactive mode, when I click on the edit button to modify the configuration of an Item, the page is empty.

Same on Firefox and chrome up to date
![2022-01-09 00_19_28-2022_01_09_00_19_15_EVOServ_Dashy_Mozilla_Firefox png - Paint](https://user-images.githubusercontent.com/45015615/148663234-5c13e9f7-9ac8-4691-9fe8-69f8e71829d9.png)
![2022-01-09 00_19_39-EVOServ - Dashy — Mozilla Firefox](https://user-images.githubusercontent.com/45015615/148663240-67795173-af11-435b-ac5a-9bd46acc7a4f.png)

### Additional info

In Firefox Console : 

```
TypeError: t.items is undefined
    getItemById App.vue:66
    getItemById App.vue:65
    getItemFromState EditItem.vue:1
    mounted EditItem.vue:1
    VueJS 19
        ne
        Ni
        insert
        L
        Es
        _update
        n
        get
        run
        Xi
        ve
        he
        promise callback*re
        ve
        tn
        update
        notify
        set
        set
    openItemSettings Item.vue:148
    itemOpened ItemContextMenu.vue:1
    VueJS 3
        ne
        i
        _wrapper
vue.runtime.esm.js:1897:12
```

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Heya @EVOTk 

Thanks for raising, and sorry about that

Seems like this line, `this.item = this.getItemFromState(this.itemId);` in [`EditItem.vue`](https://github.com/Lissy93/dashy/blob/master/src/components/InteractiveEditor/EditItem.vue#L115) doesn't have any data, like it's unable to find the item matching that ID 🤔 

But weirdly I can't yet recreate it in any of my instances or on the [dev version](https://dev.dashy.to/#). I will look into it further and update you when I find a fix. Thank you for your patience :)

**Comment by EVOTk** [comment]
If that helps you, I just gave it a try and this bug goes away if I remove the pihole widgets from my configuration.

If I remove this from my configuration:
```
  - name: Serveur DNS
    widgets:
      - type: pi-hole-stats
        useProxy: true
        options:
          hostname: http://192.168.2.90
          hideChart: true
          hideInfo: true
        id: 0_1009_piholestats
      - type: pi-hole-stats
        useProxy: true
        options:
          hostname: http://192.168.2.91
          hideChart: true
          hideInfo: true
        id: 1_1009_piholestats
```

So it works fine:
![2022-01-09 10_00_53-EVOServ - Dashy — Mozilla Firefox](https://user-images.githubusercontent.com/45015615/148675951-a28c7bbd-d23e-40a1-bf37-587105ae29ae.png)

**Comment by EVOTk** [comment]
Oh ! And copy that, I see that the 2 widgets have the same IDs.

I modified like this:
```
  - name: Serveur DNS
    widgets:
      - type: pi-hole-stats
        useProxy: true
        options:
          hostname: http://192.168.2.90
          hideChart: true
          hideInfo: true
        id: 0_1009_piholestats
      - type: pi-hole-stats
        useProxy: true
        options:
          hostname: http://192.168.2.91
          hideChart: true
          hideInfo: true
        id: 1_1010_piholestats
```

But that doesn't change anything :(
