### ISSUE TITLE
[QUESTION] 2x environment in example docker-compose

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#48]
Hello, it's me again
In exemple of [docker-compose](https://github.com/Lissy93/dashy/blob/master/docker-compose.yml) : 

```
    # Set any environmental variables
    environment:
      NODE_ENV: production
```

the `environment` variable is duplicated with this example : 
```
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    # environment:
    #  - UID=1000
    #  - GID=1000
```

The `environment` variable is therefore present twice, and moreover the arguments are not written in the same way. Why not have indicated in the form : `NODE_ENV: production` or not `- NODE_ENV=production` ?

This would not be simpler if the example is: 
```
---
# Welcome to Dashy! To get started, run `docker compose up`
version: "3.8"
services:
  dashy:
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: Dashy
    # Pass in your config file below, by specifying the path on your host machine
    # volumes:
      # - /root/my-config.yml:/app/public/conf.yml
    ports:
      - 4000:80
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
```

Thx you, again ! :)
