### ISSUE TITLE
More then one copy running at a time.

### ISSUE THREAD

**Issue by BenMtl** [Lissy93/dashy#512]
Hi, I am trying to run 3 copies of Dashy on the same docker server and can't seem to get them to work. I have given each its own volume and container name in the compose file. Is there anything special that has to be done to have more then one copy running at a time or is there something I missed?

**Comment by Ateroz** [comment]
Could you post an example of your compose fil

**Comment by hugalafutro** [comment]
Did you give each instance it's own port too? I know it sounds obvious, but you mentioned volumes, but not ports. I just tried it and it works on my end. I copied the docker-compose.yml and config/config.yml and only 2 things I changed was port and container name. Both dashy instances are accessible and work.

For reference my docker-compose.yml:
```
---
version: "3.8"
services:
  dashy:
    container_name: dashy
    image: lissy93/dashy
    volumes:
      - ./config/config.yml:/app/public/conf.yml
      - ./icons:/app/public/item-icons
#      - ./certs/mycert.key:/etc/ssl/certs/dashy-priv.key:ro
#      - ./certs/mycert.pem:/etc/ssl/certs/dashy-pub.pem:ro
    ports:
#      - 4546:443
      - 4546:80
    environment:
      - NODE_ENV=production
      - INTEGRITY=true
      - UID=1000
      - GID=1000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
```
