### ISSUE TITLE
[BUG] keycloak configuration just gives a black screen, no dashboard, no login prompt

### ISSUE THREAD

**Issue by lgwapnitsky** [Lissy93/dashy#520]
### Environment

Self-Hosted (Bare Metal)

### Describe the problem

I've configured dashy to authenticate against my keycloak instance, which is currently working properly for other apps.

Upon rebuilding and relaunching dashy, I get a black screen, no login prompt, nothing else. The logs do not show anything, and a config validation shows no errors

Se

### Additional info

```
appConfig:
  theme: one-dark
  layout: vertical
  iconSize: medium
  language: en
  auth:
    enableKeycloak: true
    keycloak:
      serverUrl: https://auth.wapnet.MYDOMAIN.com
      realm: 'master'
      clientId: 'dashy'
```
![Screenshot at 2022-02-28 22-19-24](https://user-images.githubusercontent.com/647444/156098551-935094ea-d8f2-49c8-b71e-823610e14114.png)

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
