### ISSUE TITLE
[BUG] Latest release (2.0.4) is not starting 

### ISSUE THREAD

**Issue by jglezp** [Lissy93/dashy#539]
<h3 dir="auto">Environment</h3>
<p dir="auto">Self-Hosted (Docker)</p>
<h3 dir="auto">Version</h3>
<p dir="auto">2.0.4</p>
<h3 dir="auto">Describe the problem</h3>
<p dir="auto">With release 2.0.4 container is not becoming ready, its just in "starting" and does not works after hours.</p>
<p dir="auto">I removed my previous configuration (remove the volume) to check if a "fresh restart" works, and after 8 minutes it worked, but never with it.<br>
Trying to check logs there is no output to stdout/stderr, only this:</p>
<blockquote>
<p dir="auto">root@minipc:~/init# docker logs -f dashy<br>
yarn run v1.22.15<br>
$ node server</p>
<p dir="auto">Checking config file against schema...<br>
<g-emoji class="g-emoji" alias="heavy_check_mark" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2714.png">✔️</g-emoji> Config file is valid, no issues found</p>
<p dir="auto">SSL Not Enabled: Public key not present</p>
<p dir="auto">██████╗  █████╗ ███████╗██╗  ██╗██╗   ██╗<br>
██╔══██╗██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝<br>
██║  ██║███████║███████╗███████║ ╚████╔╝<br>
██║  ██║██╔══██║╚════██║██╔══██║  ╚██╔╝<br>
██████╔╝██║  ██║███████║██║  ██║   ██║<br>
╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝</p>
<hr>
<p dir="auto">Welcome to Dashy! <g-emoji class="g-emoji" alias="rocket" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f680.png">🚀</g-emoji><br>
Your new dashboard is now up and running with Docker</p>
<hr>
<p dir="auto">Using Dashy V-2.0.4. Update Check Complete<br>
<g-emoji class="g-emoji" alias="white_check_mark" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2705.png">✅</g-emoji> Dashy is Up-to-Date</p>
</blockquote>
<p dir="auto">Couldn't find any path on container with logs...<br>
And couldn't find any new release page, only the releases on github but last update was for 1.9: <a href="https://github.com/Lissy93/dashy/releases">https://github.com/Lissy93/dashy/releases</a></p>
<p dir="auto">I had to go back to 2.0.3 to make it work again.</p>
<h3 dir="auto">Additional info</h3>
<p dir="auto"><em>No response</em></p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy (check the first two digits of the version number)</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">issue hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                    <img src="https://repository-images.githubusercontent.com/343078060/fd44e000-ad15-11eb-8f8a-2feab996e27c" width="48" align="right" />                          <div>          <strong>                          <a href="https://github.com/Lissy93/dashy/releases">Releases · Lissy93/dashy</a>                      </strong>        </div>                    <div>🚀 A self-hosted startpage for your server. Easy to use visual editor, status checking, widgets, themes and tons more! - Lissy93/dashy</div>                      </blockquote>

**Comment by Ateroz** [comment]
Are you getting anything when you open dashy in your browser? The build no longer runs. As of 2.0.4 the app is distributed already built and no longer requires a rebuild on config change as mentioned in the changelog

**Comment by jglezp** [comment]
No, as I said, container is not on running state in any moment, it keeps on starting.

```
CONTAINER ID   IMAGE                                   COMMAND                  CREATED          STATUS                            NAMES
7a197f214472   lissy93/dashy:latest                    "/sbin/tini -- yarn …"   10 minutes ago   Up 10 minutes (health: starting)  dashy-latest
cfacb7a69d13   lissy93/dashy:2.0.3                     "/sbin/tini -- yarn …"   37 minutes ago   Up 37 minutes (healthy)           dashy
```

And compose:
```
  dashy:
    image: lissy93/dashy:2.0.3
    container_name: dashy
    volumes:
      - /srv/dashy:/app/public
    ports:
      - 4000:80
    restart: always
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      minipc:
        ipv4_address: 172.0.0.19
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashy.rule=Host(`dashy.example.org`)"
      - "traefik.http.routers.dashy.tls=true"
      - "traefik.http.routers.dashy.tls.certresolver=le"
      - "traefik.http.services.dashy.loadbalancer.server.port=80"

  dashy2:
    image: lissy93/dashy:latest
    container_name: dashy-latest
    volumes:
      - /srv/dashy:/app/public
    ports:
      - 4001:80
    restart: always
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      minipc:
```

I upload my configuration file if there is something that is not working now with new release

[conf.yml.zip](https://github.com/Lissy93/dashy/files/8197826/conf.yml.zip)

**Comment by jglezp** [comment]
After a few more minutes now it become unhealthy:

```
root@minipc:~/init# docker ps
CONTAINER ID   IMAGE                                   COMMAND                  CREATED          STATUS                     NAMES
7a197f214472   lissy93/dashy:latest                    "/sbin/tini -- yarn …"   7 minutes ago    Up 6 minutes (unhealthy)   dashy-latest
cfacb7a69d13   lissy93/dashy:2.0.3                     "/sbin/tini -- yarn …"   41 minutes ago   Up 41 minutes (healthy)    dashy
```

And no output on logs
```
root@minipc:~/init# docker logs -f dashy-latest
yarn run v1.22.15
$ node server

Checking config file against schema...
✔️ Config file is valid, no issues found

SSL Not Enabled: Public key not present


 ██████╗  █████╗ ███████╗██╗  ██╗██╗   ██╗
 ██╔══██╗██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝
 ██║  ██║███████║███████╗███████║ ╚████╔╝
 ██║  ██║██╔══██║╚════██║██╔══██║  ╚██╔╝
 ██████╔╝██║  ██║███████║██║  ██║   ██║
 ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝

*******************************************************************************************
Welcome to Dashy! 🚀
Your new dashboard is now up and running with Docker
*******************************************************************************************


Using Dashy V-2.0.4. Update Check Complete
✅ Dashy is Up-to-Date

```

**Comment by Lissy93** [comment]
I think it's mounting `/srv/dashy:/app/public` as the volume, but am having trouble recreating.
Mounting the `/app/public/conf.yml` file seems to work as expected. Let me look into it further....

**Comment by Ateroz** [comment]
You said it worked with a fresh config correct? The structure of the docker image has changed a bit and you're passing through an entire directory instead of just conf.yml.

Please change your volume to match what's described in the [docs](https://dashy.to/docs/deployment#using-docker-compose). I believe that should be the issue. And if it's not, it would definitely cause other issues after we work this out.

**Comment by jglezp** [comment]
> I think it's mounting `/srv/dashy:/app/public` as the volume that's the problem, but am having trouble recreating. Mounting the `/app/public/conf.yml` file seems to work as expected for me. Let me look into it further....

That was the problem... I mounted the volume and not only the config file because of custom icons...
This is working now:
```
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    volumes:
      - /srv/dashy/conf.yml:/app/public/conf.yml
      - /srv/dashy/item-icons:/app/public/item-icons
    ports:
      - 4000:80
    restart: always
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      minipc:
```

Thanks for the help
