### ISSUE TITLE
[FEATURE_REQUEST] Add Target Attribute to Nav Links

### ISSUE THREAD

**Issue by mkin701** [Lissy93/dashy#552]
### Is your feature request related to a problem? If so, please describe.

While I'm waiting for the multi-view feature to be released I'm trying to link my 3 Dashy instances together using navigation links. This works great except for the fact I cannot set the links to open in the same tab which is not ideal. I think this would be an easy feature to add and useful for other things as well.

### Describe the solution you'd like

It would be nice to have the `target` attribute available on the nav links in the top bar so links can be opened in the same tab as the dashboard. 

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
Sure, will do :)

**Comment by Lissy93** [comment]
Heya @mkin701
Sorry for the delay in addressing this, have now implemented your request in #557
So you can now set the opening method of each nav link with the `target` attribute

E.g.
```yaml
pageInfo:
  navLinks:
  - title: Workspace View
    path: /workspace
    target: sametab
  - title: Duck
    path: https://duck.com
    target: newtab
```

For more info, see config docs: [`pageInfo.navLinks`](https://github.com/Lissy93/dashy/blob/master/docs/configuring.md#pageinfonavlinks-optional)
Feel free to reach out if you need anything else :)
