### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by vanillanesquik** [Lissy93/dashy#577]
Hello,

I am having trouble with the weather widget, I was able to go through the configuration and setup all of my links and sections but I am trying to experiment with the widgets.

I was able to confirm that the basic widgets works (no API), for example the Crypto ones in the sample config.

I signed up for openweather.org and setup the widget in my config. I have tried several different city codes and switched to US just for troubleshooting.

I have tried with both the proxy (useProxy: true) and internal CORS (no proxy). I don't know how to access the logs to find out what the problem is. I only saw references to using the browser console which I do not have much experience with in troubleshooting.

Any idea where I may be able to find the logs?
I am running on Docker in Unraid. I have Pihole running on unraid and use PFsense on my router. Openweather.org and api.openweather.org are both pingable from inside the container.

![image](https://user-images.githubusercontent.com/79759690/160200161-68911276-3099-44a1-88bd-7f6121eec26b.png)

- name: Today
    displayData:
      rows: 5
      sortBy: default
      cols: 5
      collapsed: false
      hideForGuests: false
    widgets:
      - type: weather
        useProxy: true
        options: null
        apiKey: efdbade728b37086877a5e83442004db
        city: US
        units: imperial
        hideDetails: false
        id: 0_513_weather

**Comment by Lissy93** [comment]
Just [open the console](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console) / usually <kbd>F12</kbd>

Looking at your example, I think `us` is probably not a valid city name, it has to be something supported by OWM.

Also, not sure if it's just the formatting in how you've pasted your config (you can use ` ``` <code> ``` ` for code blocks), but the indentation of your config looks incorrect. Don't set options to null, instead, you need to nest `apiKey`, `city`, `units` under `options`. Try this instead:

```yaml
- name: Today
  displayData:
    rows: 5
    sortBy: default
    cols: 5
    collapsed: false
    hideForGuests: false
  widgets:
  - type: weather
    options:
      apiKey: efdbade728b37086877a5e83442004db
      city: London
      units: imperial
```

You can always run `yarn validate-config` if you're unsure.
