### ISSUE TITLE
[BUG] docker-compose.yml not working

### ISSUE THREAD

**Issue by JadBlackstone** [Lissy93/dashy#579]
### Environment

Self-Hosted (Docker)

### Describe the problem

When I try to run the docker-compose.yml from the documentation i get the following error.
```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the 'services' key, or omit the `version` key and place your service definitions at the root of the file to use version 1
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

### Additional info

I fixed it by changing the `version`
```
#original
version: "3.8"
#modified
version: '3'
```
and commenting out the `start_periode` of the `healthcheck`

my complete file looks like this:
```
version: '3'
services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: Dashy
    # Pass in your config file below, by specifying the path on your host machine
    #volumes:
      #- ./data:/app/public/
    ports:
      - 8012:80
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      #start_period: 40s
```

I don't know if it is a weird problem of my Server. If it is not, it would be great if you could update the documentation.
Great Tool by the way. I really like it.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
