### ISSUE TITLE
[QUESTION] How to use a named docker volume

### ISSUE THREAD

**Issue by remygrandin** [Lissy93/dashy#599]
### Question

Hi,

I'm trying to deploy Dashy on my docker cluster, however for that I need to be able to use a named volume for persistent storage.
I saw in your documentation an exemple of docker compose but with a direct file mapping for persistence.

I tried this
```
  dashy:
    image: lissy93/dashy
    container_name: BattleStation_Dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - persistent-Dashy:/public/
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      - UID=500
      - GID=500
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.battleStation_dashy_web.entrypoints=web"
      - "traefik.http.routers.battleStation_dashy_web.rule=Host(`XXXXXXXXX`)"
      - "traefik.http.routers.battleStation_dashy_websecure.entrypoints=websecure"
      - "traefik.http.routers.battleStation_dashy_websecure.tls=true"
      - "traefik.http.routers.battleStation_dashy_websecure.rule=Host(`XXXXXXXX`)"
```
Is there a way to specify the path of the config storage ? maybe with and ENV variable ?

PS : I reposted the question as I did't see a way to reopen the previous one auto closed by your bot :-)

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
