### ISSUE TITLE
[BUG] A new version of sass-loader is available, and some others warnings

### ISSUE THREAD

**Issue by MilesTEG1** [Lissy93/dashy#63]
Hello,
I'm trying Dashy witch seems very great 😃 

I'm using Docker on a Synology DS920+, and it runs great after a docker-compose install with Portainer.
But in the log I've got some warnings (see the log at the end of this message).

- The first warning I get is : ` WARN  A new version of sass-loader is available. Please upgrade for best experience.`
How can I upgrade if I'm already using the last version of Dashy ?

- Other warnings concerns the file size limit. Would it be a problem ?

Thanks for your help.

### ✍🏻  The LOGs :

```log
*******************************************************************************************
Welcome to Dashy! 🚀
Your new dashboard is now up and running in container ID 5b4daa1cb9c6
After updating your config file, run  'docker exec -it 5b4daa1cb9c6 yarn build' to rebuild
*******************************************************************************************


-  Building for production...
 WARN  A new version of sass-loader is available. Please upgrade for best experience.
 WARNING  Compiled with 2 warnings5:07:30 PM

 warning

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  fonts/Raleway-Variable.3b5635ac.ttf (302 KiB)
  js/chunk-vendors.34f36476.js (1.73 MiB)
  item-icons/synology/vpn_plus_server.png (264 KiB)
  web-icons/screenshots/dashy-scrsht-1.png (367 KiB)
  web-icons/windows10/LargeTile.scale-400.png (307 KiB)
  web-icons/windows10/SplashScreen.scale-400.png (307 KiB)

 warning

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  dashy (1.93 MiB)
      css/chunk-vendors.64811416.css
      js/chunk-vendors.34f36476.js
      css/dashy.a007dae4.css
      js/dashy.e0767cd2.js


  File                                      Size             Gzipped

  dist/js/chunk-vendors.34f36476.js         1767.30 KiB      516.49 KiB
  dist/js/dashy.e0767cd2.js                 109.53 KiB       32.45 KiB
  dist/precache-manifest.0a625fb1a654f0b    23.92 KiB        4.47 KiB
  e40100d1328f7aa9b.js
  dist/js/about.a7162e78.js                 4.48 KiB         1.99 KiB
  dist/service-worker.js                    1.04 KiB         0.61 KiB
  dist/css/dashy.a007dae4.css               94.05 KiB        14.44 KiB
  dist/css/chunk-vendors.64811416.css       4.38 KiB         1.47 KiB
  dist/css/about.a64c098d.css               1.04 KiB         0.34 KiB

  Images and other types of assets omitted.

 DONE  Build complete. Watching for changes...
```

### ✍🏻 For those who want my `docker-compose.yml` file :
```yaml
##==============================================================================================
##                                                                                            ##
##                              Fichier docker-compose.yml Dashy                              ##
##                                                                                            ##
##                              https://github.com/Lissy93/dashy                              ##
##                                                                                            ##
##==============================================================================================



---
  # Welcome to Dashy! To get started, run `docker compose up`
version: "2.4"
services:
  Dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy      # https://github.com/Lissy93/dashy
    container_name: Dashy

    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - /volume1/docker/dashy/dashy-config.yml:/app/public/conf.yml
      - /volume1/docker/dashy/images:/app/public/item-icons/
    
    ports:
      - 4000:80
    
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      - UID=1000
      - GID=1000
    
    # ###############
    # Le label ci-dessous permet à Watchtower de faire les mises à jour automatiquement
    # Cela peut-être supprimé si Watchtower n'est pas utilisé.
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    # ###############

    # Specify restart policy
    restart: unless-stopped
    
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
```
