### ISSUE TITLE
[BUG] Dashy not loading properly in Firefox brower

### ISSUE THREAD

**Issue by dtc-tech** [Lissy93/dashy#633]
### Environment

Self-Hosted (Docker)

### Describe the problem

Recently my Dashy dashboard does not load properly in Firefox.  I've dumbed down the my-config.yml quite a bit and still experience the same problem.  I've cleared all cookies/cache/history etc, I created a brand new Firefox profile (no extensions), even with these steps the same errors occur.  However, the Dashy dashboard loads properly in **Chrome** based broswers.

I also re-deployed a fresh Dashy docker on another host and I'm experiencing the same issue (with the same config).

All of the container logs look normal.

After +/- 30 seconds Firefox display this message:
[image1](https://i.postimg.cc/1z915gFB/20220505-firefox-213.png)
When I click "Stop" it will load 1/3rd of the page, missing images, sections, etc.

Here is the Firefox console output:
[image2](https://i.postimg.cc/65n1F9Ph/20220505-NVIDIA-Share-216.png)

Console Error:
`The stylesheet http://x.x.x.8:8091/# was not loaded because its MIME type, “text/html”, is not “text/css”.`

my-config.yml (IP addresses changed for privacy)

```
pageInfo:
  title: Controls
  description: Data Center Dashboard
  navLinks:
    - title: SearXNG
      path: http://0.0.0.0:8888
    - title: Linkding
      path: http://0.0.0.0:6505/login/?next=/bookmarks
    - title: Github
      path: https://github.com/dtc-tech
    - title: Documentation
      path: https://dashy.to/docs
  footerText: ⮩Control Panel⮨
appConfig:
  layout: auto
  iconSize: small
  language: en
  theme: nord-frost
  colCount: 4
sections:
  - name: Server Management
    icon: fas fa-server
    dispayData:
      sortBy: last-used
      collapsed: false
      cols: 4
      rows: 1
    items:
      - title: unRAID
        description: https://unraid:8111
        icon: unraid.png
        url: http://0.0.0.0/
        # statusCheck: true
        # statusCheckAllowInsecure: true
        id: 0_1684_unraid
      - title: Proxmox
        description: https://proxmox:8512
        icon: proxmox.png
        url: https://0.0.0.5:8006/
        # statusCheck: true
        # statusCheckAllowInsecure: true
        id: 1_1684_proxmox
      - title: xfcedoc
        description: http://xfcedoc:5235
        icon: portainer.png
        url: http://0.0.0.21:9000/
        # statusCheck: true
        # statusCheckAllowInsecure: true
        id: 0_1984_xfcedoc
      - title: ender01
        description: https://0.0.0.27:6231
        icon: portainer.png
        url: https://0.0.0.27:9443
        # statusCheck: true
        # statusCheckAllowInsecure: true
        id: 1_1984_archdoc
  - name: Network Admin
    icon: fas fa-ethernet
    dispayData:
      sortBy: last-used
      collapsed: false
      cols: 4
      rows: 1
    items:
      - title: pfSense
        icon: hl-pfsense
        url: http://0.0.0.1:4351
        # statusCheck: true
        # statusCheckAllowInsecure: true
        id: 0_1267_pfsense
      - title: UniFi
        icon: unifi-controller.png
        url: https://0.0.0.9:2366
        # statusCheck: true
        # statusCheckAllowInsecure: true
        id: 1_1267_unifi
      - title: Aruba
        icon: aruba.png
        url: https://0.0.0.53:4213
        # statusCheck: true
        # statusCheckAllowInsecure: true
        id: 2_1267_aruba
      - title: pihole-master
        description: DNS settings for ad & tracker blocking
        icon: pihole.png
        url: http://0.0.0.254/admin/
        target: newtab
        # statusCheck: true
        id: 3_1267_piholemaster
      - title: pihole-slave
        description: DNS settings for ad & tracker blocking
        icon: pihole.png
        url: http://0.0.0.200/admin/
        target: newtab
        # statusCheck: true
        id: 4_1267_piholeslave
      - title: Nginx Proxy Manager
        description: Reverse Proxy Configuration
        icon: nginxproxymanager.png
        target: newtab
        url: http://0.0.0.0:7818/
        # statusCheck: true
        id: 5_1267_nginxproxymanager
      - title: Guacamole
        icon: guacamole.png
        target: newtab
        url: http://0.0.0.27:8080
  - name: Download
    icon: fas fa-hand-point-up
    displayData:
      sortBy: last-used
    items:
      - title: Deluge
        icon: deluge.png
        target: newtab
        url: http://0.0.0.0:8112
      - title: JDownloader
        icon: jdownloader2.png
        target: newtab
        url: http://0.0.0.27:58020/
      - title: MEGASync
        icon: mega.png
        target: newtab
        url: http://0.0.0.0:6344
      - title: TubeSync
        target: newtab
        icon: tubesync.png
      - title: Deemix
        icon: deemix.png
        target: newtab
        url: http://0.0.0.0:7345
      - title: Prowlarr
        icon: prowlarr.png
        target: newtab
        url: http://0.0.0.0:9492/
        id: 1_834_prowlarr
      - title: Radarr
        icon: radarr.png
        target: newtab
        url: http://0.0.0.0:2348/
        id: 2_834_radarr
      - title: Sonarr
        icon: sonarr.png
        target: newtab
        url: http://0.0.0.0:1127/
        id: 3_834_sonarr
  - name: Media
    icon: fas fa-film
    displayData:
      sortBy: last-used
    items:
      - title: Plex
        icon: plex.png
        target: newtab
        url: http://0.0.0.0:32400/web/index.html#!/
      - title: Jellyfin
        icon: jellyfin.png
        target: newtab
        url: http://0.0.0.27:21345
      - title: Pasta
        icon: pasta.png
        target: newtab
        url: http://0.0.0.0:321312/
      - title: Filebot
        icon: filebot.png
        target: newtab
        url: http://0.0.0.0:7001
      - title: PodGrab
        icon: podgrab.png
        target: newtab
        url: http://0.0.0.0:8521
      - title: CalbreWeb
        icon: calibreweb.png
        target: newtab
        url: http://0.0.0.0:8223
      - title: Bazarr
        icon: bazarr.png
        target: newtab
        url: http://0.0.0.0:4555
      - title: Tautulli
        icon: tautulli.png
        target: newtab
        url: http://0.0.0.0:8213
  - name: Cloud
    icon: fas fa-cloud
    displayData:
      sortBy: last-used
    items:
      - title: Bitwarden
        icon: bitwarden.png
        target: newtab
        url: https://xxxx.mydomain.com/login
      - title: Gitea
        icon: gitea.png
        target: newtab
        url: https://xxxx.mydomain.com
      - title: Nextcloud
        icon: nextcloud.png
        target: newtab
        url: https://xxxx.mydomain.com
      - title: Kitana
        icon: kitana.png
        target: newtab
        url: http://0.0.0.0:22117/token
  - name: Tools
    icon: fad fa-hammer
    displayData:
      sortBy: last-used
    items:
      - title: Krusader
        icon: krusader.png
        target: modal
        url: http://0.0.0.0:6080/vnc.html?resize=remote&host=0.0.0.0&port=6080&autoconnect=1/
      - title: QDirStat
        icon: qdirstat.png
        target: modal
        url: http://0.0.0.0:7815
      - title: Czkawka
        icon: czkawka.png
        target: newtab
        url: http://0.0.0.0:7821
      - title: Filebrowser
        icon: filebrowser.png
        target: newtab
        url: http://0.0.0.0:8180
      - title: Filezilla
        icon: filezilla.png
        target: newtab
        url: http://0.0.0.0:3109
      - title: SyncThing
        icon: syncthing.png
        target: newtab
        url: http://0.0.0.0:8384
      - title: Virt-Manager
        icon: virtman.png
        target: newtab
        url: http://0.0.0.0:8808
      - title: diagrams.net
        icon: draw.png
        target: newtab
        url: http://0.0.0.0:3699
  - name: Productivty
    icon: fas fa-pen-nib
    displayData:
      sortBy: last-used
    items:
      - title: Wallabag
        icon: wallabag.png
        target: newtab
        url: http://0.0.0.0:6500
      - title: Snipe-IT
        icon: snipeit.png
        target: newtab
        url: http://0.0.0.0:8019
      - title: Grocy
        icon: grocy.png
        target: newtab
        url: http://0.0.0.0:9283
  - name: Monitor
    icon: fas fa-hat-wizard
    displayData:
      sortBy: last-used
    items:
      - title: Grafana
        icon: grafana.png
        target: newtab
        url: http://0.0.0.0:3000/login
      - title: NetData
        icon: netdata.png
        target: newtab
        url: http://0.0.0.0:19999/#after=-300;before=0;=undefined;theme=slate;utc=America%2FNew_York
  - name: External Services
    icon: fas fa-globe
    displayData:
      sortBy: last-used
    items:
      - title: Protonmail
        icon: protonmail.png
        target: newtab
        url: https://protonmail.com/
      - title: Cloudflare
        description: Web Proxy
        icon: cloudflare.png
        url: https://www.cloudflare.com/
      - title: ifconfig.io
        description: Find my IP
        icon: ip.png
        target: modal
        url: https://ifconfig.io
      - title: Private Internet Access
        description: VPN
        icon: pia.png
        url: https://www.privateinternetaccess.com/
  - name: News
    icon: fas fa-newspaper
    displayData:
      sortBy: last-used
    items:
      - title: Hackernews
        icon: favicon
        target: newtab
        url: https://news.ycombinator.com/
      - title: Reddit
        icon: favicon
        target: newtab
        url: https://www.reddit.com/r/all/
      - title: /g/
        icon: favicon
        target: newtab
        url: https://boards.4channel.org/g/catalog
```

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
