### ISSUE TITLE
[BUG] statusCheck in Items not being honored when set at appConfig level

### ISSUE THREAD

**Issue by ridizy** [Lissy93/dashy#650]
### Environment

Self-Hosted (Docker)

### Version

2.0.8

### Describe the problem

I am setting `statusCheck` to `true` at the appConfig level.  I then have some items where I don't want the status check to be enabled, and I am setting those to `statusCheck: false`.  However, those items still have the status check enabled.

For example,  I have:
```
appConfig:
  theme: default
  language: en
  layout: auto
  iconSize: medium
  statusCheck: true
```

And then I have:
```
items:
  - title: App1
    description: My App 1
    icon: favicon
    url: https://app1.example.com
    id: 0_393_app1
  - title: App2
    description: My App 2
    icon: favicon
    url: http://app2.example.com
    id: 1_393_app2
```

I would expect `App 1` to have the status check enabled and `App 2` to not have it enabled.  However, both items are showing up on the dashboard with the status check enabled.

### Additional info

No errors are being thrown

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
