### ISSUE TITLE
[QUESTION] Where is sub-sections docs ?

### ISSUE THREAD

**Issue by cfouche3005** [Lissy93/dashy#657]
### Question

I want to use sub-section added in 2.0.7 but I couldn't find how to in the documentation.

### Category

Theming & Layout

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Do you mean like multi-page support? It's [here](https://github.com/Lissy93/dashy/blob/master/docs/pages-and-sections.md) :)
The website is sometimes a bit out-of-date, but you can always find the latest version here: [`/docs`](https://github.com/Lissy93/dashy/tree/master/docs#readme)

**Comment by Lissy93** [comment]
Oh, you mean sub-items. Oops, looks like I forgot to write the docs for that...

I'll add that to the above link when I get a moment, sorry about that. But in short, you can do it like:

```yaml
- name: Dev & Cloud
  icon: far fa-code
  items:
  - title: Normal Item
    icon: favicon
    url: https://dev-environment-central.lan/
  - title: Sub Items Example # title is optional
    subItems: # An array of sub-items
    - title: JavaScript
      url: https://developer.mozilla.org
      icon: si-javascript
      color: '#F7DF1E'
    - title: TypeScript
      url: https://www.typescriptlang.org/docs
      icon: si-typescript
      color: '#3178C6'
    - title: Svelt
      url: https://svelte.dev/docs
      icon: si-svelte
      color: '#FF3E00'
    - title: Go
      url: https://go.dev/doc
      icon: si-go
      color: '#00ADD8'
    - title: Rust
      url: https://doc.rust-lang.org/reference
      icon: si-rust
      color: '#000000'
    - title: Docker
      url: https://docs.docker.com/
      icon: si-docker
      color: '#2496ED'
```
