### ISSUE TITLE
[QUESTION] <title>

### ISSUE THREAD

**Issue by Skyfay** [Lissy93/dashy#727]
### Question

I'm trying to deploy Dashy from a subdirectory but it doesn't work.
Unfortunately, my discussion on the subject is closed.

I did everything that was explained to me but it doesn't work.
Does anyone have any other ideas what I did wrong?

WebServer (Nginx):
`location /subdirectory { 
 proxy_pass http://172.19.0.140:80/; add_header Access-Control-Allow-Origin *; 
 }`
 Dashy Config:
`routingMode: hash`
Docker-Compose file:
`- BASE_URL=/subdirectory`

https://github.com/Lissy93/dashy/discussions/666

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
As mentioned on your previous ticked - this is something that is configured on your web server, and **not** within Dashy. 

You will need to use the resources I shared with you previously, and do it yourself. 

Please check previous issues before opening a new one, as this same question has been asked before in: #31, #193, #249, #351, #543, #600, #628 and #666.

**Comment by Skyfay** [comment]
> As mentioned on your previous ticked - this is something that is configured on your web server, and **not** within Dashy.
> 
> You will need to use the resources I shared with you previously, and do it yourself.
> 
> Please check previous issues before opening a new one, as this same question has been asked before in: #31, #193, #249, #351, #543, #600, #628 and #666.

I've done these steps and it doesn't work!
I have other services running like this and they work, so there must be something misconfigured in Dashy that is causing these errors.

**Comment by Lissy93** [comment]
Many other users are running from sub paths, but if you've found areas for configuration improvement, then do feel free to fix them.

But I have already tried to help you and got nowhere, I am not going to write your server config files for you.

**Comment by Skyfay** [comment]
> Many other users are running from sub paths, but if you've found areas for configuration improvement, then do feel free to fix them.
> 
> But I have already tried to help you and got nowhere, I am not going to write your server config files for you.

It's not about that you should write my server config. But somehow there is no exact instruction how it works with subdirectories. Everything is entangled and you have to search for it awkwardly.

I looked at every single topic on this topic and implemented everything exactly the same way.
Still it doesn't work.

**Comment by Lissy93** [comment]
Did you try the [sample web server configs](https://github.com/Lissy93/dashy/blob/master/docs/management.md#web-server-configuration=) in the management docs? After that, all you need to do is set the `BASE_URL` env var, then under appConfig set `routingMode: hash`. That worked for me. But really Dashy is intended to be run on a sub-domain.

You could try homer or another dashboard app, might be a better fit for you. I put some [alternatives in the docs](https://github.com/Lissy93/dashy/#alternatives-=).

**Comment by Skyfay** [comment]
> Did you try the [sample web server configs](https://github.com/Lissy93/dashy/blob/master/docs/management.md#web-server-configuration=) in the management docs? After that, all you need to do is set the `BASE_URL` env var, then under appConfig set `routingMode: hash`. That worked for me. But really Dashy is intended to be run on a sub-domain.
> 
> You could try homer or another dashboard app, might be a better fit for you. I put some [alternatives in the docs](https://github.com/Lissy93/dashy/#alternatives-=).

Yes, i did that.
I would don't want to use another dashboard because I like this one a lot!

When i restart Dashy, it works with the subdir:
![image](https://user-images.githubusercontent.com/76796007/173236106-bac81753-5178-4364-b39f-75250bae2426.png)
After the start it just looks like this:
![image](https://user-images.githubusercontent.com/76796007/173236183-0b363cf1-ab85-46b8-a6d9-f96f27d0e4a5.png)

**Comment by Lissy93** [comment]
There should be a message [in the browser console](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console=), that will show what's going on.
But I guess it's a 404 because it's looking for the assets at the wrong location 😕

The initialization screen doesn't have any assets, which would be how that loads okay.

**Comment by Skyfay** [comment]
> There should be a message [in the browser console](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console=), that will show what's going on. But I guess it's a 404 because it's looking for the assets at the wrong location 😕
> 
> The initialization screen doesn't have any assets, which would be how that loads okay.

Yes it is:
![image](https://user-images.githubusercontent.com/76796007/173236764-6165595e-2e38-4a82-8dc1-b23069df923e.png)

**Comment by Lissy93** [comment]
Yeah, I'm really not sure why that isn't working.
Sorry :/

**Comment by Skyfay** [comment]
Ok :(
Thanks for the help anyway. I'll test it a bit more. If I find a solution I will share it here.

**Comment by jdjingdian** [comment]
@Lissy93 Hello Lissy, here is my nginx conf

``` nginx
server {
	    listen 8443 ssl default_server;
	    listen [::]:8443 ssl default_server;
  		...
      location /home/ {
            proxy_pass http://192.168.4.30:4000/;
            rewrite conf.yml https://www.mydomain.com:8443/home/conf.yml redirect;
            add_header Access-Control-Allow-Origin *;
      }
```



I'm running dashy with docker-compose

``` yaml
version: '3.8'
services:
    dashy:
        container_name: dashy
        image: 'lissy93/dashy:latest'
        ports:
          - '4000:80'
        environment:
          - BASE_URL=/home
        volumes:
          - '/srv/dev-disk-by-uuid-ec7fe9aa-6ff5-4df4-a757-d2b97ed029b2/docker/dashy/conf.yml:/app/public/conf.yml'
          - '/srv/dev-disk-by-uuid-ec7fe9aa-6ff5-4df4-a757-d2b97ed029b2/docker/dashy/icons/:/app/public/item-icons/icons'

        
        restart: unless-stopped
        healthcheck:
          test: ['CMD', 'node', '/app/services/healthcheck']
          interval: 1m30s
          timeout: 10s
          retries: 3
          start_period: 40s
        
```

What I got just like this

[![image](https://user-images.githubusercontent.com/76796007/173236183-0b363cf1-ab85-46b8-a6d9-f96f27d0e4a5.png)](https://user-images.githubusercontent.com/76796007/173236183-0b363cf1-ab85-46b8-a6d9-f96f27d0e4a5.png)



One more thing

If I set up auth in appConfig like this

``` 
auth:
    users:
      - user: myusername
        hash: b38529dc97815df7eb0af68b723733734f9aa432660c6045c3cbbcb9df4aa2f3
        type: admin
```

https://www.mydomain.com:8443/home/ will jump to https://www.mydomain.com:8443/login
