### ISSUE TITLE
[FEATURE_REQUEST] Setting the amount of information displayed by statuscheck

### ISSUE THREAD

**Issue by Tinyblargon** [Lissy93/dashy#729]
### Is your feature request related to a problem? If so, please describe.

When using the `statusCheck` feature hovering over the green dot it will for some items it displays a message along the lines of:
```
server responded with <code> OK <time>
```

For other items it displays a message like:
```
example.com responded with <code> OK <time>
```

In my scenario we are using `statusCheckUrl` to do health checks to the back-ends of our services with internal only domain names. These internal only domain names are showing in the statuschecks, and should not be known to users using the dashboard.

### Describe the solution you'd like

Could an option be created to set the amount of information given from the statuscheck on an item by item basis?
Examples:

1. Setting it to `full` would show the information as it is currently implemented .
```yaml
statusCheckInfo: full
```

2. Setting it to `limited` would only show the check mark and time.
```yaml
statusCheckInfo: limited
```

3. Setting it to `none` would prevent the status windows from appearing when hovering over the status icon.
```yaml
statusCheckInfo: none
```

Example in item configuration:
```yaml
    items:
      - title: example
        url: https://example.com/
        statusCheckInfo: limited
        statusCheckUrl: http://internal.example.com/
```

### Priority

Low (Nice-to-have)
