### ISSUE TITLE
[QUESTION] hideComponents

### ISSUE THREAD

**Issue by shadowking001** [Lissy93/dashy#82]
Hello @Lissy93 

Still rocking dashboard !
I tried to add the hideComponents object, but it seems like I'm not doing it as expected :

![dashy_hidecomponents_1](https://user-images.githubusercontent.com/43928955/124665090-97f3a380-deac-11eb-8d72-188a1b83be6c.PNG)

Any clue about what I did wrong ?

**Comment by Lissy93** [comment]
Heya @shadowking001 😄 
Hmm, so what you've got looks to be correct to me. What warning does that exclamation mark show when you hover over it?

My guess is that an older version of the app has been cashed, the latest version *should* be available after a page refresh, but sometimes the service worker doesn't pick up the changes properly. Do you see any errors in the dev tools (F12 --> Console)? Try doing a hard refresh (Ctrl + Alt + F5 / refresh btn)

I just tested it out with the below snippet, and it seems to work for me.
```yaml
appConfig:
  hideComponents:
    hideFooter: true
```

Let me know if none of that works, and I'll look into it further :)

**Comment by shadowking001** [comment]
![dashy_hidecomponents_1](https://user-images.githubusercontent.com/43928955/124824653-f7b48200-df72-11eb-8a36-644fae1b84b4.png)
![dashy_hidecomponents_2](https://user-images.githubusercontent.com/43928955/124824677-ff742680-df72-11eb-996d-b41167b8ed6a.png)

Conf file seems to have been overwritten successfully :

```
appConfig:
  theme: "material-dark"
  fontAwesomeKey: "0821c65656"
  layout: "auto"
  statusCheck: true
  statusCheckInterval: 30
  faviconApi: "faviconkit"
  iconSize: "medium"
  hideComponents:
    hideFooter: true
pageInfo:
  title: ...
```
