### ISSUE TITLE
[BUG] Edit Button on Subpage scrambles the entire config of this page

### ISSUE THREAD

**Issue by Zwixx** [Lissy93/dashy#841]
### Environment

Self-Hosted (Docker)

### System

Firefox, Docker 20.10.16, Ubuntu 22.04.1

### Version

2.1.1

### Describe the problem

Hello, I use dashy for a while and now tried subpages. I made my own subpage in a Editor and all worked fine. Then I tried to edit this page in the build-in editor.

On the main page (right-click edit) all works fine. In the Subpage on every button I click on edit, the same dialog with the same title and data are shown. The data are shown from another button in this page, but not the right one. If I saved this button the entire page is scrambled and all buttons show the same title.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
There will be an error in the console, you'll need to share that ([here's how](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console))

**Comment by Zwixx** [comment]
Yes, there is one:

Dashy  V2.1.1 🚀 
[dashy.390818b7.js:1:54365](http://x.x.x.x:4000/js/dashy.390818b7.js)
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://x.x.x.x:4000/js/dashy.390818b7.js
Source-Map-Adresse: dashy.390818b7.js.map

But only one time.
Then, another time the following warning every time I open this Subpage:

⚠️ Warning ⚠️ 
The path to 'google' could not be resolved 

I hope this helps

**Comment by Lissy93** [comment]
Okay, yup, and share the relevant parts of your config.

This isn't a bug with Dashy, but rather an issue with your config. It could be a CORS error, or a typo in the path to the page, or something like that.

**Comment by Zwixx** [comment]
I made a test file

conf.yaml

```
# yaml-language-server: $schema=schema.json
appConfig:
  theme: material-dark
  backgroundImg: /img/bg.png
  layout: auto
  iconSize: medium
  language: de
  routingMode: hash
pageInfo:
  title: Dashboard
  description: HomeLab - Standard
  navLinks:
    - title: Documentation
      path: https://dashy.to/docs
      target: newtab
  footerText: ''
sections:
  - name: Section 1 - YT
    items:
      - title: YouTube - Barlow's Hexer Blog
        description: ''
        icon: icons/youtubedl.png
        url: http://www.youtube.com/watch?v=8QI8zF0Lqis
        id: 0_1088_youtubebarlowshexerblog
      - title: YouTube
        description: ''
        icon: icons/youtubedl.png
        url: https://www.youtube.com/
        id: 1_1088_youtube
pages:
  - name: TestSeite
    path: conf.test.yaml
```

conf.test.yaml:
```
# yaml-language-server: $schema=schema.json
---
# Page meta info, like heading, footer text and nav links
pageInfo:
  title: Dashy - A
  description: A, was sonst :)

# Optional app settings and configuration
appConfig:
  theme: material-dark
  backgroundImg: /img/bg.png
  routingMode: hash

# Main content - An array of sections, each containing an array of items
sections: # An array of sections
- name: Test
  items:
  - description: ""
    icon: favicon
    title: "The Example"
    url: https://example.com
  - description: ""
    icon: favicon
    title: "Bing"
    url: https://bing.com

```
