### ISSUE TITLE
[QUESTION] Is my gl-disk-space widget config correct?

### ISSUE THREAD

**Issue by yed01** [Lissy93/dashy#848]
### Question

Hi,
I am not able to get the gl-disk-space widget to work.
All the other Glances-widgets are working, and all have the same configuration.

![d](https://user-images.githubusercontent.com/98295983/184890750-155a67c7-1147-4f2a-a01e-194ccd20a1f7.jpg)

```
- name: Disk Space
  icon: fas fa-hdd
  widgets:
  - type: gl-disk-space
    options:
      hostname: https://domain.com
      username: glances
      password: xxxxx 
      useProxy: true
```

Help would be appreciated.

### Category

Widgets

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
