### ISSUE TITLE
[QUESTION] How can I control the number of widgets per row in a section?

### ISSUE THREAD

**Issue by Emeraude998** [Lissy93/dashy#860]
### Question

So I have a dashboard containing multiple widgets in a single section. I would like to have all 3 on one row, similar to how it's displayed in the section page. I searched through the documentation and I don't see anything similar to the field `itemCountX` used for the items for the widgets.

Widgets in the Home Page : 
![2022-08-20 01_20_52-Dashy](https://user-images.githubusercontent.com/70350808/185719070-26088c95-3cc2-4244-93ff-4ecdd4e28bb7.png)

Widgets in the Section Page : 
![2022-08-20 01_21_08-Dashy](https://user-images.githubusercontent.com/70350808/185719094-23e1cb93-1457-49b4-9500-75024a05ecf4.png)

If it's useful, here is the config I'm currently using : 
```
appConfig:
  theme: colorful
  layout: auto
  iconSize: medium
  language: fr
pageInfo:
  title: Dashy
  description: Welcome to your Home Lab!
  navLinks:
    - title: GitHub
      path: https://github.com/Lissy93/dashy
    - title: Documentation
      path: https://dashy.to/docs
  footerText: ''
sections:
  - name: Host Info
    displayData:
      cols: 5
      cutToHeight: true
      sectionLayout: grid
      itemCountX: 3
    widgets:
      - type: gl-current-cpu
        options:
          hostname: http://192.168.1.100:61208
        id: 0_842_glcurrentcpu
      - type: gl-current-mem
        options:
          hostname: http://192.168.1.100:61208
        id: 1_842_glcurrentmem
      - type: gl-disk-space
        options:
          hostname: http://192.168.1.100:61208
        id: 2_842_gldiskspace
```
I'm clearly not an expert when it comes to CSS and custom style coding... Please help

### Category

Widgets

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Emeraude998** [comment]
Issue has not been resolved as of yet.

**Comment by Lissy93** [comment]
Heya @Emeraude998 
Sorry for the veryyyy late reply...

So this is something that I can add to the todo list to get built in natively. 


But in the meantime, it should be possible with a tiny bit of CSS.
The widget container has a class of `.widget-list`

#### Option 1) - Flex

Just adding the following should display widgets horizontally:

```css
.widget-list {
  display: flex;
  align-items: flex-start;
  justify-content: space-around;
}
```
Or, to make it dynamic depending on available space, add `flex-wrap: wrap;`

---

#### Option 2) - Grid

If you want widgets to display in a fixed grid-type layout, then you can instead use `display: `[`grid`](https://developer.mozilla.org/en-US/docs/Web/CSS/grid)`;` For example, for a 2-col grid, you could do something like:

```css
.widget-list {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
}
```
---

#### Targetting a Single Section
If you only want to do this for a single section, then you can preface the selector with that section's ID - you can find this in the developer tools. For example: `.section-outer-home-section-1 .widget-list { }`

---

#### How to Apply
You can either set these styles [through the UI](https://github.com/Lissy93/dashy/blob/master/docs/theming.md#setting-custom-css-in-the-ui) (Config --> Styles --> Custom CSS), or you can minify them and add it under `appConfig.customCss` 

---

#### More Options

You can find, test out, and apply more layout options using the browsers developer tools. That way you can preview changes live, then just copy the changed CSS into your config.
