### ISSUE TITLE
docker-compose crashes on initialization

### ISSUE THREAD

**Issue by mybuntu-git2** [Lissy93/dashy#868]
### Environment

Self-Hosted (Docker)

### System

ubuntu server 20.04 

### Version

1.9.9 (arm64v8 docker image pulled today)

### Describe the problem

fails to start.
says something is wrong with the config file.

```
Checking config file against schema...

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Warning: 29 issues found in config file  
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. additionalProperties must NOT have additional properties in /appConfig
2. additionalProperties must NOT have additional properties in /appConfig
3. additionalProperties must NOT have additional properties in /appConfig
4. additionalProperties must NOT have additional properties in /appConfig
5. additionalProperties must NOT have additional properties in /appConfig
6. additionalProperties must NOT have additional properties in /sections/0/items/0
7. additionalProperties must NOT have additional properties in /sections/0/items/1
8. additionalProperties must NOT have additional properties in /sections/0/items/2
9. additionalProperties must NOT have additional properties in /sections/0/items/6
10. additionalProperties must NOT have additional properties in /sections/0/items/7
```

my docker-compose.yml is the following:
```
---
version: "3.8"
services:
  dashy:
    image: lissy93/dashy:arm64v8
    container_name: Dashy
    deploy:
      resources:
        limits:
         cpus: '0.5'
         memory: 350M
    volumes:
      - '/home/ubuntu/dashy/conf/dashy_conf.yml:/app/public/conf.yml'
    ports:
      - 4000:80
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      - UID=1000
      - GID=1000
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
```
the same happens if I remove the resources limits. previously, the same config was working fine (same docker-compose.yml file). similarly, dashy_conf.yml has not changed.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
