### ISSUE TITLE
[QUESTION] Pages section not routing? Possibly setup incorrectly.

### ISSUE THREAD

**Issue by bmcgonag** [Lissy93/dashy#869]
### Question

I'm trying to setup some extra pages, following your documentation, I've setup a `servers.yml` inside the `public` directory (same location as my main `conf.yml` file.

In the `conf.yml` file I added a top level `pages` section with the name and path attributes for it.

Section in `conf.yml` below

```
appConfig:
  theme: colorful
  layout: auto
  iconSize: small
  language: en

pages:
- name: Servers
  path: 'servers.yml'

pageInfo:
  title: Home Lab
  description: Welcome to your Home Lab!
  footerText: ''
sections:
  - name: Servers
    icon: fas fa-server
    items:
```

The main page works fine, and the "Servers" button / tab shows up in the upper right. When clicked, the URL path changes to http://<ip>:<port>/home/servers (which I presume is right), but the page does not change.  If I then click in the URL bar and press the Enter key, the screen shows the message:

`Cannot GET /home/servers`

My `servers.yml` is as follows:

```
sections:
  - name: Bia Info
    widgets:
      - type: gl-current-cpu
        options:
          hostname: http://<server1-ip>:61208
        id: 0_696_glcurrentcpu
      - type: gl-current-mem
        options:
          hostname: http://<server1-ip>:61208
        id: 1_696_glcurrentmem
  - name: Aria Info
    widgets:
      - type: gl-current-cpu
        options:
          hostname: http://<server2-ip>:61208
        id: 0_809_glcurrentcpu
      - type: gl-current-mem
        options:
          hostname: http://<server2-ip>:61208
        id: 1_809_glcurrentmem
```

I'm excited to use this feature, but I'm obviously doing something wrong.  Any help is greatly appreciated.

I also don't know where to see the version, but I did a `docker-compose pull` and `docker-compose up -d` this morning to make sure I'm on the latest.

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
