### ISSUE TITLE
[QUESTION][SOLVED] I just can't seem to get my multi-page setup to work

### ISSUE THREAD

**Issue by coalwater** [Lissy93/dashy#929]
### Question

I'm trying to create a new dashy page for my frequently used links at work in a separate page, to make that my homepage in my work laptop.

I've been struggling for weeks, every now and then I keep fiddling with my `conf.yml` and `pages`, but it just never seems to work out.

I've looked into the issues and I see there's two groups of people, some who their setup just works, and some that can't get things working, and I'm starting to think it might be related to how the application is deployed.

I'm gonna share snippets here from my `conf.yml` and `work.yml` and see if you can spot something that's immediately looks wrong.

```yml
# conf.yml
pageInfo: title: My home page

appConfig:
  language: en
  startingView: default
  iconSize: medium
  routingMode: hash
  preventWriteToDisk: true
  preventLocalSave: true
  disableConfiguration: true
  disableContextMenu: true
  enableServiceWorker: false
pages:
  - name: My home page
    path: 'conf.yml'
  - name: Work
    path: 'work.yml'


sections:
  - name: Start
    widgets:
      - type: clock
        options:
          timeZone: Europe/Amsterdam
          format: en-GB
          hideDate: false
# snip
```

```yml
# work.yml
# copied from somewhere in the docs
sections:
- name: Work
  icon: far fa-code
  items:
    - title: Normal Item 1
    - title: Normal Item 2
    - subItems:
      - icon: si-javascript
        title: JavaScript
        url: https://developer.mozilla.org
      - icon: si-typescript
        title: TypeScript
        url: https://www.typescriptlang.org/docs
      - icon: si-svelte
        title: Svelt
        url: https://svelte.dev/docs
      - icon: si-go
        title: Go
        url: https://go.dev/doc
```

My current setup is deployed on a local kubernetes cluster,
the request goes through `cloudflare -> firewall ->  traefik (pod) -> dashy (pod)`  
I can verify that the `work.yml` file is accessible by doing `curl https://mydomain.com/work.yml`

If I try to click the work section on the top nav I get this error on the console

> No section named 'work' was found 

Which doesn't make sense because I thought dashy would be loading the full yml file, not just searching for a `section` called `work`

Another symptom that I'm not sure if it's related, it seems that the `routingMode: hash` is not being picked up, and dashy is still using `history`

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
