### ISSUE TITLE
[BUG] Unable to fetch some icons

### ISSUE THREAD

**Issue by Ramzh** [Lissy93/dashy#985]
### Environment

Self-Hosted (Docker)

### System

Firefox 107

### Version

2.1.1

### Describe the problem

Using homelab icons, some icons are not being fetched correctly, for example plex-new-transparent using the hl method: hl-plex-new-transparent/hl-plexnewtransparent/hl-plex_new_transparent

Instead the broken default logo is used

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hi @Ramzh 
Please can you share the output of the browser console ([how](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console)) and the relevant parts of your config.
Without that info, it's not possible to know what your issue is.

**Comment by Ramzh** [comment]
> Hi @Ramzh Please can you share the output of the browser console ([how](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console)) and the relevant parts of your config. Without that info, it's not possible to know what your issue is.

Apologies, here is the config:

```- name: Streaming
    items:
      - title: Plex
        description: Films and TV Shows Streaming
        url: http://192.168.50.158:32400/web/index.html#!/
        icon: hl-plexnewtransparent #hl-plex-new-transparent 
        target: newtab
 ```
Console:
![image](https://user-images.githubusercontent.com/20802073/204137630-5e4eed24-bcd1-4ee5-b890-8bbd1c8d5512.png)
![image](https://user-images.githubusercontent.com/20802073/204137682-f00a574f-4677-4499-ad76-e941c04138a9.png)

it works fine if I use the URL 
`https://raw.githubusercontent.com/walkxcode/Dashboard-Icons/main/png/plex-new-transparent.png`

**Comment by Lissy93** [comment]
You've got a typo.
`icon: hl-plexnewtransparent` should be `icon: hl-plex-new-transparent`

**Comment by Lissy93** [comment]
Just to be sure, I've tested it with the following config, and it seems to work okay, so I'm going to go ahead and close the ticket. But let me know if you're still having issues.

<p align="right"><img align="right" width="350" src="https://user-images.githubusercontent.com/1862727/204144580-df25f367-e519-4d7a-921e-8c69ebbdf8c1.png"></p>

```yaml
sections:
- name: 'Test Issue #985'
  icon: si-plex
  items:
  - title: Plex
    icon: hl-plex
  - title: Plex New
    icon: hl-plex-new 
  - title: Plex Transparent
    icon: hl-plex-new-transparent 
  - title: Plex Square
    icon: hl-plex-square 
  - title: Plex Drive
    icon: hl-plexdrive 
  - title: Plex Requests
    icon: hl-plexrequests 
  - title: Material
    icon: mdi-plex
  - title: Simple
    icon: si-plex
```

I hope that helps :)
